//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <arpa/inet.h>
#include <assert.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_1074c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
char *function_1076c(char *haystack, char *needle);
int32_t function_10778(char *format, ...);
int32_t function_10784(int32_t fd, int32_t *buf, int32_t nbytes);
void function_10790(char *s);
int32_t function_1079c(int32_t fd, struct sockaddr *addr, int32_t *addr_len);
int32_t function_107a8(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s);
char *function_107b4(char *dest, char *src);
int32_t function_107c0(int32_t *newthread, int32_t *attr,
                       int32_t *(*start_routine)(int32_t *), int32_t *arg);
int32_t function_107cc(char *s);
int32_t function_107d8(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
int32_t function_107e4(char *command);
void function_107f0(void);
void function_107fc(int32_t status);
int32_t function_10808(char *s);
int32_t function_10814(int32_t fd, struct sockaddr *addr, int32_t len);
int32_t *function_10820(int32_t *s, int32_t c, int32_t n);
int32_t function_1082c(int32_t fd, int32_t *buf, int32_t n);
void function_10838(int32_t *retval);
int32_t function_10844(int32_t fd, int32_t how);
int32_t function_10850(int32_t fd, int32_t n);
int32_t function_1085c(char *s, char *format, ...);
int32_t function_10868(int32_t domain, int32_t type, int32_t protocol);
int32_t function_10874(char *cp);
void function_10880(void);
int32_t function_1088c(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10898(int32_t fd);
int32_t function_108a4(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_108b0(int32_t fd, struct sockaddr *addr, int32_t len);
void function_108bc(char *assertion, char *file, int32_t line, char *function);
int32_t function_108c8(int32_t i_a1, int32_t i_a2);
int32_t function_10b40(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_10b4c(void);
int32_t function_10b70(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_10bc4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10bd8(void);
int32_t function_10bdc(char *p_a1);
int32_t function_10c28(int32_t i_a1);
int32_t function_10dbc(int32_t i_a1);
int32_t function_10ed8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10f14(void);
int32_t function_10f18(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = -0x1cae0000;   // 0x10b5c
int32_t i_g2 = 0;             // 0x11022
int32_t i_g3 = 46;            // 0x114a4
int32_t i_g4 = 0x10bd9;       // 0x21f08
struct _IO_FILE *p_g5 = NULL; // 0x22090
int32_t i_g6;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());

// ------------------------ Functions -------------------------

// Address range: 0x1074c - 0x10758
int32_t function_1074c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x1074c
    return function_10b4c();
}

// Address range: 0x1076c - 0x10778
char *function_1076c(char *haystack, char *needle) {
    // 0x1076c
    return strstr(haystack, needle);
}

// Address range: 0x10778 - 0x10784
int32_t function_10778(char *format, ...) {
    // 0x10778
    return printf(format);
}

// Address range: 0x10784 - 0x10790
int32_t function_10784(int32_t fd, int32_t *buf, int32_t nbytes) {
    // 0x10784
    return read(fd, buf, nbytes);
}

// Address range: 0x10790 - 0x1079c
void function_10790(char *s) {
    // 0x10790
    perror(s);
}

// Address range: 0x1079c - 0x107a8
int32_t function_1079c(int32_t fd, struct sockaddr *addr, int32_t *addr_len) {
    // 0x1079c
    return accept(fd, addr, addr_len);
}

// Address range: 0x107a8 - 0x107b4
int32_t function_107a8(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s) {
    // 0x107a8
    return fwrite(ptr, size, n, s);
}

// Address range: 0x107b4 - 0x107c0
char *function_107b4(char *dest, char *src) {
    // 0x107b4
    return strcpy(dest, src);
}

// Address range: 0x107c0 - 0x107cc
int32_t function_107c0(int32_t *newthread, int32_t *attr,
                       int32_t *(*start_routine)(int32_t *), int32_t *arg) {
    // 0x107c0
    return pthread_create(newthread, attr, start_routine, arg);
}

// Address range: 0x107cc - 0x107d8
int32_t function_107cc(char *s) {
    // 0x107cc
    return puts(s);
}

// Address range: 0x107d8 - 0x107e4
int32_t function_107d8(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x107d8
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x107e4 - 0x107f0
int32_t function_107e4(char *command) {
    // 0x107e4
    return system(command);
}

// Address range: 0x107f0 - 0x107fc
void function_107f0(void) {
    // 0x107f0
    __gmon_start__();
}

// Address range: 0x107fc - 0x10808
void function_107fc(int32_t status) {
    // 0x107fc
    exit(status);
}

// Address range: 0x10808 - 0x10814
int32_t function_10808(char *s) {
    // 0x10808
    return strlen(s);
}

// Address range: 0x10814 - 0x10820
int32_t function_10814(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x10814
    return bind(fd, addr, len);
}

// Address range: 0x10820 - 0x1082c
int32_t *function_10820(int32_t *s, int32_t c, int32_t n) {
    // 0x10820
    return memset(s, c, n);
}

// Address range: 0x1082c - 0x10838
int32_t function_1082c(int32_t fd, int32_t *buf, int32_t n) {
    // 0x1082c
    return write(fd, buf, n);
}

// Address range: 0x10838 - 0x10844
void function_10838(int32_t *retval) {
    // 0x10838
    pthread_exit(retval);
}

// Address range: 0x10844 - 0x10850
int32_t function_10844(int32_t fd, int32_t how) {
    // 0x10844
    return shutdown(fd, how);
}

// Address range: 0x10850 - 0x1085c
int32_t function_10850(int32_t fd, int32_t n) {
    // 0x10850
    return listen(fd, n);
}

// Address range: 0x1085c - 0x10868
int32_t function_1085c(char *s, char *format, ...) {
    // 0x1085c
    return sprintf(s, format);
}

// Address range: 0x10868 - 0x10874
int32_t function_10868(int32_t domain, int32_t type, int32_t protocol) {
    // 0x10868
    return socket(domain, type, protocol);
}

// Address range: 0x10874 - 0x10880
int32_t function_10874(char *cp) {
    // 0x10874
    return inet_addr(cp);
}

// Address range: 0x10880 - 0x1088c
void function_10880(void) {
    // 0x10880
    abort();
}

// Address range: 0x1088c - 0x10898
int32_t function_1088c(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x1088c
    return recv(fd, buf, n, flags);
}

// Address range: 0x10898 - 0x108a4
int32_t function_10898(int32_t fd) {
    // 0x10898
    return close(fd);
}

// Address range: 0x108a4 - 0x108b0
int32_t function_108a4(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x108a4
    return send(fd, buf, n, flags);
}

// Address range: 0x108b0 - 0x108bc
int32_t function_108b0(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x108b0
    return connect(fd, addr, len);
}

// Address range: 0x108bc - 0x108c8
void function_108bc(char *assertion, char *file, int32_t line, char *function) {
    // 0x108bc
    __assert_fail(assertion, file, line, function);
}

// Address range: 0x108c8 - 0x10b18
int32_t function_108c8(int32_t i_a1, int32_t i_a2) {
    char *p_v1 = (char *)i_a2;            // 0x108e4
    char *p_v2 = strstr(p_v1, "daemonc"); // 0x108e4
    if (p_v2 != NULL) {
        // 0x10a4c
        return function_10dbc(*(int32_t *)(i_a2 + 4));
    }
    // 0x108f0
    if (strstr(p_v1, "daemons") == NULL) {
        // 0x10a7c
        puts("Cannot Find Command!\r");
        // 0x10a4c
        return -1;
    }
    int32_t i_v3 = socket(AF_INET, SOCK_STREAM, (int32_t)p_v2); // 0x10914
    if (i_v3 == -1) {
        // 0x10aac
        __assert_fail("sockfd_server != -1", "update-daemon.c", 129,
                      "ProcessServer");
        // 0x10ac8
        fwrite((int32_t *)"listen error!\n", 1, 14, p_g5);
        exit(1);
        // UNREACHABLE
    }
    float64_t f_v4 = __asm_vmov_i32(0); // 0x10924
    int16_t i_v5 = 2;                   // bp-56, 0x10930
    int32_t i_v6;                       // 0x108c8
    __asm_vst1_8(f_v4, i_v6);
    __asm_vst1_8(f_v4, i_v6);
    inet_addr("127.0.0.1");
    printf("Will Listening To Port[%d]\r\n", function_10bdc("22322"));
    if (bind(i_v3, (struct sockaddr *)&i_v5, 16) == -1) {
        // 0x10af0
        fwrite((int32_t *)"bind error!\n", 1, 12, p_g5);
        exit(1);
        return &i_g6;
    }
    // 0x1098c
    if (listen(i_v3, 512) == -1) {
        // 0x10ac8
        fwrite((int32_t *)"listen error!\n", 1, 14, p_g5);
        exit(1);
        // UNREACHABLE
    }
    while (true) {
        // 0x109c0
        puts("waiting for new connection...");
        int32_t i_v7 = 16; // bp-64, 0x109d8
        int32_t i_v8;      // bp-40, 0x108c8
        int32_t i_v9 = accept(i_v3, (struct sockaddr *)&i_v8, &i_v7); // 0x109dc
        int32_t i_v10 = i_v9; // bp-68, 0x109e4
        if (i_v9 == -1) {
            // 0x10a60
            fwrite((int32_t *)"Accept error!\n", 1, 14, p_g5);
        } else {
            // 0x109ec
            puts("A new connection occurs!");
            int32_t i_v11; // bp-60, 0x108c8
            if (pthread_create(&i_v11, NULL, (int32_t * (*)(int32_t *))0x10c28,
                               &i_v10) == -1) {
                // break -> 0x10a10
                break;
            }
        }
    }
    // 0x10a10
    fwrite((int32_t *)"pthread_create error!\n", 1, 22, p_g5);
    if (shutdown(i_v3, SHUT_WR) != -1) {
        // 0x10a3c
        puts("Server shuts down");
        // 0x10a4c
        return 0;
    }
    // 0x10a90
    __assert_fail("ret != -1", "update-daemon.c", 171, "ProcessServer");
    // 0x10aac
    __assert_fail("sockfd_server != -1", "update-daemon.c", 129,
                  "ProcessServer");
    // 0x10ac8
    fwrite((int32_t *)"listen error!\n", 1, 14, p_g5);
    exit(1);
    // UNREACHABLE
}

// Address range: 0x10b1c - 0x10b40
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10b1c
    int32_t i_v1; // 0x10b1c
    __libc_start_main(0x108c8, i_a2, (char **)&i_v1, (void (*)())0x10ed9,
                      (void (*)())0x108c8, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x10b40 - 0x10b44
int32_t function_10b40(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x10b40
    return i_a1;
}

// Address range: 0x10b4c - 0x10b68
int32_t function_10b4c(void) {
    int32_t i_v1 =
        *(int32_t *)((int32_t)&i_g1 + (int32_t)&i_g3 + 128); // 0x10b58
    if (i_v1 == 0) {
        int32_t i_v2; // 0x10b4c
        return i_v2;
    }
    // 0x10b64
    __gmon_start__();
    return &i_g6;
}

// Address range: 0x10b70 - 0x10bc4
int32_t function_10b70(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x10b70
    int32_t i_v1; // 0x10b70
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x10b70
    if (i_v3) {
        return i_a1;
    }
    bool i_v4; // 0x10b70
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x10ba8
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x10bb8
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    float64_t f_v6; // 0x10b70
    __asm_vqrshl_s8(f_v6, f_v6);
    return i_a1;
}

// Address range: 0x10bc4 - 0x10bd8
int32_t function_10bc4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    char *p_v1 = (char *)(0x40000 * i_a3 | 0x20000); // 0x10bca
    int32_t i_v2 = i_a1;                             // 0x10bcc
    if (*p_v1 == 0) {
        // 0x10bce
        i_v2 = function_10b70(i_a1, i_a2, i_a3, 0);
        *p_v1 = 1;
    }
    // 0x10bd6
    return i_v2;
}

// Address range: 0x10bd8 - 0x10bda
int32_t function_10bd8(void) {
    // 0x10bd8
    int32_t i_v1; // 0x10bd8
    return i_v1;
}

// Address range: 0x10bdc - 0x10c28
int32_t function_10bdc(char *p_a1) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = strlen(p_a1); // 0x10be4
    int32_t i_v3 = i_v1 - 1;
    int32_t i_v4 = i_v1 - 2 + i_v2; // 0x10bfc
    int32_t i_v5 = -48;             // 0x10c18
    if (i_v3 == i_v4) {
        // 0x10c1c
        return (int32_t) * (char *)(i_v2 + i_v3) - 48;
    }
    int32_t i_v6 = i_v3; // 0x10c18
    i_v6++;
    i_v5 = 10 * (i_v5 + (int32_t) * (char *)i_v6) - 48;
    while (i_v6 != i_v4) {
        // 0x10c04
        i_v6++;
        i_v5 = 10 * (i_v5 + (int32_t) * (char *)i_v6) - 48;
    }
    // 0x10c1c
    return i_v5 + (int32_t) * (char *)(i_v2 + i_v3);
}

// Address range: 0x10c28 - 0x10dbc
int32_t function_10c28(int32_t i_a1) {
    // 0x10c28
    puts("New Thread!\r");
    int32_t i_v1 = 0;                               // bp-2064, 0x10c50
    int32_t i_v2;                                   // bp-2060, 0x10c28
    int32_t i_v3 = (int32_t)memset(&i_v2, 0, 1020); // 0x10c54
    read(i_v3, &i_v1, 1024);
    printf("Recv:'%s'\r\n", &i_v1);
    char *p_v4 = (char *)0x7273752f; // bp-1040, 0x10c8c
    char i_v5 = 0;                   // bp-1016, 0x10c9c
    int32_t i_v6;                    // bp-1015, 0x10c28
    memset(&i_v6, 0, 999);
    strcpy(&i_v5, (char *)&i_v1);
    int32_t i_v7 = 0x656d6f43;             // bp-2080, 0x10cd0
    uint32_t i_v8 = system((char *)&p_v4); // 0x10cdc
    int32_t i_v9;                          // 0x10c28
    int32_t i_v10;                         // 0x10c28
    if (i_v8 == -1) {
        // 0x10d78
        puts("system err!\r");
        i_v7 = 0x303035;
        goto lab_0x10d28;
    } else {
        // 0x10ce8
        printf("system status:[%d]\r\n", i_v8);
        int32_t i_v11 = __asm_ubfx(i_v8, 8, 8); // 0x10d00
        if (i_v8 % 128 == 0) {
            if (i_v11 == 0) {
                // 0x10d10
                puts("Shell Exec Successfully!\r");
                i_v7 = 0x303032;
                i_v9 = 0;
            } else {
                // 0x10d94
                printf("Shell Execute Failed, Ret[%d]\r\n", i_v11);
                sprintf((char *)&i_v7, "%d", i_v11);
                i_v9 = i_v11;
            }
            goto lab_0x10d28;
        } else {
            // 0x10ce8
            i_v10 = i_v11;
            goto lab_0x10d50;
        }
    }
lab_0x10d28:
    // 0x10d28
    write(i_v3, &i_v7, strlen((char *)&i_v7) + 1);
    close(i_v3);
    pthread_exit(NULL);
    i_v10 = i_v9;
    goto lab_0x10d50;
lab_0x10d50:
    // 0x10d50
    printf("Other Exit Ret[%d]\r\n", i_v10);
    sprintf((char *)&i_v7, "6%d", i_v10);
    i_v9 = i_v10;
    goto lab_0x10d28;
}

// Address range: 0x10dbc - 0x10ed8
int32_t function_10dbc(int32_t i_a1) {
    // 0x10dbc
    if (i_a1 == 0) {
        // 0x10ea0
        return -3;
    }
    float64_t f_v1 = __asm_vmov_i32(0); // 0x10dcc
    int32_t i_v2;                       // 0x10dbc
    __asm_vst1_8(f_v1, i_v2);
    int32_t i_v3 = 2; // bp-1056, 0x10de8
    __asm_vst1_8(f_v1, i_v2);
    inet_addr("127.0.0.1");
    function_10bdc("22322");
    int32_t i_v4 = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10e14
    if (i_v4 < 0) {
        // 0x10eb0
        perror("socket err:");
        // 0x10ea0
        return -1;
    }
    // 0x10e20
    if (connect(i_v4, (struct sockaddr *)&i_v3, 16) < 0) {
        // 0x10ec4
        perror("connect err:");
        // 0x10ea0
        return -2;
    }
    // 0x10e34
    send(i_v4, (int32_t *)i_a1, strlen((char *)i_a1) + 1, 0);
    int32_t i_v5 = 0; // bp-1040, 0x10e60
    int32_t i_v6;     // bp-1036, 0x10dbc
    memset(&i_v6, 0, 1020);
    int32_t i_v7 = recv(i_v4, &i_v5, 1024, 0); // 0x10e78
    if (i_v7 < 1) {
        // 0x10ea0
        return -3;
    }
    // 0x10e84
    int32_t i_v8; // bp-16, 0x10dbc
    *(char *)((int32_t)&i_v8 - 1024 + i_v7) = 0;
    int32_t i_v9 = function_10bdc((char *)&i_v5); // 0x10e94
    return i_v9 == 200 ? 0 : i_v9;
}

// Address range: 0x10ed8 - 0x10f0c
int32_t function_10ed8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_1074c(i_a1, i_a2, i_a3, i_a4); // 0x10ee8
    int32_t i_v2 =
        (int32_t)&i_g2 + 0x10ee8 - (int32_t)&i_g4 >> 2 == 0 ? i_v1 : i_a1;
    return i_v2;
}

// Address range: 0x10f14 - 0x10f16
int32_t function_10f14(void) {
    // 0x10f14
    int32_t i_v1; // 0x10f14
    return i_v1;
}

// Address range: 0x10f18 - 0x10f20
int32_t function_10f18(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10f18
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 43
