//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <ctype.h>
#include <errno.h>
#include <netdb.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct hostent {
    char *e0;
    char **e1;
    int32_t e2;
    int32_t e3;
    char **e4;
};

struct sockaddr {
    int32_t e0;
    char e1[14];
};

// ------------------- Function Prototypes --------------------

int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _fini(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t _start(int32_t i_a1, int32_t i_a2);
int32_t callapi(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t display(int32_t i_a1);
int32_t function_108fc(char *s1, char *s2);
int32_t function_10908(char *nptr, char **endptr, int32_t base);
int32_t function_10914(int32_t fd, int32_t level, int32_t optname,
                       int32_t *optval, int32_t optlen);
int32_t function_10920(char *format, ...);
void function_1092c(int32_t *ptr);
int32_t *function_10938(int32_t *ptr, int32_t size);
int32_t *function_10944(int32_t *s, int32_t c);
int32_t function_10950(char *s);
int32_t *function_1095c(int32_t size);
int32_t function_10968(int32_t main2, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
char *function_10974(int32_t errnum);
void function_10980(void);
int16_t **function_1098c(void);
int32_t function_10998(char *s);
char *function_109a4(char *s, int32_t c);
int32_t function_109b0(struct _IO_FILE *stream, char *format, ...);
int32_t *function_109bc(void);
int32_t function_109c8(int32_t domain, int32_t type, int32_t protocol);
struct hostent *function_109d4(char *name);
void function_109e0(void);
int32_t function_109ec(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_109f8(int32_t fd);
int32_t function_10a04(int32_t fd, int32_t *buf, int32_t n, int32_t flags);
int32_t function_10a10(int32_t fd, struct sockaddr *addr, int32_t len);
int32_t function_10bd4(int32_t i_a1);
int32_t function_10be0(void);
int32_t function_10c04(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10c60(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_10c6c(void);
int32_t function_10c70(int32_t i_a1);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = -0x1cae0000;   // 0x10bf0
char *p_g2;                   // 0x112ac
int32_t i_g3 = 0;             // 0x11410
int32_t i_g4 = 0x10c6d;       // 0x21f10
struct _IO_FILE *p_g5 = NULL; // 0x22078
int32_t i_g6 = 0;             // 0x22080
int32_t i_g7;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());
int32_t *__rawmemchr(int32_t *p_a1, int32_t i_a2);

// ------------------------ Functions -------------------------

// Address range: 0x108dc - 0x108e8
int32_t _init(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x108dc
    return function_10be0();
}

// Address range: 0x108fc - 0x10908
int32_t function_108fc(char *s1, char *s2) {
    // 0x108fc
    return strcmp(s1, s2);
}

// Address range: 0x10908 - 0x10914
int32_t function_10908(char *nptr, char **endptr, int32_t base) {
    // 0x10908
    return strtol(nptr, endptr, base);
}

// Address range: 0x10914 - 0x10920
int32_t function_10914(int32_t fd, int32_t level, int32_t optname,
                       int32_t *optval, int32_t optlen) {
    // 0x10914
    return setsockopt(fd, level, optname, optval, optlen);
}

// Address range: 0x10920 - 0x1092c
int32_t function_10920(char *format, ...) {
    // 0x10920
    return printf(format);
}

// Address range: 0x1092c - 0x10938
void function_1092c(int32_t *ptr) {
    // 0x1092c
    free(ptr);
}

// Address range: 0x10938 - 0x10944
int32_t *function_10938(int32_t *ptr, int32_t size) {
    // 0x10938
    return realloc(ptr, size);
}

// Address range: 0x10944 - 0x10950
int32_t *function_10944(int32_t *s, int32_t c) {
    // 0x10944
    return __rawmemchr(s, c);
}

// Address range: 0x10950 - 0x1095c
int32_t function_10950(char *s) {
    // 0x10950
    return puts(s);
}

// Address range: 0x1095c - 0x10968
int32_t *function_1095c(int32_t size) {
    // 0x1095c
    return malloc(size);
}

// Address range: 0x10968 - 0x10974
int32_t function_10968(int32_t main2, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10968
    return __libc_start_main(main2, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10974 - 0x10980
char *function_10974(int32_t errnum) {
    // 0x10974
    return strerror(errnum);
}

// Address range: 0x10980 - 0x1098c
void function_10980(void) {
    // 0x10980
    __gmon_start__();
}

// Address range: 0x1098c - 0x10998
int16_t **function_1098c(void) {
    // 0x1098c
    return __ctype_b_loc();
}

// Address range: 0x10998 - 0x109a4
int32_t function_10998(char *s) {
    // 0x10998
    return strlen(s);
}

// Address range: 0x109a4 - 0x109b0
char *function_109a4(char *s, int32_t c) {
    // 0x109a4
    return strchr(s, c);
}

// Address range: 0x109b0 - 0x109bc
int32_t function_109b0(struct _IO_FILE *stream, char *format, ...) {
    // 0x109b0
    return fprintf(stream, format);
}

// Address range: 0x109bc - 0x109c8
int32_t *function_109bc(void) {
    // 0x109bc
    return __errno_location();
}

// Address range: 0x109c8 - 0x109d4
int32_t function_109c8(int32_t domain, int32_t type, int32_t protocol) {
    // 0x109c8
    return socket(domain, type, protocol);
}

// Address range: 0x109d4 - 0x109e0
struct hostent *function_109d4(char *name) {
    // 0x109d4
    return gethostbyname(name);
}

// Address range: 0x109e0 - 0x109ec
void function_109e0(void) {
    // 0x109e0
    abort();
}

// Address range: 0x109ec - 0x109f8
int32_t function_109ec(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x109ec
    return recv(fd, buf, n, flags);
}

// Address range: 0x109f8 - 0x10a04
int32_t function_109f8(int32_t fd) {
    // 0x109f8
    return close(fd);
}

// Address range: 0x10a04 - 0x10a10
int32_t function_10a04(int32_t fd, int32_t *buf, int32_t n, int32_t flags) {
    // 0x10a04
    return send(fd, buf, n, flags);
}

// Address range: 0x10a10 - 0x10a1c
int32_t function_10a10(int32_t fd, struct sockaddr *addr, int32_t len) {
    // 0x10a10
    return connect(fd, addr, len);
}

// Address range: 0x10a1c - 0x10bb0
int main(int argc, char **argv) {
    // 0x10a1c
    if (argc < 2) {
        // 0x10b44
        return callapi((int32_t) "summary", (int32_t) "127.0.0.1", 4028);
    }
    int32_t i_v1 = (int32_t)argv;
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x10a28
    char *p_v3 = (char *)i_v2;             // 0x10a34
    char i_v4;                             // 0x10ad0
    if (*p_v3 == 45) {
        // 0x10ad0
        i_v4 = *(char *)(i_v2 + 1);
        switch (i_v4) {
        case 63: {
            // 0x10adc
            if (*(char *)(i_v2 + 2) == 0) {
                // 0x10b68
                fprintf(p_g5, "usAge: %s [command [ip/host [port]]]\n",
                        (char *)i_v1);
                return 1;
            }
            goto lab_0x10ae8;
        }
        case 104: {
            // 0x10b5c
            if (*(char *)(i_v2 + 2) == 0) {
                // 0x10b68
            }
            goto lab_0x10a40;
        }
        default: {
            goto lab_0x10ae8;
        }
        }
    } else {
        goto lab_0x10a40;
    }
lab_0x10a40:;
    int32_t i_v5 = 1; // 0x10a54
    if (strcmp(p_v3, "--help") == 0) {
        // 0x10b68
        fprintf(p_g5, "usAge: %s [command [ip/host [port]]]\n",
                (char *)(int32_t) "--help");
        return 1;
    }
    goto lab_0x10a5c;
lab_0x10ae8:
    // 0x10ae8
    if (strcmp(p_v3, "--help") == 0) {
        // 0x10b68
        fprintf(p_g5, "usAge: %s [command [ip/host [port]]]\n",
                (char *)(int32_t) "--help");
        return 1;
    }
    // 0x10b00
    i_v5 = 1;
    if (i_v4 == 111) {
        // 0x10b08
        i_v5 = 1;
        if (*(char *)(i_v2 + 2) == 0) {
            // 0x10b14
            i_g6 = 1;
            i_v5 = 2;
            if (argc == 2) {
                // 0x10b44
                return callapi((int32_t) "summary", (int32_t) "127.0.0.1",
                               4028);
            }
        }
    }
    goto lab_0x10a5c;
lab_0x10a5c:;
    int32_t i_v6 = 4 * i_v5 + i_v1;                  // 0x10a5c
    int32_t i_v7 = function_10c70(*(int32_t *)i_v6); // 0x10a64
    int32_t i_v8 = *(char *)i_v7 == 0 ? (int32_t) "summary" : i_v7;
    if (i_v5 + 1 >= argc) {
        // 0x10b44
        return callapi(i_v8, (int32_t) "127.0.0.1", 4028);
    }
    int32_t i_v9 = function_10c70(*(int32_t *)(i_v6 + 4)); // 0x10a9c
    int32_t i_v10 = *(char *)i_v9 == 0 ? (int32_t) "127.0.0.1" : i_v9;
    if (i_v5 + 2 >= argc) {
        // 0x10b44
        return callapi(i_v8, i_v10, 4028);
    }
    char *p_v11 = (char *)function_10c70(*(int32_t *)(i_v6 + 8)); // 0x10abc
    int32_t i_v12 = 4028;                                         // 0x10ac4
    if (*p_v11 != 0) {
        // 0x10b8c
        i_v12 = __asm_sxth(strtol(p_v11, NULL, 10));
    }
    // 0x10b44
    return callapi(i_v8, i_v10, i_v12);
}

// Address range: 0x10bb0 - 0x10bd4
int32_t _start(int32_t i_a1, int32_t i_a2) {
    // 0x10bb0
    int32_t i_v1; // 0x10bb0
    __libc_start_main(0x10a1c, i_a2, (char **)&i_v1, (void (*)())0x11209,
                      (void (*)())0x10a1c, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x10bd4 - 0x10bd8
int32_t function_10bd4(int32_t i_a1) {
    // 0x10bd4
    return i_a1;
}

// Address range: 0x10be0 - 0x10bfc
int32_t function_10be0(void) {
    int32_t i_v1 =
        *(int32_t *)((int32_t)&i_g1 + (int32_t)&i_g3 + 108); // 0x10bec
    if (i_v1 == 0) {
        int32_t i_v2; // 0x10be0
        return i_v2;
    }
    // 0x10bf8
    __gmon_start__();
    return &i_g7;
}

// Address range: 0x10c04 - 0x10c60
int32_t function_10c04(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10c04
    bool i_v1; // 0x10c04
    if (i_v1) {
        return i_a1;
    }
    // 0x10c34
    int32_t i_v2;                   // 0x10c04
    int32_t i_v3 = 0x100001 * i_v2; // 0x10c38
    bool i_v4;                      // 0x10c04
    int32_t i_v5;                   // 0x10c04
    if (i_v1) {
        // .thread
        i_v5 = i_v1 ? i_v3 : 0;
    } else {
        int32_t i_v6 = i_v3 & -1 - 0x400000 * i_v2; // 0x10c3c
        i_v5 = i_v6 < 1 ? 0 : i_v3;
        i_v4 = i_v6 < 0;
        if (i_v6 == 0) {
            return unknown_240();
        }
    }
    // 0x10c4c
    if (i_v4 != i_v1) {
        __asm_svclt(0x4770);
    }
    float64_t f_v7; // 0x10c04
    __asm_vqrshl_s8(f_v7, f_v7);
    __asm_vmvn_i32(0xc0000);
    if (!i_v1) {
        *(int32_t *)i_a4 = i_v5;
    }
    return i_a1;
}

// Address range: 0x10c60 - 0x10c6c
int32_t function_10c60(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    int32_t i_v1 = i_a1; // 0x10c60
    if (i_a4 == 0) {
        // 0x10c62
        i_v1 = function_10c04(i_a1, i_a2, i_a3, 0);
        int32_t i_v2; // 0x10c60
        *(char *)i_v2 = 1;
    }
    // 0x10c6a
    return i_v1;
}

// Address range: 0x10c6c - 0x10c6e
int32_t function_10c6c(void) {
    // 0x10c6c
    int32_t i_v1; // 0x10c6c
    return i_v1;
}

// Address range: 0x10c70 - 0x10ce0
int32_t function_10c70(int32_t i_a1) {
    int16_t **p_v1 = __ctype_b_loc(); // 0x10c78
    int32_t i_v2 = (int32_t)*p_v1;    // 0x10c80
    uint32_t i_v3 = i_a1;             // 0x10c84
    while ((*(int16_t *)(2 * (int32_t) * (char *)i_v3 + i_v2) & 0x2000) != 0) {
        // 0x10c88
        i_v3++;
    }
    int32_t i_v4 = (int32_t)__rawmemchr((int32_t *)i_v3, 0); // 0x10cac
    if (i_v3 >= i_v4) {
        // 0x10cd8
        return i_v3;
    }
    int32_t i_v5 = i_v4; // 0x10cb8
    i_v5--;
    char *p_v6 = (char *)i_v5; // 0x10cb8
    if ((*(int16_t *)(2 * (int32_t)*p_v6 + (int32_t)*p_v1) & 0x2000) != 0) {
        *p_v6 = 0;
    }
    while (i_v3 < i_v5) {
        // 0x10cb8
        i_v5--;
        p_v6 = (char *)i_v5;
        if ((*(int16_t *)(2 * (int32_t)*p_v6 + (int32_t)*p_v1) & 0x2000) != 0) {
            *p_v6 = 0;
        }
    }
    // 0x10cd8
    return i_v3;
}

// Address range: 0x10ce0 - 0x10e6c
int32_t display(int32_t i_a1) {
    // 0x10ce0
    if (i_a1 == 0) {
        // 0x10d44
        return 0;
    }
    int32_t i_v1 = i_a1; // 0x10cec
    int32_t i_v2;        // 0x10ce0
    int32_t i_v3;        // 0x10ce0
    int32_t i_v4;        // 0x10ce0
    int32_t i_v5;        // 0x10ce0
    int32_t i_v6;        // 0x10ce0
    while (true) {
    lab_0x10d0c:
        // 0x10d0c
        i_v4 = i_v1;
        char *p_v7 = (char *)i_v4;      // 0x10d14
        char *p_v8 = strchr(p_v7, 124); // 0x10d14
        int32_t i_v9 = (int32_t)p_v8;   // 0x10d14
        if (p_v8 == NULL) {
            // 0x10d4c
            i_v3 = i_v9;
            i_v6 = i_v9;
            if (*p_v7 == 0) {
                // break -> 0x10d44
                break;
            }
            goto lab_0x10d58;
        } else {
            // 0x10d20
            *p_v8 = 0;
            int32_t i_v10 = i_v9 + 1; // 0x10d2c
            i_v2 = i_v9;
            i_v5 = i_v10;
            i_v6 = i_v10;
            if (*p_v7 == 0) {
                goto lab_0x10d3c;
            } else {
                goto lab_0x10d58;
            }
        }
    }
lab_0x10d44:
    // 0x10d44
    return i_v3;
lab_0x10d7c:;
    // 0x10d7c
    int32_t i_v11; // 0x10ce0
    int32_t i_v12 = i_v11;
    char *p_v13;                     // 0x10ce0
    char *p_v14 = strchr(p_v13, 61); // 0x10d84
    char *p_v15;                     // 0x10ce0
    int32_t i_v16;                   // 0x10ce0
    int32_t i_v17;                   // 0x10ce0
    if (p_v14 == NULL) {
        if (i_v17 == 0) {
            // 0x10e58
            printf("[%s%s] =>\n(\n", p_v13, (char *)&p_g2);
            // 0x10e38
            printf("   [%d] => %s\n", i_v17, p_v13);
            i_v16 = i_v12;
            goto lab_0x10df0;
        } else {
            // 0x10e38
            printf("   [%d] => %s\n", i_v17, p_v13);
            i_v16 = i_v12;
            goto lab_0x10df0;
        }
    } else {
        int32_t i_v18 = (int32_t)p_v14 + 1; // 0x10d98
        *p_v14 = 0;
        if (i_v17 == 0) {
            if (i_v18 == 0) {
                // 0x10e58
                printf("[%s%s] =>\n(\n", p_v13, (char *)&p_g2);
                // 0x10e38
                printf("   [%d] => %s\n", i_v17, p_v13);
                i_v16 = i_v12;
                goto lab_0x10df0;
            } else {
                int16_t **p_v19 = __ctype_b_loc(); // 0x10dac
                char *p_v20 = (char *)i_v18;
                int16_t i_v21 = *(int16_t *)(2 * (int32_t)*p_v20 +
                                             (int32_t)*p_v19); // 0x10dc4
                printf("[%s%s] =>\n(\n", p_v13,
                       (i_v21 & 2048) == 0 ? (char *)&p_g2 : p_v20);
                p_v15 = p_v20;
                goto lab_0x10dd8;
            }
        } else {
            if (i_v18 == 0) {
                // 0x10e38
                printf("   [%d] => %s\n", i_v17, p_v13);
                i_v16 = i_v12;
                goto lab_0x10df0;
            } else {
                // 0x10e30
                p_v15 = (char *)i_v18;
                goto lab_0x10dd8;
            }
        }
    }
lab_0x10df0:;
    int32_t i_v22 = i_v16;     // 0x10df8
    int32_t i_v23 = i_v17 + 1; // 0x10df8
    if (i_v16 == 0) {
        // break -> 0x10e1c
        goto lab_0x10e1c;
    }
    goto lab_0x10dfc;
lab_0x10dd8:
    // 0x10dd8
    printf("   [%s] => %s\n", p_v13, p_v15);
    i_v16 = i_v12;
    goto lab_0x10df0;
lab_0x10d58:
    // 0x10d58
    i_v22 = i_v4;
    i_v23 = 0;
    while (true) {
    lab_0x10dfc:
        // 0x10dfc
        i_v17 = i_v23;
        p_v13 = (char *)i_v22;
        char *p_v24 = strchr(p_v13, 44); // 0x10e04
        int32_t i_v25 = (int32_t)p_v24;  // 0x10e04
        if (p_v24 == NULL) {
            // 0x10e10
            i_v11 = i_v25;
            if (*p_v13 == 0) {
                // break -> 0x10e1c
                break;
            }
            goto lab_0x10d7c;
        } else {
            // 0x10d60
            *p_v24 = 0;
            int32_t i_v26 = i_v25 + 1; // 0x10d6c
            i_v11 = i_v26;
            i_v16 = i_v26;
            if (*p_v13 == 0) {
                goto lab_0x10df0;
            } else {
                goto lab_0x10d7c;
            }
        }
    }
lab_0x10e1c:
    // 0x10e1c
    i_v2 = puts(")");
    i_v5 = i_v6;
    goto lab_0x10d3c;
lab_0x10d3c:
    // 0x10d3c
    i_v1 = i_v5;
    i_v3 = i_v2;
    if (i_v1 == 0) {
        // break -> 0x10d44
        goto lab_0x10d44;
    }
    goto lab_0x10d0c;
}

// Address range: 0x10e6c - 0x11208
int32_t callapi(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    char *p_v1 = (char *)i_a2; // 0x10e84
    if (gethostbyname(p_v1) == NULL) {
        // 0x10fc8
        printf("Couldn't get hostname: '%s'\n", p_v1);
        return 1;
    }
    int32_t i_v2 = socket(AF_INET, SOCK_STREAM, IPPROTO_IP); // 0x10e9c
    if (i_v2 == -1) {
        // 0x10fe8
        printf("Socket initialisation failed: %s\n",
               strerror(*__errno_location()));
        return 1;
    }
    float64_t f_v3 = __asm_vmov_i32(0); // 0x10eac
    __asm_rev16(i_a3);
    int32_t i_v4; // 0x10e6c
    __asm_vst1_8(f_v3, i_v4);
    int32_t i_v5 = 2; // bp-56, 0x10ecc
    __asm_vst1_8(f_v3, i_v4);
    if (connect(i_v2, (struct sockaddr *)&i_v5, 16) < 0) {
        // 0x11014
        printf("Socket connect failed: %s\n", strerror(*__errno_location()));
        return 1;
    }
    int32_t i_v6 = 1; // bp-72, 0x10f14
    if (setsockopt(i_v2, SO_DEBUG, 13, &i_v6, 8) != 0) {
        // 0x11090
        printf("cgminer-api, setsocket SO_LINGER failed (%s)\n",
               strerror(*__errno_location()));
        close(i_v2);
    }
    int32_t i_v7 = 10; // bp-64, 0x10f4c
    if (setsockopt(i_v2, SO_DEBUG, 21, &i_v7, 8) != 0) {
        // 0x11068
        printf("cgminer-api, setsocket SO_SNDTIMEO failed (%s)\n",
               strerror(*__errno_location()));
        close(i_v2);
    }
    int32_t i_v8 = setsockopt(i_v2, SO_DEBUG, 20, &i_v7, 8); // 0x10f74
    if (i_v8 != 0) {
        // 0x11040
        printf("cgminer-api, setsocket SO_RCVTIMEO failed (%s)\n",
               strerror(*__errno_location()));
        close(i_v2);
    }
    char *p_v9 = (char *)i_a1;                                    // 0x10f84
    int32_t i_v10 = send(i_v2, (int32_t *)i_a1, strlen(p_v9), 0); // 0x10f98
    if (i_v10 < 1) {
        // 0x110b8
        printf("cgminer api send failed: %s\n", strerror(*__errno_location()));
        // 0x10fb4
        close(i_v2);
        // 0x10fbc
        return 1;
    }
    // 0x10fa4
    if (strlen(p_v9) != i_v10) {
        // 0x10fb4
        close(i_v2);
        // 0x10fbc
        return i_v8;
    }
    int32_t *p_v11 = malloc(0x10000); // 0x110e0
    int32_t i_v12 = 0xffff;           // 0x110f4
    int32_t i_v13 = 3;                // 0x110f4
    if (p_v11 == NULL) {
        // 0x11174
        printf("cgminer api: OOM (%d)\n", 0x10000);
    lab_0x10fbc:
        // 0x10fbc
        return 1;
    }
    int32_t *p_v14 = p_v11;
    int32_t i_v15 = 0;
    int32_t i_v16 = (int32_t)p_v14;
    int32_t i_v17 = i_v15 + i_v16;                           // 0x110f8
    int32_t i_v18 = recv(i_v2, (int32_t *)i_v17, 0xffff, 0); // 0x11110
    int32_t i_v19;                                           // 0x10e6c
    int32_t i_v20;                                           // 0x10e6c
    while (i_v18 >= 0) {
        if (i_v18 == 0) {
            // 0x111ec
            puts("Recv failed: api server close the socket");
            i_v19 = 1;
            i_v20 = i_v17;
            goto lab_0x11190;
        }
        int32_t i_v21 = i_v12;
        int32_t i_v22 = i_v18 + i_v15; // 0x11128
        if (i_v21 != i_v22) {
            // 0x11200
            i_v19 = i_v8;
            i_v20 = i_v22 + i_v16;
            goto lab_0x11190;
        }
        // 0x1113c
        if (i_v13 == 1) {
            // 0x1118c
            i_v19 = i_v8;
            i_v20 = i_v21 + i_v16;
            goto lab_0x11190;
        }
        int32_t i_v23 = i_v21 + 0x10000;        // 0x1110c
        int32_t *p_v24 = realloc(p_v14, i_v23); // 0x11148
        i_v12 = i_v21 + 0xffff;
        i_v13--;
        if (p_v24 == NULL) {
            // 0x1115c
            printf("cgminer realloc: OOM (%d)\n", i_v23);
            return 1;
        }
        p_v14 = p_v24;
        i_v15 = i_v21;
        i_v16 = (int32_t)p_v14;
        i_v17 = i_v15 + i_v16;
        i_v18 = recv(i_v2, (int32_t *)i_v17, 0xffff, 0);
    }
    // 0x111c8
    printf("Recv failed: %s\n", strerror(*__errno_location()));
    i_v19 = 1;
    i_v20 = i_v17;
    goto lab_0x11190;
lab_0x11190:
    // 0x11190
    *(char *)i_v20 = 0;
    if (i_g6 == 0) {
        // 0x111c0
        display(i_v16);
    } else {
        // 0x111b0
        puts((char *)p_v14);
    }
    // 0x111b4
    free(p_v14);
    // 0x10fb4
    close(i_v2);
    // 0x10fbc
    return i_v19;
}

// Address range: 0x11208 - 0x1123c
int32_t __libc_csu_init(int32_t i_a1, int32_t i_a2, int32_t i_a3,
                        int32_t i_a4) {
    int32_t i_v1 = _init(i_a1, i_a2, i_a3, i_a4); // 0x11218
    return 0x21f12 - (int32_t)&i_g4 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x11244 - 0x11246
int32_t __libc_csu_fini(void) {
    // 0x11244
    int32_t i_v1; // 0x11244
    return i_v1;
}

// Address range: 0x11248 - 0x11250
int32_t _fini(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x11248
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 38
