//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t $x(void);
int64_t $x10(void);
int64_t $x11(void);
int64_t $x12(void);
int64_t $x13(void);
int64_t $x14(void);
int64_t $x15(void);
int64_t $x16(void);
int64_t $x17(void);
int64_t $x2(void);
int64_t $x3(void);
int64_t $x4(void);
int64_t $x5(void);
int64_t $x6(void);
int64_t $x7(void);
int64_t $x8(int64_t i_a1);
int64_t $x9(void);
int64_t _24_x(int64_t i_a1);
int64_t __arch_copy_to_user(int64_t i_a1, int64_t i_a2, int64_t i_a3,
                            int64_t i_a4, int64_t i_a5);
int64_t __const_udelay(int64_t i_a1, int64_t i_a2, int64_t *p_a3);
int64_t __dynamic_pr_debug(int64_t i_a1);
int64_t __iounmap(int64_t i_a1);
int64_t __platform_driver_register(int64_t i_a1, int64_t i_a2);
int64_t __raw_spin_lock_init(int64_t i_a1);
int64_t _mcount(int64_t *p_a1, int64_t i_a2, int64_t i_a3);
int64_t _reg_write_mask(void);
int64_t cleanup_module(int64_t i_a1);
int64_t cvi_base_read_chip_id(void);
int64_t cvi_base_read_chip_version(void);
int64_t function_1028(int64_t i_a1, int64_t i_a2, int64_t i_a3, int64_t i_a4,
                      int64_t i_a5, int64_t i_a6);
int64_t function_2418(void);
int64_t function_2c0(int64_t i_a1);
int64_t function_3f50(void);
int64_t function_4070(void);
int64_t function_48(void);
int64_t init_module(void);
int64_t kfree(int64_t i_a1);
int64_t kstrtoull(int64_t i_a1, int64_t i_a2, int32_t i_a3, int64_t i_a4);
int64_t log_proc_init(void);
int64_t log_proc_remove(void);
int64_t memset(int64_t i_a1, int64_t i_a2, int64_t *p_a3, int32_t *p_a4);
int64_t memstart_addr(int64_t i_a1, int64_t *p_a2, int64_t *p_a3);
int64_t misc_register(int64_t i_a1, int64_t i_a2);
int64_t printk(int64_t i_a1, int64_t *p_a2, int64_t i_a3);
int64_t proc_create_data(int64_t i_a1, int64_t *p_a2, int64_t i_a3,
                         int64_t i_a4);
int64_t proc_remove(int64_t i_a1, int64_t i_a2);
int64_t remove_proc_entry(int64_t i_a1);
int64_t scnprintf(int64_t i_a1, int64_t i_a2, int32_t i_a3);
int64_t seq_puts(int64_t i_a1);
int64_t seq_read(int64_t i_a1, int64_t i_a2, int64_t i_a3);
int64_t single_release(int64_t i_a1, int64_t i_a2, int64_t i_a3, int64_t i_a4);
int64_t snprintf(int64_t i_a1, int32_t i_a2);
int64_t sscanf(int64_t i_a1, int64_t *p_a2, int64_t i_a3);
int64_t strlen(int64_t i_a1, int64_t i_a2);
int64_t strncmp(int64_t i_a1, int32_t i_a2, int64_t *p_a3);
int64_t sys_proc_init(void);
int64_t sys_proc_remove(void);
int64_t tee_cv_efuse_read(int64_t i_a1);
int64_t unknown_43d0(int64_t i_a1, int64_t i_a2, int64_t i_a3);
int64_t unknown_43d8(int64_t i_a1);
int64_t unknown_6200(int64_t i_a1);
int64_t unknown_6238(int64_t i_a1, int64_t i_a2, int64_t i_a3);
int64_t unknown_62a0(int64_t i_a1, int64_t i_a2, int64_t i_a3);
int64_t unknown_62c8(int64_t i_a1, int64_t i_a2, int64_t i_a3);
int64_t unknown_62f0(int64_t i_a1, int64_t i_a2);
int64_t unknown_6328(int64_t i_a1);
int64_t unknown_6330(int64_t i_a1, int64_t i_a2, int64_t i_a3);
int64_t unknown_6368(int64_t i_a1);
int64_t unknown_6378(int64_t i_a1);
int64_t vb_proc_init(void);
int64_t vb_proc_remove(void);
int64_t vip_get_clk_lp(int64_t i_a1);
int64_t vip_get_intr_mask(int64_t i_a1);
int64_t vip_get_intr_status(int64_t i_a1);
int64_t vip_get_isp_clk(int64_t i_a1);
int64_t vip_get_reset(int64_t i_a1);
int64_t vip_isp_clk_reset(void);
int64_t vip_set_base_addr(void);
int64_t vip_set_clk_lp(void);
int64_t vip_set_intr_mask(void);
int64_t vip_set_isp_clk(void);
int64_t vip_set_reset(void);
int64_t vip_sys_cif_cb(void);
int64_t vip_sys_cmm_cb_i2c(void);
int64_t vip_sys_cmm_cb_ssp(int64_t i_a1, int64_t i_a2, int64_t i_a3,
                           int64_t i_a4);
int64_t vip_sys_reg_read(void);
int64_t vip_sys_reg_write_mask(void);
int64_t vip_sys_register_cif_cb(void);
int64_t vip_sys_register_cmm_cb(void);
int64_t vip_sys_set_offline(void);
int64_t vip_toggle_reset(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x14000000;                    // 0x1
int64_t i_g2 = 0x541aff66a0923777;            // 0x10
int64_t i_g3 = -0x6efffc0256428403;           // 0x1000
int64_t i_g4 = -0x6efffc0256418403;           // 0x110
int64_t i_g5 = 0x17fffffb12800000;            // 0x160
int64_t i_g6 = 0x44fccbdeac0b9959;            // 0x18
int64_t i_g7;                                 // 0x1f
int32_t i_g8 = 0x140000;                      // 0x2
int64_t i_g9;                                 // 0x20
int32_t *p_g10 = (int32_t *)0x300000014;      // 0x4
int64_t i_g11 = 0;                            // 0x707
int32_t *p_g12 = (int32_t *)0x554e4700000003; // 0x8
int32_t i_g13 = -0x7fffffe9;                  // 0xff
int32_t i_g14;

// ------------------------ Functions -------------------------

// Address range: 0x28 - 0x44
int64_t _24_x(int64_t i_a1) {
    // 0x28
    int64_t i_v1; // 0x28
    unknown_43d8(i_v1);
    return 0;
}

// Address range: 0x48 - 0xa0
int64_t function_48(void) {
    // 0x48
    int64_t i_v1; // 0x48
    int64_t i_v2 = i_v1;
    unknown_43d8(i_v1);
    return *(int64_t *)(*(int64_t *)(i_v2 + 40) + 72) == 0 ? -515 : i_v2;
}

// Address range: 0xa0 - 0x108
int64_t vip_sys_register_cmm_cb(void) {
    // 0xa0
    int64_t i_v1; // 0xa0
    uint64_t i_v2 = i_v1;
    unknown_43d8(i_v1);
    bool i_v3 = true;  // 0xcc
    bool i_v4 = &i_g1; // 0xcc
    if (!((i_v1 == 0 ? (bool)&i_g1 : i_v1 == 0))) {
        i_v3 = i_v2 != (int64_t)&i_g1;
        i_v4 = i_v2 >= (int64_t)&i_g1;
    }
    int64_t i_v5 = 0xffffffff; // 0xd0
    if (i_v4 != i_v3) {
        // 0xd4
        *(int32_t *)(i_v2 == 0 ? 0 : (int64_t)&i_g6) = (int32_t)i_v2;
        i_v5 = 0;
    }
    // 0xe8
    return i_v5;
}

// Address range: 0x110 - 0x168
int64_t vip_sys_cmm_cb_i2c(void) {
    // 0x110
    int64_t i_v1; // 0x110
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x170 - 0x1d8
int64_t vip_sys_cmm_cb_ssp(int64_t i_a1, int64_t i_a2, int64_t i_a3,
                           int64_t i_a4) {
    // 0x170
    int64_t i_v1; // 0x170
    unknown_43d8(i_v1);
    if (*(int32_t *)&i_g6 != (int32_t)&i_g1 ||
        *(int64_t *)((int64_t)&i_g6 + 16) == 0) {
        // 0x1c8
        return 0xffffffff;
    }
    // 0x1a8
    return *(int64_t *)((int64_t)&i_g6 + 8);
}

// Address range: 0x1e0 - 0x228
int64_t vip_sys_register_cif_cb(void) {
    // 0x1e0
    int64_t i_v1; // 0x1e0
    unknown_43d8(i_v1);
    int64_t i_v2 = 0xffffffff; // 0x204
    if (!((i_v1 == 0 ? (bool)&i_g1 : i_v1 == 0))) {
        // 0x208
        i_v2 = 0;
    }
    // 0x214
    return i_v2;
}

// Address range: 0x230 - 0x280
int64_t vip_sys_cif_cb(void) {
    // 0x230
    int64_t i_v1; // 0x230
    unknown_43d8(i_v1);
    if (*(int64_t *)56 == 0) {
        // 0x278
        return 0xffffffff;
    }
    // 0x258
    return *(int64_t *)48;
}

// Address range: 0x288 - 0x2c0
int64_t $x(void) {
    // 0x288
    int64_t i_v1; // 0x288
    unknown_43d8(i_v1);
    return 0x100000000 * sscanf(0, &i_g3, i_v1) >> 32;
}

// Address range: 0x2c0 - 0x354
int64_t function_2c0(int64_t i_a1) {
    int64_t i_v1 = i_a1;
    int64_t i_v2; // 0x2c0
    unknown_43d8(i_v2);
    int32_t i_v3 = -0x21504111;                    // bp-4, 0x2ec
    int64_t i_v4 = __const_udelay(i_v2, 0, &i_v1); // 0x2f4
    if ((int32_t)i_v4 < 0) {
        // 0x338
        kstrtoull(0, i_v4 & 0xffffffff, (int32_t)(int64_t)&i_v1, i_v2);
        return 0x100000000 * i_v4 >> 32;
    }
    int64_t i_v5 =
        sscanf(i_v1 & 0xffffffff, (int64_t *)&p_g10, (int64_t)&i_v3); // 0x30c
    kstrtoull(0, i_v1, i_v3, i_v5 & 0xffffffff);
    return i_v2;
}

// Address range: 0x368 - 0x3e0
int64_t $x2(void) {
    // 0x368
    int64_t i_v1; // 0x368
    unknown_43d8(i_v1);
    int32_t i_v2 = 0;                                        // 0x394
    int32_t i_v3 = 0;                                        // 0x398
    int64_t i_v4 = memset(i_v1, 0, (int64_t *)&i_v2, &i_v3); // 0x39c
    int64_t i_v5 = -12;                                      // 0x3a8
    if ((int32_t)i_v4 == (int32_t)&i_g8) {
        // 0x3bc
        kstrtoull(0, (int64_t)i_v2, i_v3, (int64_t)&i_v3);
        int64_t i_v6 = snprintf((int64_t)i_v2, i_v3); // 0x3cc
        i_v5 = (int32_t)i_v6 < 0 ? 0x100000000 * i_v6 >> 32 : i_v1;
    }
    // 0x3ac
    return i_v5;
}

// Address range: 0x3f0 - 0x42c
int64_t $x3(void) {
    // 0x3f0
    int64_t i_v1; // 0x3f0
    unknown_43d8(i_v1);
    return 0x100000000 * proc_create_data(i_v1, &i_g3, 0, 0) >> 32;
}

// Address range: 0x440 - 0x4b0
int64_t cvi_base_read_chip_id(void) {
    // 0x440
    int64_t i_v1; // 0x440
    unknown_43d8(i_v1);
    __asm_dsb(0);
    uint32_t i_v2 = *(int32_t *)(*(int64_t *)64 + 140) % 0x10000; // 0x46c
    if ((*(int16_t *)34 & 4) != 0) {
        // 0x4a0
        single_release(0, 0, (int64_t)i_v2, i_v1);
    }
    uint32_t i_v3 = i_v2 - 0x1822; // 0x47c
    int64_t i_v4 = &i_g8;          // 0x488
    if (i_v3 >= 22 != i_v3 != 22) {
        uint32_t i_v5 = *(int32_t *)(4 * (int64_t)(i_v2 + 0x3fffe7de) &
                                     0xfffffffc); // 0x490
        i_v4 = i_v5;
    }
    // 0x494
    return i_v4;
}

// Address range: 0x4d0 - 0x554
int64_t cvi_base_read_chip_version(void) {
    // 0x4d0
    int64_t i_v1; // 0x4d0
    unknown_43d8(i_v1);
    uint32_t i_v2 = *(int32_t *)*(int64_t *)64; // 0x4ec
    __asm_dsb(0);
    if ((*(int16_t *)74 & 4) == 0) {
        int64_t i_v3 = i_v2 == 0x18802001 ? (int64_t)(2 * (int32_t)&i_g1)
                                          : (int64_t)(int32_t)&i_g1; // 0x518
        return i_v3;
    }
    // 0x528
    single_release(40, 0, (int64_t)i_v2, i_v1);
    int64_t i_v4 = i_v2 == 0x18802001 ? (int64_t)(2 * (int32_t)&i_g1)
                                      : (int64_t)(int32_t)&i_g1; // 0x548
    return i_v4;
}

// Address range: 0x570 - 0x6e4
int64_t $x4(void) {
    // 0x570
    int64_t i_v1; // 0x570
    unknown_43d8(i_v1);
    if ((*(int16_t *)114 & 4) != 0) {
        // 0x698
        single_release(80, 0, i_v1, i_v1);
    }
    int64_t i_v2 = i_v1 + (int64_t)&i_g2;           // 0x594
    int64_t i_v3 = scnprintf(i_v2, 104, 0x24080c0); // 0x5b4
    if (i_v3 == 0) {
        // 0x660
        return 0xfffffff4;
    }
    int64_t i_v4 = strncmp(0xa0000, 0x24080c0, (int64_t *)&p_g12); // 0x5d0
    int64_t *p_v5 = (int64_t *)(i_v3 + 88);                        // 0x5d4
    *p_v5 = i_v4;
    if (i_v4 == 0) {
        // 0x660
        return 0xfffffff4;
    }
    int64_t i_v6 = __platform_driver_register(0, 0); // 0x5e4
    *(int64_t *)72 = i_v6;
    if ((int32_t)i_v6 < 0) {
        // 0x5fc
        kstrtoull(0, *p_v5, (int32_t)&p_g12, i_v1);
        if ((int32_t) * (int64_t *)72 < 0) {
            // 0x60c
            kstrtoull(0, *p_v5, (int32_t)&p_g12, i_v1);
            if ((int32_t) * (int64_t *)72 < 0) {
                // 0x6cc
                kstrtoull(0, *p_v5, (int32_t)&p_g12, i_v1);
            }
        }
    }
    // 0x61c
    *(int64_t *)(i_v3 + (int64_t)&i_g2) = 0;
    int64_t i_v7 = i_v3 + (int64_t)&p_g12; // 0x630
    *(int32_t *)i_v7 = (int32_t)&i_g13;
    int64_t *p_v8 = (int64_t *)i_v3; // 0x638
    *p_v8 = i_v2;
    *(int64_t *)(i_v3 + (int64_t)&i_g6) = 96;
    int64_t i_v9 = __dynamic_pr_debug(i_v7); // 0x640
    uint32_t i_v10 = (int32_t)i_v9;          // 0x648
    if (i_v10 != 0) {
        // 0x678
        proc_remove(*p_v8, 0);
        if (i_v10 <= 0xffffffff) {
            // 0x688
            kstrtoull(0, 0, (int32_t)&p_g12, i_v1);
            // 0x660
            return i_v9 & 0xffffffff;
        }
    }
    // 0x64c
    *(int64_t *)(i_v1 + (int64_t)&i_g2 + 184) = i_v3;
    if ((*(int16_t *)154 & 4) != 0) {
        // 0x6a8
        single_release(120, 0, 336, i_v1);
    }
    // 0x660
    return 0;
}

// Address range: 0x748 - 0x8a8
int64_t $x5(void) {
    // 0x748
    int64_t i_v1; // 0x748
    int64_t i_v2 = i_v1;
    unknown_43d8(i_v1);
    int32_t i_v3 =
        (int32_t)(*(int64_t *)(i_v2 + (int64_t)&p_g12) - i_v2); // 0x784
    uint32_t i_v4 =
        0x1000 * (int32_t) * (int64_t *)(i_v2 + 152) + i_v3; // 0x784
    if (i_v4 >= 0xa0000 == (i_v4 != 0xa0000)) {
        // 0x870
        return 0xffffffea;
    }
    // 0x794
    if (i_v3 == 0) {
        // 0x870
        return 0;
    }
    // 0x7ec
    abort();
    // UNREACHABLE
}

// Address range: 0x8c8 - 0x988
int64_t $x6(void) {
    // 0x8c8
    int64_t i_v1; // 0x8c8
    unknown_43d8(i_v1);
    int64_t i_v2 = 0x80047301; // 0x8f0
    if ((int32_t)i_v1 != -0x7ffb8cff) {
        // 0x8f4
        i_v2 = 0x80047302;
        if ((i_v1 & 0xffffffff) != 0x80047302) {
            // 0x940
            kstrtoull(0, i_v1, (int32_t)i_v1, i_v1);
            return -25;
        }
    }
    int64_t i_v3 = i_v2;                    // 0x90c
    int64_t i_v4 = __asm_mrs(i_v1, i_v1);   // 0x910
    uint64_t i_v5 = i_v1 + (int64_t)&p_g10; // 0x91c
    bool i_v6 = false;                      // 0x920
    bool i_v7 = &i_g1;                      // 0x920
    if (i_v5 >= i_v1) {
        uint64_t i_v8 = *(int64_t *)(i_v4 + (int64_t)&p_g12); // 0x918
        i_v6 = i_v5 == i_v8;
        i_v7 = i_v5 < i_v8 != (bool)&i_g1;
    }
    if (i_v6 || !i_v7) {
        // 0x968
        return memstart_addr(i_v1, &i_v3, (int64_t *)&p_g10) == 0 ? 0 : -14;
    }
    // 0x92c
    return -14;
}

// Address range: 0x990 - 0xa3c
int64_t $x7(void) {
    // 0x990
    int64_t i_v1; // 0x990
    unknown_43d8(i_v1);
    int64_t *p_v2 = (int64_t *)(i_v1 + 200); // 0x9b0
    int64_t i_v3 = *p_v2;                    // 0x9b0
    remove_proc_entry(*(int64_t *)72);
    *(int64_t *)72 = 0;
    int64_t *p_v4 = (int64_t *)(i_v3 + 88); // 0x9d8
    __raw_spin_lock_init(*p_v4);
    *p_v4 = 0;
    __iounmap(i_v3 + 8);
    *p_v2 = 0;
    if ((*(int16_t *)234 & 4) == 0) {
        // 0xa00
        return 0;
    }
    // 0xa18
    single_release(200, 0, (int64_t)&i_g5, i_v1);
    return 0;
}

// Address range: 0xa60 - 0xa7c
int64_t $x8(int64_t i_a1) {
    // 0xa60
    int64_t i_v1; // 0xa60
    unknown_43d8(i_v1);
    return 0;
}

// Address range: 0xa80 - 0xacc
int64_t vip_get_isp_clk(int64_t i_a1) {
    // 0xa80
    int64_t i_v1; // 0xa80
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xad8 - 0xb38
int64_t vip_set_isp_clk(void) {
    // 0xad8
    int64_t i_v1; // 0xad8
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xb40 - 0xb6c
int64_t vip_get_clk_lp(int64_t i_a1) {
    // 0xb40
    int64_t i_v1; // 0xb40
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xb78 - 0xbb0
int64_t vip_set_clk_lp(void) {
    // 0xb78
    int64_t i_v1; // 0xb78
    unknown_43d8(i_v1);
    __asm_dsb(0);
    abort();
    // UNREACHABLE
}

// Address range: 0xbb8 - 0xc00
int64_t vip_get_reset(int64_t i_a1) {
    // 0xbb8
    int64_t i_v1; // 0xbb8
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xc08 - 0xc6c
int64_t vip_set_reset(void) {
    // 0xc08
    int64_t i_v1; // 0xc08
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xc78 - 0xca4
int64_t vip_get_intr_status(int64_t i_a1) {
    // 0xc78
    int64_t i_v1; // 0xc78
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xcb0 - 0xcdc
int64_t vip_get_intr_mask(int64_t i_a1) {
    // 0xcb0
    int64_t i_v1; // 0xcb0
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xce8 - 0xd20
int64_t vip_set_intr_mask(void) {
    // 0xce8
    int64_t i_v1; // 0xce8
    unknown_43d8(i_v1);
    __asm_dsb(0);
    abort();
    // UNREACHABLE
}

// Address range: 0xd28 - 0xd60
int64_t vip_sys_reg_read(void) {
    // 0xd28
    int64_t i_v1; // 0xd28
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xd68 - 0xda0
int64_t vip_set_base_addr(void) {
    // 0xd68
    int64_t i_v1; // 0xd68
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0xdb0 - 0xe20
int64_t vip_toggle_reset(void) {
    // 0xdb0
    int64_t i_v1; // 0xdb0
    unknown_43d8(i_v1);
    int64_t i_v2 = tee_cv_efuse_read((int64_t)&p_g12); // 0xdd8
    seq_puts(0x14f8c);
    return misc_register((int64_t)&p_g12, i_v2);
}

// Address range: 0xe28 - 0xf4c
int64_t vip_isp_clk_reset(void) {
    // 0xe28
    int64_t i_v1; // 0xe28
    unknown_43d8(i_v1);
    int64_t i_v2 =
        printk(0x3002030, (int64_t *)&p_g10,
               (int64_t)&i_g11 & 0xffffffffffff | 0xe8000000000000); // 0xe54
    int64_t i_v3 = tee_cv_efuse_read((int64_t)&p_g12);               // 0xe6c
    int32_t *p_v4 = (int32_t *)i_v2;                                 // 0xf14
    __asm_dsb(0);
    __asm_dsb(0);
    *p_v4 = *p_v4 & -0x3e00001;
    misc_register((int64_t)&p_g12, i_v3);
    return kfree(i_v2);
}

// Address range: 0xf58 - 0xfa4
int64_t vip_sys_reg_write_mask(void) {
    // 0xf58
    int64_t i_v1; // 0xf58
    unknown_43d8(i_v1);
    int64_t i_v2 = function_1028((int64_t)&i_g14, (int64_t)&i_g14,
                                 (int64_t)&i_g14, (int64_t)&i_g14,
                                 (int64_t)&i_g14, (int64_t)&i_g14); // 0xf90
    return i_v2;
}

// Address range: 0xfb0 - 0xff8
int64_t vip_sys_set_offline(void) {
    // 0xfb0
    int64_t i_v1; // 0xfb0
    unknown_43d8(i_v1);
    int64_t i_v2 = function_1028((int64_t)&i_g14, (int64_t)&i_g14,
                                 (int64_t)&i_g14, (int64_t)&i_g14,
                                 (int64_t)&i_g14, (int64_t)&i_g14); // 0xfe8
    return i_v2;
}

// Address range: 0x1000 - 0x1028
int64_t _reg_write_mask(void) {
    // 0x1000
    int64_t i_v1; // 0x1000
    return unknown_43d8(i_v1);
}

// Address range: 0x1028 - 0x1064
int64_t function_1028(int64_t i_a1, int64_t i_a2, int64_t i_a3, int64_t i_a4,
                      int64_t i_a5, int64_t i_a6) {
    // 0x1028
    int64_t i_v1; // 0x1028
    int64_t i_v2 = i_v1;
    int64_t i_v3 = tee_cv_efuse_read(i_v1); // 0x102c
    __asm_dsb(0);
    *(int32_t *)i_v2 = (int32_t)((i_v1 ^ i_v2) & i_v1 ^ i_v2);
    return misc_register(i_v1, i_v3);
}

// Address range: 0x1070 - 0x10a4
int64_t $x9(void) {
    // 0x1070
    int64_t i_v1; // 0x1070
    unknown_43d8(i_v1);
    return unknown_43d0(i_v1, 0, 0);
}

// Address range: 0x10b0 - 0x147c
int64_t $x10(void) {
    // 0x10b0
    int64_t i_v1; // 0x10b0
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x1590 - 0x15c0
int64_t $x11(void) {
    // 0x1590
    int64_t i_v1; // 0x1590
    unknown_43d8(i_v1);
    $x10();
    return 0;
}

// Address range: 0x15c0 - 0x1620
int64_t vb_proc_init(void) {
    // 0x15c0
    int64_t i_v1; // 0x15c0
    unknown_43d8(i_v1);
    if (__arch_copy_to_user(0, 420, i_v1, 0, 0) == 0) {
        // 0x1610
        kstrtoull(0, 420, (int32_t)i_v1, 0);
    }
    // 0x15fc
    abort();
    // UNREACHABLE
}

// Address range: 0x1640 - 0x167c
int64_t vb_proc_remove(void) {
    // 0x1640
    int64_t i_v1; // 0x1640
    unknown_43d8(i_v1);
    strlen(0, i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x1690 - 0x16c4
int64_t $x12(void) {
    // 0x1690
    int64_t i_v1; // 0x1690
    unknown_43d8(i_v1);
    return unknown_43d0(i_v1, 0, 0);
}

// Address range: 0x16d0 - 0x1768
int64_t $x13(void) {
    // 0x16d0
    int64_t i_v1; // 0x16d0
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x1798 - 0x19bc
int64_t $x14(void) {
    // 0x1798
    int64_t i_v1; // 0x1798
    unknown_43d8(i_v1);
    int64_t i_v2 = 0;  // bp-56, 0x17c4
    bool i_v3 = true;  // 0x17d0
    bool i_v4 = &i_g1; // 0x17d0
    if (i_v1 != 0) {
        i_v3 = i_v1 != (int64_t)&i_g7;
        i_v4 = i_v1 >= 31;
    }
    if (i_v4 == i_v3) {
        // 0x19ac
        kstrtoull(0, i_v1, (int32_t)i_v1, i_v1);
        return -22;
    }
    int64_t i_v5 = __asm_mrs(i_v1, i_v1); // 0x17d8
    uint64_t i_v6 = 2 * i_v1;             // 0x17e8
    bool i_v7 = false;                    // 0x17ec
    bool i_v8 = &i_g1;                    // 0x17ec
    if (i_v6 >= i_v1) {
        uint64_t i_v9 = *(int64_t *)(i_v5 + (int64_t)&p_g12); // 0x17e0
        i_v7 = i_v6 == i_v9;
        i_v8 = i_v6 < i_v9 != (bool)&i_g1;
    }
    int64_t i_v10; // 0x1798
    if (i_v7 || !i_v8) {
        int64_t i_v11 = _mcount(&i_v2, i_v1, i_v1); // 0x1900
        if (i_v11 == 0) {
            // 0x1800
            abort();
            // UNREACHABLE
        }
        // 0x1908
        i_v10 = i_v11;
        seq_read(i_v1 + (int64_t)&i_v2 - i_v10, 0, i_v10);
        kstrtoull(0, 0, (int32_t)i_v10, i_v1);
        return -14;
    }
    if (i_v1 == 0) {
        // 0x1800
        abort();
        // UNREACHABLE
    }
    // 0x1908
    int64_t i_v12; // 0x1798
    i_v10 = i_v12;
    seq_read(i_v1 + (int64_t)&i_v2 - i_v10, 0, i_v10);
    kstrtoull(0, 0, (int32_t)i_v10, i_v1);
    return -14;
}

// Address range: 0x1a08 - 0x1a90
int64_t log_proc_init(void) {
    // 0x1a08
    int64_t i_v1; // 0x1a08
    unknown_43d8(i_v1);
    if (__arch_copy_to_user(0, 420, i_v1, (int64_t)&i_g4, 0) == 0) {
        // 0x1a80
        kstrtoull(0, 420, (int32_t)i_v1, 0);
    }
    // 0x1a48
    abort();
    // UNREACHABLE
}

// Address range: 0x1ab0 - 0x1aec
int64_t log_proc_remove(void) {
    // 0x1ab0
    int64_t i_v1; // 0x1ab0
    unknown_43d8(i_v1);
    strlen(0, i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x1b00 - 0x1b34
int64_t $x15(void) {
    // 0x1b00
    int64_t i_v1; // 0x1b00
    unknown_43d8(i_v1);
    return unknown_43d0(i_v1, 0, 0);
}

// Address range: 0x1b40 - 0x1e10
int64_t $x16(void) {
    // 0x1b40
    int64_t i_v1; // 0x1b40
    unknown_43d8(i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x1ea0 - 0x1f04
int64_t sys_proc_init(void) {
    // 0x1ea0
    int64_t i_v1; // 0x1ea0
    unknown_43d8(i_v1);
    if (__arch_copy_to_user(0, 420, i_v1, (int64_t)&i_g4, 0) == 0) {
        // 0x1ef4
        kstrtoull(0, 420, (int32_t)i_v1, (int64_t)&i_g4);
    }
    // 0x1ee0
    abort();
    // UNREACHABLE
}

// Address range: 0x1f28 - 0x1f64
int64_t sys_proc_remove(void) {
    // 0x1f28
    int64_t i_v1; // 0x1f28
    unknown_43d8(i_v1);
    strlen(0, i_v1);
    abort();
    // UNREACHABLE
}

// Address range: 0x1f78 - 0x1fc8
int64_t $x17(void) {
    // 0x1f78
    int64_t i_v1; // 0x1f78
    unknown_6328(i_v1);
    unknown_6330(*(int64_t *)80, 0, 0);
    unknown_6330(*(int64_t *)80, (int64_t)&i_g9, 0);
    return unknown_6200(*(int64_t *)80);
}

// Address range: 0x1fd8 - 0x20b4
int64_t init_module(void) {
    int64_t i_v1 = unknown_62c8(0x3000000, 0x10000,
                                (int64_t)&i_g11 & 0xffffffffffff |
                                    0xe8000000000000); // 0x1ff8
    *(int64_t *)64 = i_v1;
    uint64_t i_v2 = unknown_6238(0, 0, 88); // 0x2014
    *(int64_t *)80 = i_v2;
    uint64_t i_v3 = i_v2 + (int64_t)&i_g3; // 0x201c
    if (i_v3 != 0 && i_v3 < i_v2) {
        // 0x2024
        unknown_62f0(0, 0);
        // 0x209c
        function_3f50();
        // 0x20a0
        return (int64_t) * (int32_t *)80 & 0xffffffff;
    }
    int64_t i_v4 = unknown_62a0(i_v2, 0, 0); // 0x2040
    if ((int32_t)i_v4 != 0) {
        // 0x204c
        unknown_62f0(0, 0);
        // 0x209c
        function_3f50();
        // 0x20a0
        return i_v4 & 0xffffffff & 0xffffffff;
    }
    int64_t i_v5 = unknown_62a0(*(int64_t *)80, (int64_t)&i_g9, 0); // 0x2064
    int64_t i_v6 = i_v5 & 0xffffffff;                               // 0x2068
    if ((int32_t)i_v5 == 0) {
        // 0x207c
        unknown_6330(64, 0, 0);
        unknown_62f0(0, function_2418() & 0xffffffff);
        // 0x20a0
        return i_v6 & 0xffffffff;
    }
    // 0x2070
    unknown_62f0(0, (int64_t)&i_g9);
    // 0x209c
    function_3f50();
    // 0x20a0
    return i_v6 & 0xffffffff;
}

// Address range: 0x20f8 - 0x2124
int64_t cleanup_module(int64_t i_a1) {
    // 0x20f8
    unknown_6368(64);
    function_4070();
    return unknown_6378(*(int64_t *)64);
}

// Address range: 0x2418 - 0x2419
int64_t function_2418(void) {
    // 0x2418
    int64_t i_v1; // 0x2418
    return i_v1;
}

// Address range: 0x3f50 - 0x3f51
int64_t function_3f50(void) {
    // 0x3f50
    int64_t i_v1; // 0x3f50
    return i_v1;
}

// Address range: 0x4070 - 0x4071
int64_t function_4070(void) {
    // 0x4070
    int64_t i_v1; // 0x4070
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (6.3.1)
// Detected functions: 55
