//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __libc_start_main(void);
int32_t abort(void);
int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t execvp(void);
int32_t exit(void);
int32_t fclose(void);
int32_t fopen(void);
int32_t fork(void);
int32_t fscanf(void);
int32_t function_84e4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8588(void);
int32_t function_85c4(int32_t i_a1, int32_t i_a2);
int32_t function_87d8(void);
int32_t function_87fc(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_8834(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8874(void);
int32_t function_889c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_88d0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_88f0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8910(void);
int32_t function_8974(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_89d8(void);
int32_t function_89dc(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t gettimeofday(void);
int32_t printf(void);
int32_t puts(void);
int32_t sleep(void);
int32_t system(void);
int32_t usleep(void);
int32_t wait(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0;           // 0x10c24
int32_t i_g2 = 0;           // 0x10d5c
char *p_g3;                 // 0x10d68
int32_t i_g4 = 0;           // 0x8280
int32_t i_g5 = 0x8594;      // 0x828c
int32_t i_g6 = -0x1e4f9eba; // 0x899c

// ------------------------ Functions -------------------------

// Address range: 0x84e4 - 0x84f0
int32_t function_84e4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x84e4
    return function_87d8();
}

// Address range: 0x8504 - 0x8510
int32_t printf(void) {
    // 0x8504
    int32_t i_v1; // 0x8504
    return i_v1;
}

// Address range: 0x8510 - 0x851c
int32_t fscanf(void) {
    // 0x8510
    int32_t i_v1; // 0x8510
    return i_v1;
}

// Address range: 0x851c - 0x8528
int32_t fopen(void) {
    // 0x851c
    int32_t i_v1; // 0x851c
    return i_v1;
}

// Address range: 0x8528 - 0x8534
int32_t execvp(void) {
    // 0x8528
    int32_t i_v1; // 0x8528
    return i_v1;
}

// Address range: 0x8534 - 0x8540
int32_t sleep(void) {
    // 0x8534
    int32_t i_v1; // 0x8534
    return i_v1;
}

// Address range: 0x8540 - 0x854c
int32_t wait(void) {
    // 0x8540
    int32_t i_v1; // 0x8540
    return i_v1;
}

// Address range: 0x854c - 0x8558
int32_t usleep(void) {
    // 0x854c
    int32_t i_v1; // 0x854c
    return i_v1;
}

// Address range: 0x8558 - 0x8564
int32_t gettimeofday(void) {
    // 0x8558
    int32_t i_v1; // 0x8558
    return i_v1;
}

// Address range: 0x8564 - 0x8570
int32_t puts(void) {
    // 0x8564
    int32_t i_v1; // 0x8564
    return i_v1;
}

// Address range: 0x8570 - 0x857c
int32_t __libc_start_main(void) {
    // 0x8570
    int32_t i_v1; // 0x8570
    return i_v1;
}

// Address range: 0x857c - 0x8588
int32_t system(void) {
    // 0x857c
    int32_t i_v1; // 0x857c
    return i_v1;
}

// Address range: 0x8588 - 0x8594
int32_t function_8588(void) {
    // 0x8588
    int32_t i_v1; // 0x8588
    return i_v1;
}

// Address range: 0x8594 - 0x85a0
int32_t exit(void) {
    // 0x8594
    int32_t i_v1; // 0x8594
    return i_v1;
}

// Address range: 0x85a0 - 0x85ac
int32_t fclose(void) {
    // 0x85a0
    int32_t i_v1; // 0x85a0
    return i_v1;
}

// Address range: 0x85ac - 0x85b8
int32_t fork(void) {
    // 0x85ac
    int32_t i_v1; // 0x85ac
    return i_v1;
}

// Address range: 0x85b8 - 0x85c4
int32_t abort(void) {
    // 0x85b8
    int32_t i_v1; // 0x85b8
    return i_v1;
}

// Address range: 0x85c4 - 0x8770
int32_t function_85c4(int32_t i_a1, int32_t i_a2) {
    // 0x85c4
    printf();
    int32_t i_v1 = 0;
    int32_t i_v2 = (int32_t) "18:32:45"; // 0x85e0
    int32_t i_v3;                        // 0x85c4
    int32_t i_v4;                        // 0x85c4
    int32_t i_v5;                        // 0x85c4
    while (true) {
        int32_t i_v6 = i_v2; // 0x85f0
        int32_t i_v7;        // 0x85c4
        int32_t i_v8 = i_v7; // 0x85f0
        int32_t i_v9 = i_v7; // 0x85f0
        if (function_8910() == 0) {
            while (true) {
                // 0x85f4
                function_88d0(gettimeofday(), 0, i_v6, i_v8);
                puts();
                i_v3 = i_v6;
                i_v4 = i_v8;
                if (function_8910() != 1) {
                    while (true) {
                    lab_generated_0:
                        gettimeofday();
                        while (i_v1 >= 0x2dc6c1) {
                            // 0x8658
                            puts();
                            int32_t i_v10 = function_8910(); // 0x8688
                            int32_t i_v11 = system();        // 0x8690
                            if (i_v10 == 0) {
                                function_88d0(i_v11, i_v5, i_v1, 0x2dc6c0);
                                function_88f0(sleep(), i_v5, i_v1, 0x2dc6c0);
                                sleep();
                                int32_t i_v12 = function_8910(); // 0x8688
                                i_v11 = system();
                                while (i_v12 == 0) {
                                    // 0x8664
                                    function_88d0(i_v11, i_v5, i_v1, 0x2dc6c0);
                                    function_88f0(sleep(), i_v5, i_v1,
                                                  0x2dc6c0);
                                    sleep();
                                    i_v12 = function_8910();
                                    i_v11 = system();
                                }
                            }
                            // 0x8694
                            puts();
                            int32_t i_v13 = fork(); // 0x86a4
                            if (i_v13 < 0) {
                                // 0x8738
                                puts();
                                goto lab_0x8608;
                            }
                            if (i_v13 == 0) {
                                // break (via goto) -> 0x8744
                                goto lab_0x8744;
                            }
                            // 0x86b4
                            wait();
                            int32_t i_v14 = puts(); // 0x86c4
                            int32_t i_v15 = 100;
                            function_88d0(i_v14, i_v5, i_v1, 0x2dc6c0);
                            function_88f0(usleep(), i_v5, i_v1, 0x2dc6c0);
                            i_v14 = usleep();
                            int32_t i_v16 = i_v15 - 1; // 0x86ec
                            while (i_v15 != 1) {
                                // 0x86c8
                                i_v15 = i_v16;
                                function_88d0(i_v14, i_v5, i_v1, 0x2dc6c0);
                                function_88f0(usleep(), i_v5, i_v1, 0x2dc6c0);
                                i_v14 = usleep();
                                i_v16 = i_v15 - 1;
                            }
                            // 0x86f0
                            puts();
                            i_v3 = i_v1;
                            i_v4 = 0x2dc6c0;
                            if (function_8910() == 1) {
                                // break (via goto) -> 0x8708
                                goto lab_0x8708_2;
                            }
                            gettimeofday();
                        }
                        // 0x8728
                        usleep();
                        goto lab_0x8608;
                    }
                }
            lab_0x8708_2:
                // 0x8708
                function_88f0(1, 0, i_v3, i_v4);
                i_v6 = i_v3;
                i_v8 = i_v4;
                i_v2 = i_v3;
                i_v9 = i_v4;
                if (function_8910() != 0) {
                    // break -> 0x871c
                    break;
                }
            }
        }
        // 0x871c
        sleep();
        i_v7 = i_v9;
    }
lab_0x8744:
    // 0x8744
    function_88f0(0, i_v5, i_v1, 0x2dc6c0);
    if (i_a1 < 2) {
        // 0x8764
        sleep();
        // 0x875c
        exit();
        // 0x8764
        sleep();
        // 0x875c
        exit();
        // 0x8764
        sleep();
        goto lab_0x875c;
    } else {
        // 0x8750
        execvp();
        // 0x875c
        exit();
        // 0x8764
        sleep();
        // 0x875c
        exit();
        // 0x8764
        sleep();
        goto lab_0x875c;
    }
lab_0x8608:
    // 0x8608
    i_v3 = i_v1;
    i_v4 = 0x2dc6c0;
    if (function_8910() == 1) {
        // break -> 0x8708
        goto lab_0x8708_2;
    }
    goto lab_generated_1;
}

// Address range: 0x879c - 0x87cc
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x879c
    __libc_start_main();
    return abort();
}

// Address range: 0x87d8 - 0x87f4
int32_t function_87d8(void) {
    // 0x87d8
    if (i_g2 == 0) {
        int32_t i_v1; // 0x87d8
        return i_v1;
    }
    // 0x87f0
    return function_8588();
}

// Address range: 0x87fc - 0x8828
int32_t function_87fc(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x87fc
    return (int32_t)&p_g3;
}

// Address range: 0x8834 - 0x8868
int32_t function_8834(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8834
    return (int32_t)&p_g3;
}

// Address range: 0x8874 - 0x8898
int32_t function_8874(void) {
    // 0x8874
    int32_t i_v1; // 0x8874
    if (*(char *)&p_g3 != 0) {
        return i_v1;
    }
    int32_t i_v2 = function_87fc(i_v1, i_v1, i_v1, 0); // 0x8888
    *(char *)&p_g3 = 1;
    return i_v2;
}

// Address range: 0x889c - 0x88c8
int32_t function_889c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x889c
    return function_8834(&i_g1, i_a2, i_a3, i_a4);
}

// Address range: 0x88d0 - 0x88f0
int32_t function_88d0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x88d0
    system();
    return system();
}

// Address range: 0x88f0 - 0x8910
int32_t function_88f0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x88f0
    system();
    return system();
}

// Address range: 0x8910 - 0x8964
int32_t function_8910(void) {
    // 0x8910
    int32_t i_v1; // 0x8910
    if (fopen() == 0) {
        // 0x8954
        puts();
        i_v1 = -1;
    } else {
        // 0x892c
        fscanf();
        fclose();
        int32_t i_v2; // 0x8910
        i_v1 = i_v2 != 0;
    }
    // 0x894c
    return i_v1;
}

// Address range: 0x8974 - 0x89d0
int32_t function_8974(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_84e4(i_a1, i_a2, i_a3, i_a4); // 0x8990
    int32_t i_v2 =
        (int32_t)&i_g5 + 0x8994 - ((int32_t)&i_g6 + (int32_t)&i_g4) >> 2 == 0
            ? i_v1
            : i_a1;
    return i_v2;
}

// Address range: 0x89d8 - 0x89dc
int32_t function_89d8(void) {
    // 0x89d8
    int32_t i_v1; // 0x89d8
    return i_v1;
}

// Address range: 0x89dc - 0x89e4
int32_t function_89dc(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x89dc
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.x)
// Detected functions: 30
