//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <dirent.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stropts.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct __dirstream {
    int32_t e0;
};

struct dirent64 {
    int32_t e0;
    int32_t e1;
    int16_t e2;
    char e3;
    char e4[256];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_10940(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t *function_10960(int32_t nmemb, int32_t size);
int32_t function_1096c(char *s1, char *s2);
int32_t function_10978(char *nptr, char **endptr, int32_t base);
int32_t function_10984(struct _IO_FILE *stream);
void function_10990(int32_t *ptr);
char *function_1099c(char *s, int32_t n, struct _IO_FILE *stream);
int32_t *function_109a8(int32_t *ptr, int32_t size);
int32_t function_109b4(char *s1, char *s2);
int32_t function_109c0(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s);
int32_t function_109cc(int32_t fd, int32_t request, ...);
char *function_109d8(char *dest, char *src);
struct __dirstream *function_109e4(char *name);
int32_t function_109f0(char *file, int32_t oflag, ...);
int32_t *function_109fc(int32_t size);
int32_t function_10a08(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
char *function_10a14(int32_t errnum);
void function_10a20(void);
void function_10a2c(int32_t status);
int32_t function_10a38(char *nptr, char **endptr, int32_t base);
int32_t function_10a44(char *s);
char *function_10a50(char *s, int32_t c);
int32_t function_10a5c(struct _IO_FILE *stream, char *format, ...);
int32_t *function_10a68(void);
int32_t function_10a74(char *s, int32_t maxlen, char *format, ...);
int32_t function_10a80(char *s, char *format, ...);
char *function_10a8c(char *string);
int32_t *function_10a98(int32_t *s, int32_t c, int32_t n);
int32_t function_10aa4(struct _IO_FILE *stream);
int32_t function_10ab0(struct _IO_FILE *stream);
char *function_10abc(char *s, int32_t c);
int32_t function_10ac8(int32_t c, struct _IO_FILE *stream);
int32_t function_10ad4(char *s, char *format, ...);
struct dirent64 *function_10ae0(struct __dirstream *dirp);
struct _IO_FILE *function_10aec(char *filename, char *modes);
int32_t function_10af8(char *s1, char *s2, int32_t n);
void function_10b04(void);
int32_t function_10b10(int32_t fd);
int32_t function_10b1c(struct __dirstream *dirp);
int32_t function_10b28(int32_t *p_a1, int32_t i_a2, uint32_t i_a3);
int32_t function_10c64(int32_t i_a1, int32_t i_a2);
int32_t function_11464(void);
int32_t function_11470(void);
int32_t function_11494(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_114e8(int32_t i_a1, int32_t i_a2);
int32_t function_114fc(void);
int32_t function_11500(int32_t i_a1);
int32_t function_11570(int32_t i_a1);
int32_t function_115a8(int32_t i_a1, int32_t i_a2);
int32_t function_115f0(int32_t i_a1, int32_t i_a2);
int32_t function_116a8(int32_t i_a1, int32_t *p_a2, int32_t i_a3, int32_t i_a4);
int32_t function_117d8(void);
int32_t function_11dc0(int32_t i_a1);
int32_t function_11f14(int64_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_11f88(int32_t i_a1);
int32_t function_12028(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_12064(void);
int32_t function_12068(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_30000004(void);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

char *x_g1[10] = {"dummy",   "Dummy bus",   "isa",   "ISA bus",
                  "i2c",     "I2C adapter", "smbus", "SMBus adapter",
                  "unknown", "N/A"}; // 0x1269c
int32_t i_g2 = 0x114fd;       // 0x22f08
int32_t i_g3 = 0;             // 0x230a4
struct _IO_FILE *p_g4 = NULL; // 0x230b0
struct _IO_FILE *p_g5 = NULL; // 0x230b8
int32_t i_g6;
int32_t i_g7;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());
char *__strdup(char *p_a1);
struct _IO_FILE *fopen64(char *p_a1, char *p_a2);
int32_t open64(char *p_a1, int32_t i_a2, ...);
struct dirent64 *readdir64(struct __dirstream *p_a1);

// ------------------------ Functions -------------------------

// Address range: 0x10940 - 0x1094c
int32_t function_10940(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10940
    return function_11470();
}

// Address range: 0x10960 - 0x1096c
int32_t *function_10960(int32_t nmemb, int32_t size) {
    // 0x10960
    return calloc(nmemb, size);
}

// Address range: 0x1096c - 0x10978
int32_t function_1096c(char *s1, char *s2) {
    // 0x1096c
    return strcmp(s1, s2);
}

// Address range: 0x10978 - 0x10984
int32_t function_10978(char *nptr, char **endptr, int32_t base) {
    // 0x10978
    return strtol(nptr, endptr, base);
}

// Address range: 0x10984 - 0x10990
int32_t function_10984(struct _IO_FILE *stream) {
    // 0x10984
    return fflush(stream);
}

// Address range: 0x10990 - 0x1099c
void function_10990(int32_t *ptr) {
    // 0x10990
    free(ptr);
}

// Address range: 0x1099c - 0x109a8
char *function_1099c(char *s, int32_t n, struct _IO_FILE *stream) {
    // 0x1099c
    return fgets(s, n, stream);
}

// Address range: 0x109a8 - 0x109b4
int32_t *function_109a8(int32_t *ptr, int32_t size) {
    // 0x109a8
    return realloc(ptr, size);
}

// Address range: 0x109b4 - 0x109c0
int32_t function_109b4(char *s1, char *s2) {
    // 0x109b4
    return strcasecmp(s1, s2);
}

// Address range: 0x109c0 - 0x109cc
int32_t function_109c0(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s) {
    // 0x109c0
    return fwrite(ptr, size, n, s);
}

// Address range: 0x109cc - 0x109d8
int32_t function_109cc(int32_t fd, int32_t request, ...) {
    // 0x109cc
    return ioctl(fd, request);
}

// Address range: 0x109d8 - 0x109e4
char *function_109d8(char *dest, char *src) {
    // 0x109d8
    return strcpy(dest, src);
}

// Address range: 0x109e4 - 0x109f0
struct __dirstream *function_109e4(char *name) {
    // 0x109e4
    return opendir(name);
}

// Address range: 0x109f0 - 0x109fc
int32_t function_109f0(char *file, int32_t oflag, ...) {
    // 0x109f0
    return open64(file, oflag);
}

// Address range: 0x109fc - 0x10a08
int32_t *function_109fc(int32_t size) {
    // 0x109fc
    return malloc(size);
}

// Address range: 0x10a08 - 0x10a14
int32_t function_10a08(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10a08
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10a14 - 0x10a20
char *function_10a14(int32_t errnum) {
    // 0x10a14
    return strerror(errnum);
}

// Address range: 0x10a20 - 0x10a2c
void function_10a20(void) {
    // 0x10a20
    __gmon_start__();
}

// Address range: 0x10a2c - 0x10a38
void function_10a2c(int32_t status) {
    // 0x10a2c
    exit(status);
}

// Address range: 0x10a38 - 0x10a44
int32_t function_10a38(char *nptr, char **endptr, int32_t base) {
    // 0x10a38
    return strtoul(nptr, endptr, base);
}

// Address range: 0x10a44 - 0x10a50
int32_t function_10a44(char *s) {
    // 0x10a44
    return strlen(s);
}

// Address range: 0x10a50 - 0x10a5c
char *function_10a50(char *s, int32_t c) {
    // 0x10a50
    return strchr(s, c);
}

// Address range: 0x10a5c - 0x10a68
int32_t function_10a5c(struct _IO_FILE *stream, char *format, ...) {
    // 0x10a5c
    return fprintf(stream, format);
}

// Address range: 0x10a68 - 0x10a74
int32_t *function_10a68(void) {
    // 0x10a68
    return __errno_location();
}

// Address range: 0x10a74 - 0x10a80
int32_t function_10a74(char *s, int32_t maxlen, char *format, ...) {
    // 0x10a74
    return snprintf(s, maxlen, format);
}

// Address range: 0x10a80 - 0x10a8c
int32_t function_10a80(char *s, char *format, ...) {
    // 0x10a80
    return sscanf(s, format);
}

// Address range: 0x10a8c - 0x10a98
char *function_10a8c(char *string) {
    // 0x10a8c
    return __strdup(string);
}

// Address range: 0x10a98 - 0x10aa4
int32_t *function_10a98(int32_t *s, int32_t c, int32_t n) {
    // 0x10a98
    return memset(s, c, n);
}

// Address range: 0x10aa4 - 0x10ab0
int32_t function_10aa4(struct _IO_FILE *stream) {
    // 0x10aa4
    return fgetc(stream);
}

// Address range: 0x10ab0 - 0x10abc
int32_t function_10ab0(struct _IO_FILE *stream) {
    // 0x10ab0
    return fclose(stream);
}

// Address range: 0x10abc - 0x10ac8
char *function_10abc(char *s, int32_t c) {
    // 0x10abc
    return strrchr(s, c);
}

// Address range: 0x10ac8 - 0x10ad4
int32_t function_10ac8(int32_t c, struct _IO_FILE *stream) {
    // 0x10ac8
    return fputc(c, stream);
}

// Address range: 0x10ad4 - 0x10ae0
int32_t function_10ad4(char *s, char *format, ...) {
    // 0x10ad4
    return sprintf(s, format);
}

// Address range: 0x10ae0 - 0x10aec
struct dirent64 *function_10ae0(struct __dirstream *dirp) {
    // 0x10ae0
    return readdir64(dirp);
}

// Address range: 0x10aec - 0x10af8
struct _IO_FILE *function_10aec(char *filename, char *modes) {
    // 0x10aec
    return fopen64(filename, modes);
}

// Address range: 0x10af8 - 0x10b04
int32_t function_10af8(char *s1, char *s2, int32_t n) {
    // 0x10af8
    return strncmp(s1, s2, n);
}

// Address range: 0x10b04 - 0x10b10
void function_10b04(void) {
    // 0x10b04
    abort();
}

// Address range: 0x10b10 - 0x10b1c
int32_t function_10b10(int32_t fd) {
    // 0x10b10
    return close(fd);
}

// Address range: 0x10b1c - 0x10b28
int32_t function_10b1c(struct __dirstream *dirp) {
    // 0x10b1c
    return closedir(dirp);
}

// Address range: 0x10b28 - 0x10c64
int32_t function_10b28(int32_t *p_a1, int32_t i_a2, uint32_t i_a3) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = __asm_ubfx(i_a3, 2, 1); // 0x10b60
    if (i_a2 == 0) {
        // 0x10c5c
        return i_v1;
    }
    struct _IO_FILE *p_v3 =
        (struct _IO_FILE *)*(int32_t *)(i_a3 % 2 == 0 ? 0x230bc : 0x230b0);
    int32_t i_v4 = 0;
    uint16_t i_v5 = *(int16_t *)(i_v1 + 2); // 0x10b70
    int32_t i_v6;                           // 0x10b28
    int32_t i_v7 = i_v6;                    // 0x10b78
    if (i_v5 % 2 != 0) {
        i_v7 = __asm_ubfxne(i_a3, 1, 1);
    }
    int16_t *p_v8 = (int16_t *)(i_v1 + 4);
    int32_t i_v9 = i_v1; // 0x10b84
    uint16_t i_v10;      // 0x10b90
    char *p_v11;         // 0x10bac
    uint16_t i_v12;      // 0x10b88
    if ((i_a3 & 8) != 0) {
        // 0x10b88
        i_v12 = *p_v8;
        i_v10 = *(int16_t *)i_v1;
        p_v11 = i_v5 % 2 == 0 ? "write" : "read";
        i_v9 = fprintf(p_v3, "msg %u: addr 0x%02x, %s, len %u", i_v4,
                       (int32_t)i_v10, p_v11, (int32_t)i_v12);
    }
    int16_t i_v13 = *p_v8; // 0x10bbc
    int32_t i_v14;         // 0x10b28
    int32_t i_v15;         // 0x10b28
    int16_t i_v16;         // 0x10b28
    int32_t i_v17;         // 0x10b28
    int32_t i_v18;         // 0x10b28
    int32_t i_v19;         // 0x10b28
    int32_t i_v20;         // 0x10b28
    int32_t *p_v21;        // 0x10c04
    int32_t i_v22;         // 0x10c1c
    uint32_t i_v23;        // 0x10c00
    int32_t i_v24;         // 0x10c18
    int32_t i_v25;         // 0x10c1c
    if ((i_v5 % 2 == 0 ? i_v2 : i_v7) == 0 || i_v13 == 0) {
        // 0x10c3c
        i_v19 = i_v9;
        i_v20 = 0;
        if ((i_a3 & 8) != 0) {
            // 0x10c44
            i_v19 = fputc(10, p_v3);
            i_v20 = 0;
        }
    } else {
        // 0x10bd0
        i_v16 = i_v13;
        if ((i_a3 & 8) != 0) {
            // 0x10bd8
            fwrite((int32_t *)", buf ", 1, 6, p_v3);
            i_v16 = *p_v8;
        }
        // 0x10bf0
        p_v21 = (int32_t *)(i_v1 + 8);
        i_v22 = (int32_t) * (char *)*p_v21;
        i_v17 = i_v22;
        i_v18 = 1;
        i_v15 = 1;
        i_v14 = i_v22;
        if (i_v16 > 1) {
            fprintf(p_v3, "0x%02x ", i_v17);
            i_v23 = i_v18 % 0x10000;
            i_v24 = i_v18 + 1;
            i_v25 = (int32_t) * (char *)(*p_v21 + i_v23);
            i_v17 = i_v25;
            i_v18 = i_v24;
            i_v15 = i_v24;
            i_v14 = i_v25;
            while (i_v23 < (int32_t)*p_v8 - 1) {
                // 0x10c24
                fprintf(p_v3, "0x%02x ", i_v17);
                i_v23 = i_v18 % 0x10000;
                i_v24 = i_v18 + 1;
                i_v25 = (int32_t) * (char *)(*p_v21 + i_v23);
                i_v17 = i_v25;
                i_v18 = i_v24;
                i_v15 = i_v24;
                i_v14 = i_v25;
            }
        }
        // 0x10c2c
        i_v19 = fprintf(p_v3, "0x%02x\n", i_v14);
        i_v20 = i_v15;
    }
    int32_t i_v26 = i_v19;
    int32_t i_v27 = i_v4 + 1;  // 0x10c50
    int32_t i_v28 = i_v1 + 12; // 0x10b6c
    while (i_v27 != i_a2) {
        int32_t i_v29 = i_v28;
        i_v4 = i_v27;
        i_v5 = *(int16_t *)(i_v29 + 2);
        i_v7 = i_v20;
        if (i_v5 % 2 != 0) {
            i_v7 = __asm_ubfxne(i_a3, 1, 1);
        }
        p_v8 = (int16_t *)(i_v29 + 4);
        i_v9 = i_v26;
        if ((i_a3 & 8) != 0) {
            // 0x10b88
            i_v12 = *p_v8;
            i_v10 = *(int16_t *)i_v29;
            p_v11 = i_v5 % 2 == 0 ? "write" : "read";
            i_v9 = fprintf(p_v3, "msg %u: addr 0x%02x, %s, len %u", i_v4,
                           (int32_t)i_v10, p_v11, (int32_t)i_v12);
        }
        // 0x10bbc
        i_v13 = *p_v8;
        if ((i_v5 % 2 == 0 ? i_v2 : i_v7) == 0 || i_v13 == 0) {
            // 0x10c3c
            i_v19 = i_v9;
            i_v20 = 0;
            if ((i_a3 & 8) != 0) {
                // 0x10c44
                i_v19 = fputc(10, p_v3);
                i_v20 = 0;
            }
        } else {
            // 0x10bd0
            i_v16 = i_v13;
            if ((i_a3 & 8) != 0) {
                // 0x10bd8
                fwrite((int32_t *)", buf ", 1, 6, p_v3);
                i_v16 = *p_v8;
            }
            // 0x10bf0
            p_v21 = (int32_t *)(i_v29 + 8);
            i_v22 = (int32_t) * (char *)*p_v21;
            i_v17 = i_v22;
            i_v18 = 1;
            i_v15 = 1;
            i_v14 = i_v22;
            if (i_v16 > 1) {
                fprintf(p_v3, "0x%02x ", i_v17);
                i_v23 = i_v18 % 0x10000;
                i_v24 = i_v18 + 1;
                i_v25 = (int32_t) * (char *)(*p_v21 + i_v23);
                i_v17 = i_v25;
                i_v18 = i_v24;
                i_v15 = i_v24;
                i_v14 = i_v25;
                while (i_v23 < (int32_t)*p_v8 - 1) {
                    // 0x10c24
                    fprintf(p_v3, "0x%02x ", i_v17);
                    i_v23 = i_v18 % 0x10000;
                    i_v24 = i_v18 + 1;
                    i_v25 = (int32_t) * (char *)(*p_v21 + i_v23);
                    i_v17 = i_v25;
                    i_v18 = i_v24;
                    i_v15 = i_v24;
                    i_v14 = i_v25;
                }
            }
            // 0x10c2c
            i_v19 = fprintf(p_v3, "0x%02x\n", i_v14);
            i_v20 = i_v15;
        }
        // 0x10c50
        i_v26 = i_v19;
        i_v27 = i_v4 + 1;
        i_v28 = i_v29 + 12;
    }
    // 0x10c5c
    return i_v26;
}

// Address range: 0x10c64 - 0x11440
int32_t function_10c64(int32_t i_a1, int32_t i_a2) {
    // 0x10c64
    int32_t i_v1;         // bp-544, 0x10c64
    int32_t i_v2 = &i_v1; // 0x10c70
    int32_t i_v3;         // bp-40, 0x10c64
    int32_t i_v4 = &i_v3; // 0x10c74
    int32_t i_v5 = i_v2;  // 0x10c7c
    *(int32_t *)(i_v5 + 8) = 0;
    i_v5 += 12;
    while (i_v5 != i_v4) {
        // 0x10c80
        *(int32_t *)(i_v5 + 8) = 0;
        i_v5 += 12;
    }
    int32_t i_v6;  // 0x10c64
    int32_t i_v7;  // 0x10c64
    int32_t i_v8;  // 0x10c64
    int32_t i_v9;  // 0x10c64
    int32_t i_v10; // 0x10c64
    if (i_a1 < 2) {
        // 0x10f98
        i_v6 = 0;
        i_v7 = 0;
        i_v8 = 0;
        i_v9 = 0;
        i_v10 = 1;
        if (i_a1 == 1) {
        lab_0x10f3c:
            // 0x10f3c
            fwrite(
                (int32_t
                     *)"Usage: i2ctransfer [-f] [-y] [-v] [-V] [-a] I2CBUS "
                       "DESC [DATA] [DESC [DATA]]...\n  I2CBUS is an integer "
                       "or an I2C bus name\n  DESC describes the transfer in "
                       "the form: {r|w}LENGTH[@address]\n    1) "
                       "read/write-flag 2) LENGTH (range 0-65535) 3) I2C "
                       "address (use last one if omitted)\n  DATA are LENGTH "
                       "bytes for a write message. They can be shortened by a "
                       "suffix:\n    = (keep value constant until LENGTH)\n    "
                       "+ (increase value by 1 until LENGTH)\n    - (decrease "
                       "value by 1 until LENGTH)\n    p (use pseudo random "
                       "generator until LENGTH with value as seed)\n\nExample "
                       "(bus 0, read 8 byte at offset 0x64 from EEPROM at "
                       "0x50):\n  # i2ctransfer 0 w1@0x50 0x64 r8\nExample "
                       "(same EEPROM, at offset 0x42 write 0xff 0xfe ... "
                       "0xf0):\n  # i2ctransfer 0 w17@0x50 0x42 0xff-\n",
                1, 750, p_g4);
            // 0x10f48
            exit(1);
            // UNREACHABLE
        }
    } else {
        int32_t i_v11 = i_a2 + 4;          // 0x10c98
        int32_t i_v12 = *(int32_t *)i_v11; // 0x10c98
        int32_t i_v13 = 0;                 // 0x10ca8
        int32_t i_v14 = i_v11;             // 0x10ca8
        int32_t i_v15 = i_v12;             // 0x10ca8
        int32_t i_v16 = 0;                 // 0x10ca8
        int32_t i_v17 = 0;                 // 0x10ca8
        int32_t i_v18 = 0;                 // 0x10ca8
        int32_t i_v19 = 0;                 // 0x10ca8
        int32_t i_v20 = 1;                 // 0x10ca8
        i_v6 = 0;
        i_v7 = 0;
        i_v8 = 0;
        i_v9 = 0;
        i_v10 = 1;
        if (*(char *)i_v12 == 45) {
            int32_t i_v21; // 0x10c64
            while (true) {
                int32_t i_v22 = i_v19;
                int32_t i_v23 = i_v18;
                int32_t i_v24 = i_v17;
                int32_t i_v25 = i_v16;
                i_v21 = i_v15;
                int32_t i_v26 = i_v13;
                unsigned char i_v27 = *(char *)(i_v21 + 1); // 0x10cc4
                i_g6 = (int32_t)i_v27 - 86;
                int32_t i_v28 = i_v26; // 0x10cd0
                int32_t i_v29 = i_v25; // 0x10cd0
                int32_t i_v30 = i_v24; // 0x10cd0
                int32_t i_v31 = i_v23; // 0x10cd0
                int32_t i_v32 = 1;     // 0x10cd0
                int32_t i_v33;         // 0x10c64
                int32_t i_v34;         // 0x10d6c
                switch (i_v27) {
                case 86: {
                    // 0x10f00
                    i_v28 = 1;
                    i_v29 = i_v25;
                    i_v30 = i_v24;
                    i_v31 = i_v23;
                    i_v32 = i_v22;
                }
                case 118: {
                lab_0x10d6c:
                    // 0x10d6c
                    i_v33 = i_v28;
                    i_v34 = i_v20 + 1;
                    if (i_v34 == i_a1) {
                        if (i_v33 == 0) {
                            goto lab_0x10f3c;
                        } else {
                            goto lab_0x10f70;
                        }
                    }
                    // break -> 0x10d78
                    break;
                }
                case 121: {
                    // 0x10f10
                    i_v28 = i_v26;
                    i_v29 = i_v25;
                    i_v30 = i_v24;
                    i_v31 = 1;
                    i_v32 = i_v22;
                    // branch (via goto) -> 0x10d6c
                    goto lab_0x10d6c;
                }
                case 102: {
                    // 0x10ef8
                    i_v28 = i_v26;
                    i_v29 = i_v25;
                    i_v30 = 1;
                    i_v31 = i_v23;
                    i_v32 = i_v22;
                    // branch (via goto) -> 0x10d6c
                    goto lab_0x10d6c;
                }
                case 97: {
                    // 0x10f08
                    i_v28 = i_v26;
                    i_v29 = 1;
                    i_v30 = i_v24;
                    i_v31 = i_v23;
                    i_v32 = i_v22;
                    // branch (via goto) -> 0x10d6c
                    goto lab_0x10d6c;
                }
                default: {
                    // 0x10f18
                    fprintf(p_g4, "Error: Unsupported option \"%s\"!\n",
                            (char *)i_v21);
                    // 0x10f3c
                    fwrite(
                        (int32_t
                             *)"Usage: i2ctransfer [-f] [-y] [-v] [-V] [-a] "
                               "I2CBUS DESC [DATA] [DESC [DATA]]...\n  I2CBUS "
                               "is an integer or an I2C bus name\n  DESC "
                               "describes the transfer in the form: "
                               "{r|w}LENGTH[@address]\n    1) read/write-flag "
                               "2) LENGTH (range 0-65535) 3) I2C address (use "
                               "last one if omitted)\n  DATA are LENGTH bytes "
                               "for a write message. They can be shortened by "
                               "a suffix:\n    = (keep value constant until "
                               "LENGTH)\n    + (increase value by 1 until "
                               "LENGTH)\n    - (decrease value by 1 until "
                               "LENGTH)\n    p (use pseudo random generator "
                               "until LENGTH with value as seed)\n\nExample "
                               "(bus 0, read 8 byte at offset 0x64 from EEPROM "
                               "at 0x50):\n  # i2ctransfer 0 w1@0x50 0x64 "
                               "r8\nExample (same EEPROM, at offset 0x42 write "
                               "0xff 0xfe ... 0xf0):\n  # i2ctransfer 0 "
                               "w17@0x50 0x42 0xff-\n",
                        1, 750, p_g4);
                    // 0x10f48
                    exit(1);
                    // UNREACHABLE
                }
                }
                int32_t i_v35 = i_v32;
                int32_t i_v36 = i_v31;
                int32_t i_v37 = i_v30;
                int32_t i_v38 = i_v29;
                int32_t i_v39 = i_v14 + 4;         // 0x10d78
                int32_t i_v40 = *(int32_t *)i_v39; // 0x10d78
                i_v13 = i_v33;
                i_v14 = i_v39;
                i_v15 = i_v40;
                i_v16 = i_v38;
                i_v17 = i_v37;
                i_v18 = i_v36;
                i_v19 = i_v35;
                i_v20 = i_v34;
                if (*(char *)i_v40 != 45) {
                    // 0x10d88
                    i_v6 = i_v38;
                    i_v7 = i_v37;
                    i_v8 = i_v36;
                    i_v9 = i_v35;
                    i_v10 = i_v34;
                    if (i_v33 == 0) {
                        goto lab_0x10d90;
                    } else {
                        goto lab_0x10f70;
                    }
                }
            }
            // 0x10f18
            fprintf(p_g4, "Error: Unsupported option \"%s\"!\n", (char *)i_v21);
            // 0x10f3c
            fwrite(
                (int32_t
                     *)"Usage: i2ctransfer [-f] [-y] [-v] [-V] [-a] I2CBUS "
                       "DESC [DATA] [DESC [DATA]]...\n  I2CBUS is an integer "
                       "or an I2C bus name\n  DESC describes the transfer in "
                       "the form: {r|w}LENGTH[@address]\n    1) "
                       "read/write-flag 2) LENGTH (range 0-65535) 3) I2C "
                       "address (use last one if omitted)\n  DATA are LENGTH "
                       "bytes for a write message. They can be shortened by a "
                       "suffix:\n    = (keep value constant until LENGTH)\n    "
                       "+ (increase value by 1 until LENGTH)\n    - (decrease "
                       "value by 1 until LENGTH)\n    p (use pseudo random "
                       "generator until LENGTH with value as seed)\n\nExample "
                       "(bus 0, read 8 byte at offset 0x64 from EEPROM at "
                       "0x50):\n  # i2ctransfer 0 w1@0x50 0x64 r8\nExample "
                       "(same EEPROM, at offset 0x42 write 0xff 0xfe ... "
                       "0xf0):\n  # i2ctransfer 0 w17@0x50 0x42 0xff-\n",
                1, 750, p_g4);
            // 0x10f48
            exit(1);
            // UNREACHABLE
        }
    }
    goto lab_0x10d90;
lab_0x11054:;
    // 0x11054
    int32_t i_v72;         // 0x10c64
    int32_t i_v66 = i_v72; // 0x11000
    int32_t i_v70;         // 0x11008
    int32_t i_v67 = i_v70; // 0x11000
    int32_t i_v65 = i_v70; // 0x11000
    uint32_t i_v64;        // 0x10ff8
    if (i_v70 >= i_v64) {
        // break -> 0x11160
        goto lab_0x11160_2;
    }
    goto lab_0x11004;
lab_0x110dc_2:;
    // 0x110dc
    int32_t *p_v59; // 0x10e2c
    fprintf(p_g4, "Error: faulty argument is '%s'\n", (char *)*p_v59);
    int32_t i_v56;         // 0x10c64
    int32_t i_v82 = i_v56; // 0x110f4
    goto lab_0x1108c;
lab_0x10ee0:;
    // 0x10ee0
    int32_t i_v75;             // 0x10c64
    int32_t i_v77 = i_v75;     // 0x10ee4
    int32_t i_v76;             // 0x10c64
    int32_t i_v78 = i_v76;     // 0x10ee4
    int32_t i_v79 = i_v56 + 1; // 0x10ee4
    int32_t i_v80 = 0;         // 0x10ee4
    goto lab_0x10ee8;
lab_0x10ee8:;
    int32_t i_v89 = i_v80;
    int32_t i_v86 = i_v79;
    int32_t i_v50; // 0x10c64
    int32_t i_v90 = i_v50 + 1;
    i_v50 = i_v90;
    int32_t i_v51 = i_v89; // 0x10e1c
    int32_t i_v52 = i_v86; // 0x10e1c
    int32_t i_v53 = i_v78; // 0x10e1c
    int32_t i_v54 = i_v77; // 0x10e1c
    int32_t i_v55;         // 0x10c64
    i_v55 += 4;
    int32_t i_v48; // 0x10c64
    int32_t i_v44; // bp-564, 0x10c64
    if (i_v90 >= i_a1) {
        // 0x111c4
        i_v48 = i_v86;
        if (i_v86 != 0 == i_v89 == 0) {
            if (i_v8 == 0) {
                // 0x111e4
                fwrite((int32_t *)"WARNING! This program can confuse your I2C "
                                  "bus, cause data loss and worse!\n",
                       1, 75, p_g4);
                fprintf(
                    p_g4,
                    "I will send the following messages to device file %s:\n",
                    &i_v44);
                function_10b28(&i_v1, i_v86, 13);
                fwrite((int32_t *)"Continue? [y/N] ", 1, 16, p_g4);
                fflush(p_g4);
                if (function_11f88(0) == 0) {
                    // 0x11424
                    fwrite((int32_t *)"Aborting on user request.\n", 1, 26,
                           p_g4);
                    goto lab_0x112bc;
                } else {
                    goto lab_0x11258;
                }
            } else {
                goto lab_0x11258;
            }
        } else {
            goto lab_0x11320;
        }
    }
    goto lab_0x10e20;
lab_0x10e5c:;
    // 0x10e5c
    int32_t i_v60;                                      // 0x10e2c
    int32_t i_v91 = i_v60 + 1;                          // 0x10e44
    char *p_v46;                                        // bp-572, 0x10c64
    uint32_t i_v92 = strtoul((char *)i_v91, &p_v46, 0); // 0x10e68
    if (i_v92 >= 0x10000) {
        // 0x11400
        fwrite((int32_t *)"Error: Length invalid\n", 1, 22, p_g4);
        goto lab_0x110dc_2;
    }
    int32_t i_v93 = (int32_t)p_v46; // 0x10e78
    if (i_v91 == i_v93) {
        // 0x11400
        fwrite((int32_t *)"Error: Length invalid\n", 1, 22, p_g4);
        goto lab_0x110dc_2;
    }
    // 0x10e84
    int32_t i_v81; // 0x10c64
    int32_t i_v94 = i_v81;
    int32_t i_v57; // 0x10c64
    int32_t i_v95; // 0x10c64
    int32_t i_v43; // 0x10db0
    char *p_v96;   // 0x10e78
    switch (*p_v96) {
    case 0: {
        // 0x11130
        i_v95 = i_v57;
        if (i_v57 == -1) {
            // 0x1113c
            fwrite((int32_t *)"Error: No address given\n", 1, 24, p_g4);
            goto lab_0x110dc_2;
        }
        goto lab_0x10eb8;
    }
    case 64: {
        int32_t i_v97 = function_115f0(i_v93 + 1, i_v6); // 0x10ea0
        if (i_v97 < 0) {
            goto lab_0x110dc_2;
        }
        // 0x10eb0
        i_v95 = i_v97;
        if (i_v7 == 0) {
            // 0x11344
            i_v95 = i_v97;
            if (function_11f14((int64_t)(i_v43 < 0), i_v43, 0) != 0) {
                goto lab_0x110dc_2;
            }
        }
        goto lab_0x10eb8;
    }
    default: {
        // 0x11364
        fwrite((int32_t *)"Error: Unknown separator after length\n", 1, 38,
               p_g4);
        goto lab_0x110dc_2;
    }
    }
lab_0x10eb8:;
    int32_t i_v98 = i_v95;
    int32_t i_v99 = 12 * i_v56;    // 0x10ec0
    int32_t i_v100 = i_v99 + i_v2; // 0x10ecc
    *(int16_t *)i_v100 = (int16_t)i_v98;
    *(int16_t *)(i_v100 | 2) = (int16_t)i_v94;
    *(int16_t *)(i_v100 + 4) = (int16_t)i_v92;
    i_v75 = i_v98;
    int32_t i_v58; // 0x10c64
    i_v76 = i_v58;
    int32_t i_v49; // 0x10c64
    if (i_v92 == 0) {
        goto lab_0x10ee0;
    } else {
        int32_t *p_v101 = calloc(i_v92, 1); // 0x11174
        if (p_v101 == NULL) {
            // 0x11388
            fwrite((int32_t *)"Error: No memory for buffer\n", 1, 28, p_g4);
            goto lab_0x110dc_2;
        }
        // 0x11180
        *(int32_t *)(i_v99 + i_v49) = (int32_t)p_v101;
        i_v75 = i_v98;
        i_v76 = i_v58;
        i_v77 = i_v98;
        i_v78 = 0;
        i_v79 = i_v56;
        i_v80 = 1;
        if (i_v94 == 0) {
            goto lab_0x10ee8;
        } else {
            goto lab_0x10ee0;
        }
    }
lab_0x10d90:;
    int32_t i_v41 = 4 * i_v10;                                  // 0x10d90
    int32_t i_v42 = function_11dc0(*(int32_t *)(i_v41 + i_a2)); // 0x10d98
    if (i_v42 < 0) {
        // 0x10f48
        exit(1);
        // UNREACHABLE
    }
    // 0x10da4
    i_v43 = function_116a8(i_v42, &i_v44, 20, 0);
    if (i_v43 < 0) {
        // 0x10f48
        exit(1);
        // UNREACHABLE
    }
    // 0x10dc0
    if (ioctl(i_v43, 1797) < 0) {
        int32_t i_v45 = *__errno_location(); // 0x113e0
        fprintf(p_g4,
                "Error: Could not get the adapter functionality matrix: %s\n",
                strerror(i_v45));
        // 0x10f48
        exit(1);
        // UNREACHABLE
    }
    // 0x10dd4
    if ((int32_t)p_v46 % 2 == 0) {
        // 0x113ac
        fprintf(p_g4, "Error: Adapter does not have %s capability\n",
                "I2C transfers");
        // 0x10f48
        exit(1);
        // UNREACHABLE
    }
    int32_t i_v47 = i_v10 + 1;
    i_v48 = 0;
    if (i_v47 < i_a1) {
        // 0x10e20
        i_v49 = i_v4 - 496;
        i_v50 = i_v47;
        i_v51 = 0;
        i_v52 = 0;
        i_v53 = 0;
        i_v54 = -1;
        i_v55 = i_a2 + 4 + i_v41;
        while (true) {
        lab_0x10e20:
            // 0x10e20
            i_v56 = i_v52;
            if (i_v56 > 42) {
                // break -> 0x11070
                break;
            }
            // 0x10e38
            i_v57 = i_v54;
            i_v58 = i_v53;
            p_v59 = (int32_t *)i_v55;
            i_v60 = *p_v59;
            char *p_v61 = (char *)i_v60;
            if (i_v51 == 1) {
                uint32_t i_v62 = strtoul(p_v61, &p_v46, 0); // 0x10fc0
                if (i_v62 >= 255 == (i_v62 != 255)) {
                    // 0x111a0
                    fwrite((int32_t *)"Error: Invalid data byte\n", 1, 25,
                           p_g4);
                    goto lab_0x110dc_2;
                }
                // 0x10fcc
                if (i_v60 == (int32_t)p_v46) {
                    // 0x111a0
                    fwrite((int32_t *)"Error: Invalid data byte\n", 1, 25,
                           p_g4);
                    goto lab_0x110dc_2;
                }
                int32_t i_v63 = 12 * i_v56; // 0x10fe0
                i_v64 = (int32_t) * (int16_t *)(i_v2 + 4 + i_v63);
                i_v65 = i_v58;
                if (i_v58 < i_v64) {
                    // 0x11004
                    i_v66 = i_v62 % 256;
                    i_v67 = i_v58;
                    while (true) {
                    lab_0x11004:;
                        int32_t i_v68 = i_v66;
                        int32_t i_v69 = *(int32_t *)(i_v63 + i_v49); // 0x11004
                        i_v70 = i_v67 + 1;
                        *(char *)(i_v69 + i_v67) = (char)i_v68;
                        unsigned char i_v71 = *p_v46; // 0x11014
                        i_v65 = i_v70;
                        switch (i_v71) {
                        case 0: {
                            goto lab_0x11160_2;
                        }
                        case 45: {
                            // 0x110f8
                            i_v72 = (i_v68 + 255) % 256;
                            goto lab_0x11054;
                        }
                        default: {
                            if (i_v71 < 45) {
                                if (i_v71 != 43) {
                                    struct _IO_FILE *p_v73 = p_g4; // 0x11114
                                    fwrite((int32_t *)"Error: Invalid data "
                                                      "byte suffix\n",
                                           1, 32, p_v73);
                                    goto lab_0x110dc_2;
                                }
                                // 0x11064
                                i_v72 = (i_v68 + 1) % 256;
                                goto lab_0x11054;
                            } else {
                                // 0x1102c
                                i_v72 = i_v68;
                                switch (i_v71) {
                                case 61: {
                                    goto lab_0x11054;
                                }
                                case 112: {
                                    uint32_t i_v74 =
                                        ((i_v68 ^ 27) + 13) % 256; // 0x11044
                                    i_v72 = 2 * i_v74 & 254 | i_v74 / 128;
                                    goto lab_0x11054;
                                }
                                default: {
                                    // 0x11104
                                    fwrite((int32_t *)"Error: Invalid data "
                                                      "byte suffix\n",
                                           1, 32, p_g4);
                                    goto lab_0x110dc_2;
                                }
                                }
                            }
                        }
                        }
                    }
                }
            lab_0x11160_2:
                // 0x11160
                i_v75 = i_v57;
                i_v76 = i_v64;
                i_v77 = i_v57;
                i_v78 = i_v65;
                i_v79 = i_v56;
                i_v80 = 1;
                if (i_v65 == i_v64) {
                    goto lab_0x10ee0;
                } else {
                    goto lab_0x10ee8;
                }
            } else {
                // 0x10e40
                i_v81 = 1;
                switch (*p_v61) {
                case 114: {
                    goto lab_0x10e5c;
                }
                case 119: {
                    // 0x10e5c
                    i_v81 = 0;
                    goto lab_0x10e5c;
                }
                default: {
                    // 0x110bc
                    fwrite((int32_t *)"Error: Invalid direction\n", 1, 25,
                           p_g4);
                    goto lab_0x110dc_2;
                }
                }
            }
        }
        // 0x11070
        fprintf(p_g4, "Error: Too many messages (max: %d)\n", 42);
        i_v82 = i_v56;
        goto lab_0x1108c;
    } else {
        goto lab_0x11320;
    }
lab_0x11320:
    // 0x11320
    fwrite((int32_t *)"Error: Incomplete message\n", 1, 26, p_g4);
    i_v82 = i_v48;
    goto lab_0x1108c;
lab_0x1108c:
    // 0x1108c
    close(i_v43);
    int32_t i_v83 = 0;         // 0x11098
    int32_t i_v84 = i_v83 + 1; // 0x110a4
    free((int32_t *)*(int32_t *)(i_v2 + 8 + 12 * i_v83));
    i_v83 = i_v84;
    while (i_v82 >= i_v84) {
        // 0x1109c
        i_v84 = i_v83 + 1;
        free((int32_t *)*(int32_t *)(i_v2 + 8 + 12 * i_v83));
        i_v83 = i_v84;
    }
    // 0x10f48
    exit(1);
    // UNREACHABLE
lab_0x10f70:
    // 0x10f70
    fprintf(p_g4, "i2ctransfer version %s\n", "4.1");
    exit(0);
    // UNREACHABLE
lab_0x11258:
    // 0x11258
    p_v46 = (char *)&i_v1;
    int32_t i_v85 = ioctl(i_v43, 1799); // 0x11270
    if (i_v85 < 0) {
        // 0x112f0
        fprintf(p_g4, "Error: Sending messages failed: %s\n",
                strerror(*__errno_location()));
        i_v82 = i_v86;
        goto lab_0x1108c;
    } else {
        if (i_v86 > i_v85) {
            // 0x11284
            fprintf(p_g4, "Warning: only %d/%d messages were sent\n", i_v85,
                    i_v86);
            // 0x112a4
            function_10b28(&i_v1, i_v85, i_v9 == 0 ? 2 : 14);
            goto lab_0x112bc;
        } else {
            // 0x112a4
            function_10b28(&i_v1, i_v85, i_v9 == 0 ? 2 : 14);
            goto lab_0x112bc;
        }
    }
lab_0x112bc:
    // 0x112bc
    close(i_v43);
    int32_t i_v87 = 0; // 0x112c8
    goto lab_0x112cc;
lab_0x112cc:;
    int32_t i_v88 = i_v87 + 1; // 0x112d4
    free((int32_t *)*(int32_t *)(i_v2 + 8 + 12 * i_v87));
    i_v87 = i_v88;
    if (i_v86 <= i_v88) {
        // 0x112e8
        exit(0);
        // UNREACHABLE
    }
    goto lab_0x112cc;
}

// Address range: 0x11440 - 0x11464
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x11440
    int32_t i_v1; // 0x11440
    __libc_start_main(0x10c64, i_a2, (char **)&i_v1, (void (*)())0x12029,
                      (void (*)())0x10c64, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x11464 - 0x11468
int32_t function_11464(void) {
    // 0x11464
    return 101;
}

// Address range: 0x11470 - 0x1148c
int32_t function_11470(void) {
    // 0x11470
    if (i_g3 == 0) {
        int32_t i_v1; // 0x11470
        return i_v1;
    }
    // 0x11488
    __gmon_start__();
    return &i_g7;
}

// Address range: 0x11494 - 0x114e8
int32_t function_11494(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x11494
    int32_t i_v1; // 0x11494
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x11494
    if (i_v3) {
        return i_a1;
    }
    bool i_v4; // 0x11494
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x114cc
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x114dc
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    float64_t f_v6; // 0x11494
    __asm_vqrshl_s8(f_v6, f_v6);
    return i_a1;
}

// Address range: 0x114e8 - 0x114fc
int32_t function_114e8(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = 0x80000 * i_a1;         // 0x114e8
    int32_t i_v2;                          // 0x114e8
    char *p_v3 = (char *)(i_v2 | 0x20000); // 0x114ee
    int32_t i_v4 = i_v1;                   // 0x114f0
    if (*p_v3 == 0) {
        // 0x114f2
        i_v4 = function_11494(i_v1, i_v2, i_v2, 0);
        *p_v3 = 1;
    }
    // 0x114fa
    return i_v4;
}

// Address range: 0x114fc - 0x114fe
int32_t function_114fc(void) {
    // 0x114fc
    int32_t i_v1; // 0x114fc
    return i_v1;
}

// Address range: 0x11500 - 0x11570
int32_t function_11500(int32_t i_a1) {
    int32_t i_v1 = strlen((char *)i_a1); // 0x11508
    if (i_v1 == 0) {
        // 0x11558
        return 1;
    }
    int32_t i_v2 = i_v1 - 1;
    int32_t i_v3 = i_v2 + i_a1;
    char *p_v4 = (char *)i_v3;
    char i_v5 = *p_v4; // 0x11514
    int32_t i_v6;      // 0x11500
    int32_t i_v7;      // 0x11500
    int32_t i_v8;      // 0x11500
    char i_v9;         // 0x11500
    int32_t i_v10;     // 0x1154c
    char *p_v11;       // 0x11500
    switch (i_v5) {
    case 32: {
    }
    case 10: {
        // 0x11548
        int32_t i_v12; // 0x11500
        i_v9 = i_v5 == 10 | i_v5 == 32 ? 0 : (char)i_v12;
        *p_v4 = i_v9;
        i_v6 = i_v3;
        if (i_v2 == 0) {
            // 0x11558
            return 1;
        }
        i_v7 = i_v2;
        while (true) {
        lab_0x11534:
            // 0x11534
            i_v8 = i_v7;
            i_v10 = i_v6 - 1;
            p_v11 = (char *)i_v10;
            switch (*p_v11) {
            case 32: {
                goto lab_0x11548;
            }
            case 10: {
                goto lab_0x11548;
            }
            default: {
                return i_v8 + 1;
            }
            }
        }
    }
    default: {
        // 0x11568
        return i_v1 + 1;
    }
    }
    // 0x11560
    return i_v8 + 1;
lab_0x11548:;
    int32_t i_v13 = i_v8 - 1; // 0x11548
    *p_v11 = i_v9;
    i_v6 = i_v10;
    i_v7 = i_v13;
    if (i_v13 == 0) {
        // 0x11558
        return 1;
    }
    goto lab_0x11534;
}

// Address range: 0x11570 - 0x115a8
int32_t function_11570(int32_t i_a1) {
    int32_t i_v1 = *(int32_t *)(i_a1 + 4); // 0x11578
    int32_t i_v2 = i_a1;                   // 0x11580
    if (i_v1 == 0) {
        // 0x1159c
        free((int32_t *)i_a1);
        return &i_g7;
    }
    free((int32_t *)i_v1);
    int32_t i_v3 = *(int32_t *)(i_v2 + 20); // 0x11590
    i_v2 += 16;
    while (i_v3 != 0) {
        // 0x11588
        free((int32_t *)i_v3);
        i_v3 = *(int32_t *)(i_v2 + 20);
        i_v2 += 16;
    }
    // 0x1159c
    free((int32_t *)i_a1);
    return &i_g7;
}

// Address range: 0x115a8 - 0x115f0
int32_t function_115a8(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = 16 * i_a2;                             // 0x115a8
    int32_t *p_v2 = realloc((int32_t *)i_a1, i_v1 + 128); // 0x115bc
    int32_t i_v3 = (int32_t)p_v2;                         // 0x115bc
    if (p_v2 == NULL) {
        // 0x115e4
        function_11570(i_a1);
    } else {
        // 0x115c8
        memset((int32_t *)(i_v1 + i_v3), 0, 128);
    }
    // 0x115dc
    return i_v3;
}

// Address range: 0x115f0 - 0x116a8
int32_t function_115f0(int32_t i_a1, int32_t i_a2) {
    // 0x115f0
    char *p_v1;                                    // bp-20, 0x115f0
    int32_t i_v2 = strtol((char *)i_a1, &p_v1, 0); // 0x11608
    if ((char)i_v2 == 0 | *p_v1 != 0) {
        // 0x11660
        fwrite((int32_t *)"Error: Chip address is not a number!\n", 1, 37,
               p_g4);
        // 0x11658
        return -1;
    }
    int32_t i_v3 = i_a2 == 0 ? 3 : 0;
    int32_t i_v4 = i_a2 == 0 ? 119 : 127;
    int32_t i_v5 = i_v2; // 0x11654
    if (i_v3 > i_v2 || i_v4 < i_v2) {
        // 0x11688
        fprintf(p_g4, "Error: Chip address out of range (0x%02lx-0x%02lx)!\n",
                i_v3, i_v4);
        i_v5 = -2;
    }
    // 0x11658
    return i_v5;
}

// Address range: 0x116a8 - 0x117d8
int32_t function_116a8(int32_t i_a1, int32_t *p_a2, int32_t i_a3,
                       int32_t i_a4) {
    // 0x116a8
    snprintf((char *)p_a2, i_a3, "/dev/i2c/%d", i_a1);
    *(char *)(i_a3 - 1 + (int32_t)p_a2) = 0;
    int32_t i_v1 = open64((char *)p_a2, 2); // 0x116ec
    if (i_v1 >= 0) {
        // 0x116f8
        return i_v1;
    }
    int32_t i_v2 = *__errno_location(); // 0x11708
    int32_t i_v3 = i_v1;                // 0x116a8
    switch (i_v2) {
    case 20: {
    }
    case 2: {
        // 0x117b0
        sprintf((char *)p_a2, "/dev/i2c-%d", i_a1);
        i_v3 = open64((char *)p_a2, 2);
        // break -> 0x116f8
        break;
    }
    }
    // 0x116f8
    return i_v3;
}

// Address range: 0x117d8 - 0x11dc0
int32_t function_117d8(void) {
    // 0x117d8
    int32_t i_v1; // 0x117d8
    uint32_t i_v2 = i_v1;
    int32_t *p_v3 = calloc(8, 16); // 0x117e8
    int32_t i_v4 = (int32_t)p_v3;  // 0x117e8
    if (p_v3 == NULL) {
        // 0x11944
        return i_v4;
    }
    struct _IO_FILE *p_v5 = fopen64("/proc/bus/i2c", "r"); // 0x11804
    struct dirent64 *p_v6;                                 // 0x117d8
    int32_t i_v7;                                          // 0x117d8
    int32_t i_v8;                                          // 0x117d8
    int32_t i_v9;                                          // 0x117d8
    int32_t i_v10;                                         // 0x117d8
    int32_t i_v11;                                         // bp-296, 0x117d8
    int32_t i_v12;                                         // bp-552, 0x117d8
    struct __dirstream *p_v13;                             // 0x11a34
    if (p_v5 == NULL) {
        struct _IO_FILE *p_v14 = fopen64("/proc/mounts", "r"); // 0x11978
        if (p_v14 == NULL) {
            // 0x11944
            return i_v4;
        }
        while (fgets((char *)&i_v11, 255, p_v14) != NULL) {
            // 0x11998
            int32_t i_v15; // bp-808, 0x117d8
            sscanf((char *)&i_v11, "%*[^ ] %[^ ] %[^ ] %*s\n", &i_v12, &i_v15);
            if (strcasecmp((char *)&i_v15, "sysfs") == 0) {
                // 0x119e4
                fclose(p_v14);
                int32_t i_v16 =
                    strlen((char *)&i_v12) + (int32_t)&i_v12; // 0x11a08
                *(int32_t *)i_v16 = 0x616c632f;
                *(int32_t *)(i_v16 + 4) = 0x692f7373;
                *(int32_t *)(i_v16 + 8) = 0x642d6332;
                *(int16_t *)(i_v16 + 12) = 0x7665;
                *(char *)(i_v16 + 14) = 0;
                p_v13 = opendir((char *)&i_v12);
                i_v7 = i_v4;
                if (p_v13 == NULL) {
                    return i_v7;
                } else {
                    struct dirent64 *p_v17 = readdir64(p_v13); // 0x11a60
                    i_v9 = i_v4;
                    if (p_v17 == NULL) {
                        goto lab_0x11bac;
                    } else {
                        // 0x11a6c
                        p_v6 = p_v17;
                        i_v8 = i_v4;
                        i_v10 = 0;
                        goto lab_0x11a6c_2;
                    }
                }
            }
        }
        // 0x119d8
        fclose(p_v14);
        // 0x11944
        return i_v4;
    }
    // 0x11914
    int32_t i_v18;                                  // bp-928, 0x117d8
    char *p_v19 = fgets((char *)&i_v18, 120, p_v5); // 0x11924
    int32_t i_v20 = 1;                              // 0x11938
    int32_t i_v21 = i_v4;                           // 0x11938
    int32_t i_v22 = 0;                              // 0x11938
    if (p_v19 == NULL) {
        // 0x1193c
        fclose(p_v5);
        // 0x11944
        return i_v4;
    }
    int32_t i_v23; // 0x117d8
    while (true) {
        int32_t i_v24 = i_v21;
        uint32_t i_v25 = i_v20;
        char *p_v26 = strrchr((char *)&i_v18, 9); // 0x11830
        int32_t i_v27 = (int32_t)p_v26 + 1;       // 0x11834
        *p_v26 = 0;
        function_11500(i_v27);
        char *p_v28 = strrchr((char *)&i_v18, 9); // 0x11850
        int32_t i_v29 = (int32_t)p_v28 + 1;       // 0x11854
        *p_v28 = 0;
        int32_t i_v30 = function_11500(i_v29);    // 0x11860
        char *p_v31 = strrchr((char *)&i_v18, 9); // 0x11870
        int32_t i_v32 = (int32_t)p_v31 + 1;       // 0x11874
        *p_v31 = 0;
        int32_t i_v33 = function_11500(i_v32); // 0x11880
        sscanf((char *)&i_v18, "i2c-%d", &i_v11);
        int32_t i_v34 = i_v24; // 0x118ac
        if (i_v25 % 8 == 0) {
            // 0x118b0
            i_v34 = function_115a8(i_v24, i_v25);
            i_v7 = 0;
            if (i_v34 == 0) {
                // break -> 0x11944
                break;
            }
        }
        int32_t i_v35 = i_v33 + i_v30; // 0x11890
        i_v21 = i_v34;
        int32_t *p_v36 = malloc((i_v35 >> 31) + i_v35); // 0x118c8
        i_v23 = i_v21;
        if (p_v36 == NULL) {
            goto lab_0x11950;
        }
        int32_t i_v37 = i_v21 + i_v22;  // 0x118c0
        int32_t i_v38 = (int32_t)p_v36; // 0x118c8
        *(int32_t *)i_v37 = i_v11;
        char *p_v39 = strcpy((char *)p_v36, (char *)i_v29); // 0x118e4
        *(int32_t *)(i_v37 + 4) = (int32_t)p_v39;
        char *p_v40 = strcpy((char *)(i_v30 + i_v38), (char *)i_v32); // 0x118f8
        *(int32_t *)(i_v37 + 8) = (int32_t)p_v40;
        char *p_v41 = strcpy((char *)(i_v35 + i_v38), (char *)i_v27); // 0x1190c
        *(int32_t *)(i_v37 + 12) = (int32_t)p_v41;
        char *p_v42 = fgets((char *)&i_v18, 120, p_v5); // 0x11924
        i_v20 = i_v25 + 1;
        i_v22 += 16;
        int32_t i_v43 = i_v21; // 0x11938
        if (p_v42 == NULL) {
            // 0x1193c
            fclose(p_v5);
            // 0x11944
            return i_v43;
        }
    }
lab_0x11944:
    // 0x11944
    return i_v7;
lab_0x11950:
    // 0x11950
    function_11570(i_v23);
    i_v7 = 0;
    return i_v7;
lab_0x11bac:
    // 0x11bac
    closedir(p_v13);
    i_v7 = i_v9;
    goto lab_0x11944;
lab_0x11a6c_2:;
    struct dirent64 *p_v44 = p_v6; // 0x117d8
    int32_t i_v45 = i_v10;         // 0x117d8
    int32_t i_v46 = i_v8;          // 0x117d8
    goto lab_0x11a6c_3;
lab_0x11a6c_3:;
    int32_t i_v47 = i_v46;
    int32_t i_v48 = i_v45;
    int32_t i_v49 = (int32_t)p_v44;
    char *p_v50 = (char *)(i_v49 + 19); // 0x11a6c
    if (*p_v50 == 46) {
        // 0x11bb8
        switch (*(char *)(i_v49 + 20)) {
        case 0: {
            goto lab_0x11a5c_2;
        }
        case 46: {
            // 0x11bcc
            if (*(char *)(i_v49 + 21) == 0) {
                goto lab_0x11a5c_2;
            } else {
                goto lab_0x11a78;
            }
        }
        default: {
            goto lab_0x11a78;
        }
        }
    } else {
        goto lab_0x11a78;
    }
lab_0x11a78:;
    // 0x11a78
    struct dirent64 *p_v51;    // 0x117d8
    struct _IO_FILE *p_v52;    // 0x117d8
    struct __dirstream *p_v53; // 0x11c5c
    if (snprintf((char *)&i_v11, 255, "%s/%s/name", &i_v12, p_v50) > 254) {
        // 0x11bdc
        fprintf(p_g4, "%s: path truncated\n", &i_v11);
        goto lab_0x11a5c_2;
    } else {
        struct _IO_FILE *p_v54 = fopen64((char *)&i_v11, "r"); // 0x11aa4
        p_v52 = p_v54;
        if (p_v54 == NULL) {
            int32_t i_v55 = snprintf((char *)&i_v11, 255, "%s/%s/device/name",
                                     &i_v12, p_v50); // 0x11c14
            if (i_v55 > 254) {
                // 0x11bdc
                fprintf(p_g4, "%s: path truncated\n", &i_v11);
                goto lab_0x11a5c_2;
            } else {
                struct _IO_FILE *p_v56 =
                    fopen64((char *)&i_v11, "r"); // 0x11c28
                p_v52 = p_v56;
                if (p_v56 == NULL) {
                    // 0x11c34
                    if (snprintf((char *)&i_v11, 255, "%s/%s/device", &i_v12,
                                 p_v50) > 254) {
                        // 0x11bdc
                        fprintf(p_g4, "%s: path truncated\n", &i_v11);
                        goto lab_0x11a5c_2;
                    } else {
                        // 0x11c58
                        p_v53 = opendir((char *)&i_v11);
                        if (p_v53 == NULL) {
                            goto lab_0x11a5c_2;
                        } else {
                            struct dirent64 *p_v57 =
                                readdir64(p_v53); // 0x11c80
                            p_v51 = p_v57;
                            if (p_v57 == NULL) {
                                goto lab_0x11a5c_2;
                            } else {
                                goto lab_0x11c98;
                            }
                        }
                    }
                } else {
                    goto lab_0x11ab0;
                }
            }
        } else {
            goto lab_0x11ab0;
        }
    }
lab_0x11a5c_2:;
    struct dirent64 *p_v58 = readdir64(p_v13); // 0x11a60
    p_v6 = p_v58;
    i_v8 = i_v47;
    i_v10 = i_v48;
    i_v9 = i_v47;
    if (p_v58 == NULL) {
        goto lab_0x11bac;
    } else {
        goto lab_0x11a6c_2;
    }
lab_0x11ab0:;
    char *p_v59 = fgets((char *)&i_v18, 120, p_v52); // 0x11ac4
    fclose(p_v52);
    if (p_v59 == NULL) {
        // 0x11da0
        fprintf(p_g4, "%s: read error\n", &i_v11);
        goto lab_0x11a5c_2;
    } else {
        char *p_v60 = strchr((char *)&i_v18, 10); // 0x11ae8
        if (p_v60 == NULL) {
            goto lab_dec_label_pc_0x11b04;
        } else {
            *p_v60 = 0;
            goto lab_dec_label_pc_0x11b04;
        }
    }
lab_dec_label_pc_0x11b04:;
    int32_t i_v61; // 0x117d8
    int32_t i_v62; // bp-956, 0x117d8
    if (sscanf(p_v50, "i2c-%d", &i_v62) == 0) {
        goto lab_0x11a5c_2;
    } else {
        int32_t i_v63 = strncmp((char *)&i_v18, "ISA ", 4); // 0x11b20
        i_v61 = 8;
        if (i_v63 == 0) {
            goto lab_0x11b30;
        } else {
            // 0x11d20
            int32_t i_v64; // bp-948, 0x117d8
            int32_t i_v65 = function_116a8(i_v62, &i_v64, 20, 1); // 0x11d30
            i_v61 = 32;
            if (i_v65 >= 0) {
                int32_t i_v66 =
                    ioctl(i_v65, 1797) >= 0
                        ? i_v2 % 2 == 0 ? (i_v2 & 0x7e0000) == 0 ? 0 : 24 : 16
                        : 32;
                close(i_v65);
                i_v61 = i_v66;
                goto lab_0x11b30;
            } else {
                goto lab_0x11b30;
            }
        }
    }
lab_0x11b30:;
    int32_t i_v67 = i_v48 + 1; // 0x11b30
    int32_t i_v68 = i_v47;     // 0x11b38
    if (i_v67 % 8 == 0) {
        int32_t i_v69 = function_115a8(i_v47, i_v67); // 0x11b48
        i_v7 = 0;
        i_v68 = i_v69;
        if (i_v69 == 0) {
            goto lab_0x11944;
        } else {
            goto lab_0x11b58;
        }
    } else {
        goto lab_0x11b58;
    }
lab_0x11c98:;
    int32_t i_v70 = (int32_t)p_v51;
    char *p_v71 = (char *)(i_v70 + 19); // 0x11c98
    if (*p_v71 == 46) {
        // 0x11cfc
        switch (*(char *)(i_v70 + 20)) {
        case 0: {
            goto lab_0x11c7c_2;
        }
        case 46: {
            // 0x11d10
            if (*(char *)(i_v70 + 21) == 0) {
                goto lab_0x11c7c_2;
            } else {
                goto lab_0x11ca8;
            }
        }
        default: {
            goto lab_0x11ca8;
        }
        }
    } else {
        goto lab_0x11ca8;
    }
lab_0x11b58:;
    int32_t i_v72 = i_v68 + 16 * i_v48; // 0x11b64
    *(int32_t *)i_v72 = i_v62;
    char *p_v73 = __strdup((char *)&i_v18); // 0x11b6c
    *(int32_t *)(i_v72 + 4) = (int32_t)p_v73;
    i_v23 = i_v68;
    if (p_v73 == NULL) {
        goto lab_0x11950;
    } else {
        int32_t i_v74 = *(int32_t *)(i_v61 + (int32_t)&x_g1);     // 0x11b90
        int32_t i_v75 = *(int32_t *)(i_v61 + (int32_t)&x_g1 + 4); // 0x11b98
        *(int32_t *)(i_v72 + 8) = i_v74;
        *(int32_t *)(i_v72 + 12) = i_v75;
        struct dirent64 *p_v76 = readdir64(p_v13); // 0x11ba0
        p_v44 = p_v76;
        i_v45 = i_v67;
        i_v46 = i_v68;
        i_v9 = i_v68;
        if (p_v76 == NULL) {
            goto lab_0x11bac;
        } else {
            goto lab_0x11a6c_3;
        }
    }
lab_0x11ca8:
    // 0x11ca8
    if (strncmp(p_v71, "i2c-", 4) == 0) {
        int32_t i_v77 = snprintf((char *)&i_v11, 255, "%s/%s/device/%s/name",
                                 &i_v12, p_v50, p_v71); // 0x11cd4
        if (i_v77 > 254) {
            // 0x11d80
            fprintf(p_g4, "%s: path truncated\n", &i_v11);
            goto lab_0x11c7c_2;
        } else {
            struct _IO_FILE *p_v78 = fopen64((char *)&i_v11, "r"); // 0x11ce8
            p_v52 = p_v78;
            if (p_v78 == NULL) {
                goto lab_0x11c7c_2;
            } else {
                goto lab_0x11ab0;
            }
        }
    } else {
        goto lab_0x11c7c_2;
    }
lab_0x11c7c_2:;
    struct dirent64 *p_v79 = readdir64(p_v53); // 0x11c80
    p_v51 = p_v79;
    if (p_v79 == NULL) {
        goto lab_0x11a5c_2;
    } else {
        goto lab_0x11c98;
    }
}

// Address range: 0x11dc0 - 0x11f14
int32_t function_11dc0(int32_t i_a1) {
    char *p_v1 = (char *)i_a1;              // 0x11dd4
    char *p_v2;                             // bp-28, 0x11dc0
    int32_t i_v3 = strtoul(p_v1, &p_v2, 0); // 0x11dd4
    if (!(((char)i_v3 == 0 | *p_v2 != 0))) {
        int32_t i_v4 = i_v3; // 0x11dfc
        if (i_v3 >= 0x100000) {
            // 0x11ec4
            fwrite((int32_t *)"Error: I2C bus out of range!\n", 1, 29, p_g4);
            i_v4 = -2;
        }
        // 0x11e00
        return i_v4;
    }
    int32_t i_v5 = function_117d8(); // 0x11e0c
    if (i_v5 == 0) {
        // 0x11eec
        fwrite((int32_t *)"Error: Out of memory!\n", 1, 22, p_g4);
        // 0x11e00
        return -3;
    }
    int32_t i_v6 = *(int32_t *)(i_v5 + 4); // 0x11e18
    int32_t i_v7 = i_v6;                   // 0x11e28
    int32_t i_v8 = i_v5;                   // 0x11e28
    int32_t i_v9 = -1;                     // 0x11e28
    if (i_v6 == 0) {
        goto lab_0x11e9c;
    lab_0x11e9c:
        // 0x11e9c
        fwrite(
            (int32_t *)"Error: I2C bus name doesn't match any bus present!\n",
            1, 51, p_g4);
        // 0x11e60
        function_11570(i_v5);
        return -1;
    }
    while (true) {
        int32_t i_v10 = i_v9;
        int32_t i_v11 = i_v8;
        int32_t i_v12 = i_v10; // 0x11e38
        if (strcmp((char *)i_v7, p_v1) == 0) {
            if (i_v10 >= 0) {
                // break -> 0x11e74
                break;
            }
            // 0x11e44
            i_v12 = *(int32_t *)i_v11;
        }
        // 0x11e48
        i_v9 = i_v12;
        i_v7 = *(int32_t *)(i_v11 + 20);
        i_v8 = i_v11 + 16;
        if (i_v7 == 0) {
            // 0x11e58
            if (i_v9 == -1) {
                goto lab_0x11e9c;
            } else {
                goto lab_0x11e60;
            }
        }
    }
    // 0x11e74
    fwrite((int32_t *)"Error: I2C bus name is not unique!\n", 1, 35, p_g4);
    i_v9 = -4;
lab_0x11e60:
    // 0x11e60
    function_11570(i_v5);
    return i_v9;
}

// Address range: 0x11f14 - 0x11f88
int32_t function_11f14(int64_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x11f14
    if (ioctl((int32_t)i_a1, i_a3 == 0 ? 1795 : 1798) >= 0) {
        // 0x11f40
        return 0;
    }
    int32_t *p_v1 = __errno_location(); // 0x11f54
    fprintf(p_g4, "Error: Could not set address to 0x%02x: %s\n", i_a2,
            strerror(*p_v1));
    return -*p_v1;
}

// Address range: 0x11f88 - 0x12028
int32_t function_11f88(int32_t i_a1) {
    // 0x11f88
    int32_t i_v1; // bp-20, 0x11f88
    if (fgets((char *)&i_v1, 2, p_g5) == NULL) {
        // 0x12004
        return 0;
    }
    uint32_t i_v2 = i_v1;       // 0x11fb4
    uint32_t i_v3 = i_v2 % 256; // 0x11fb4
    int32_t i_v4;               // 0x11f88
    int32_t i_v5;               // 0x11f88
    if (i_v3 == 89) {
        // 0x12020
        i_v4 = 1;
        goto lab_0x11fec;
    } else {
        char i_v6 = i_v2;
        if (i_v3 < 89) {
            // 0x12010
            i_v4 = i_a1;
            i_v5 = i_a1;
            switch (i_v6) {
            case 78: {
                // 0x12018
                i_v4 = 0;
                goto lab_0x11fec;
            }
            case 10: {
                return i_v5;
            }
            default: {
                goto lab_0x11fec;
            }
            }
        } else {
            // 0x11fc4
            i_v4 = i_a1;
            switch (i_v6) {
            case 110: {
                // 0x12018
                i_v4 = 0;
                goto lab_0x11fec;
            }
            case 121: {
                // 0x12020
                i_v4 = 1;
                goto lab_0x11fec;
            }
            default: {
                goto lab_0x11fec;
            }
            }
        }
    }
lab_0x11fec:
    // 0x11fec
    while (true) {
        uint32_t i_v7 = fgetc(p_g5); // 0x11ff0
        i_v5 = 0;
        if (i_v7 == -1) {
            // break -> 0x12004
            break;
        }
        // 0x11fe0
        i_v1 = 0x1000000 * i_v7 / 0x1000000;
        i_v5 = i_v4;
        if (i_v7 % 256 == 10) {
            // break -> 0x12004
            break;
        }
    }
    // 0x12004
    return i_v5;
}

// Address range: 0x12028 - 0x1205c
int32_t function_12028(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_10940(i_a1, i_a2, i_a3, i_a4); // 0x12038
    return 0x22f0a - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x12064 - 0x12066
int32_t function_12064(void) {
    // 0x12064
    int32_t i_v1; // 0x12064
    return i_v1;
}

// Address range: 0x12068 - 0x12070
int32_t function_12068(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x12068
    return i_a1;
}

// Address range: 0x30000004 - 0x30000005
int32_t function_30000004(void) {
    // 0x30000004
    int32_t i_v1; // 0x30000004
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 60
