//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;
typedef long double float128_t;

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_10560(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10580(void);
int32_t function_1058c(void);
int32_t function_10598(void);
int32_t function_105a4(void);
int32_t function_105b0(void);
int32_t function_105bc(void);
int32_t function_105c8(void);
int32_t function_105d4(void);
int32_t function_105e0(void);
int32_t function_105ec(void);
int32_t function_105f8(void);
int32_t function_10604(void);
int32_t function_10610(void);
int32_t function_1061c(void);
int32_t function_10628(void);
int32_t function_10634(void);
int32_t function_10640(void);
int32_t function_1064c(void);
int32_t function_10658(void);
int32_t function_10664(void);
int32_t function_10670(int32_t i_a1, int32_t i_a2);
int32_t function_10880(void);
int32_t function_108a4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_108ce(int32_t i_a1, int32_t i_a2);
int32_t function_108f4(void);
int32_t function_1090c(void);
int32_t function_10910(int32_t i_a1);
int32_t function_10988(void);
int32_t function_109a0(void);
int32_t function_10ae8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10b24(void);
int32_t function_10b28(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x1090d; // 0x20f10
int32_t i_g2 = 0;       // 0x2105c
char *p_g3;             // 0x21068

// ------------------------ Functions -------------------------

// Address range: 0x10560 - 0x1056c
int32_t function_10560(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10560
    return function_10880();
}

// Address range: 0x10580 - 0x1058c
int32_t function_10580(void) {
    // 0x10580
    int32_t i_v1; // 0x10580
    return i_v1;
}

// Address range: 0x1058c - 0x10598
int32_t function_1058c(void) {
    // 0x1058c
    int32_t i_v1; // 0x1058c
    return i_v1;
}

// Address range: 0x10598 - 0x105a4
int32_t function_10598(void) {
    // 0x10598
    int32_t i_v1; // 0x10598
    return i_v1;
}

// Address range: 0x105a4 - 0x105b0
int32_t function_105a4(void) {
    // 0x105a4
    int32_t i_v1; // 0x105a4
    return i_v1;
}

// Address range: 0x105b0 - 0x105bc
int32_t function_105b0(void) {
    // 0x105b0
    int32_t i_v1; // 0x105b0
    return i_v1;
}

// Address range: 0x105bc - 0x105c8
int32_t function_105bc(void) {
    // 0x105bc
    int32_t i_v1; // 0x105bc
    return i_v1;
}

// Address range: 0x105c8 - 0x105d4
int32_t function_105c8(void) {
    // 0x105c8
    int32_t i_v1; // 0x105c8
    return i_v1;
}

// Address range: 0x105d4 - 0x105e0
int32_t function_105d4(void) {
    // 0x105d4
    int32_t i_v1; // 0x105d4
    return i_v1;
}

// Address range: 0x105e0 - 0x105ec
int32_t function_105e0(void) {
    // 0x105e0
    int32_t i_v1; // 0x105e0
    return i_v1;
}

// Address range: 0x105ec - 0x105f8
int32_t function_105ec(void) {
    // 0x105ec
    int32_t i_v1; // 0x105ec
    return i_v1;
}

// Address range: 0x105f8 - 0x10604
int32_t function_105f8(void) {
    // 0x105f8
    int32_t i_v1; // 0x105f8
    return i_v1;
}

// Address range: 0x10604 - 0x10610
int32_t function_10604(void) {
    // 0x10604
    int32_t i_v1; // 0x10604
    return i_v1;
}

// Address range: 0x10610 - 0x1061c
int32_t function_10610(void) {
    // 0x10610
    int32_t i_v1; // 0x10610
    return i_v1;
}

// Address range: 0x1061c - 0x10628
int32_t function_1061c(void) {
    // 0x1061c
    int32_t i_v1; // 0x1061c
    return i_v1;
}

// Address range: 0x10628 - 0x10634
int32_t function_10628(void) {
    // 0x10628
    int32_t i_v1; // 0x10628
    return i_v1;
}

// Address range: 0x10634 - 0x10640
int32_t function_10634(void) {
    // 0x10634
    int32_t i_v1; // 0x10634
    return i_v1;
}

// Address range: 0x10640 - 0x1064c
int32_t function_10640(void) {
    // 0x10640
    int32_t i_v1; // 0x10640
    return i_v1;
}

// Address range: 0x1064c - 0x10658
int32_t function_1064c(void) {
    // 0x1064c
    int32_t i_v1; // 0x1064c
    return i_v1;
}

// Address range: 0x10658 - 0x10664
int32_t function_10658(void) {
    // 0x10658
    int32_t i_v1; // 0x10658
    return i_v1;
}

// Address range: 0x10664 - 0x10670
int32_t function_10664(void) {
    // 0x10664
    int32_t i_v1; // 0x10664
    return i_v1;
}

// Address range: 0x10670 - 0x10850
int32_t function_10670(int32_t i_a1, int32_t i_a2) {
    // 0x10670
    function_10580();
    while (true) {
        // 0x106bc
        if (function_109a0() == 0) {
            while (true) {
                // 0x106cc
                function_105d4();
                function_10910(1);
                function_105e0();
                if (function_109a0() != 1) {
                    while (true) {
                    lab_generated_0:
                        function_105d4();
                        // 0x10808
                        function_105c8();
                        goto lab_0x106e4;
                    }
                }
            lab_0x107e4_2:
                // 0x107e4
                function_10910(0);
                if (function_109a0() != 0) {
                    // break -> 0x107fc
                    break;
                }
            }
        }
        // 0x107fc
        function_105a4();
    }
lab_0x10824:
    // 0x10824
    function_10910(0);
    if (i_a1 < 2) {
        // 0x10844
        function_105a4();
        // 0x1083c
        function_10610();
        // 0x10844
        function_105a4();
        goto lab_0x1083c;
    } else {
        // 0x10830
        function_10598();
        // 0x1083c
        function_10610();
        // 0x10844
        function_105a4();
        goto lab_0x1083c;
    }
lab_0x106e4:
    // 0x106e4
    if (function_109a0() == 1) {
        // break -> 0x107e4
        goto lab_0x107e4_2;
    }
    goto lab_generated_1;
}

// Address range: 0x10850 - 0x10878
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10850
    function_105ec();
    return function_10664();
}

// Address range: 0x10880 - 0x1089c
int32_t function_10880(void) {
    // 0x10880
    if (i_g2 == 0) {
        int32_t i_v1; // 0x10880
        return i_v1;
    }
    // 0x10898
    return function_10604();
}

// Address range: 0x108a4 - 0x108cc
int32_t function_108a4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x108a4
    bool i_v1; // 0x108a4
    if (!i_v1 && false) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x108ce - 0x108f2
int32_t function_108ce(int32_t i_a1, int32_t i_a2) {
    // 0x108ce
    int32_t i_v1; // 0x108ce
    return 32 * i_v1 | 0x20000;
}

// Address range: 0x108f4 - 0x1090c
int32_t function_108f4(void) {
    // 0x108f4
    int32_t i_v1; // 0x108f4
    if (*(char *)&p_g3 == 0) {
        // 0x10902
        int32_t i_v2;                                       // 0x108f4
        int32_t i_v3 = function_108a4(i_v2, i_v2, i_v2, 0); // 0x10902
        *(char *)&p_g3 = 1;
        i_v1 = i_v3;
    }
    // 0x1090a
    return i_v1;
}

// Address range: 0x1090c - 0x1090e
int32_t function_1090c(void) {
    // 0x1090c
    int32_t i_v1; // 0x1090c
    return i_v1;
}

// Address range: 0x10910 - 0x10988
int32_t function_10910(int32_t i_a1) {
    // 0x10910
    __asm_vmov_i32(0);
    float64_t f_v1; // 0x10910
    int32_t i_v2;   // 0x10910
    __asm_vst1_8(f_v1, f_v1, i_v2);
    __asm_vstr(f_v1, i_v2);
    __asm_vstr(f_v1, i_v2);
    __asm_vstr(f_v1, i_v2);
    __asm_vstr(f_v1, i_v2);
    __asm_vstr(f_v1, i_v2);
    __asm_vstr(f_v1, i_v2);
    function_1064c();
    function_105f8();
    function_1064c();
    return function_105f8();
}

// Address range: 0x10988 - 0x109a0
int32_t function_10988(void) {
    // 0x10988
    function_10628();
    return 0;
}

// Address range: 0x109a0 - 0x10ae8
int32_t function_109a0(void) {
    // 0x109a0
    __asm_vmov_i32(0);
    int32_t i_v1;   // 0x109a0
    float64_t f_v2; // 0x109a0
    __asm_vstr(f_v2, i_v1);
    __asm_vst1_8(f_v2, f_v2, i_v1);
    __asm_vstr(f_v2, i_v1);
    __asm_vstr(f_v2, i_v1);
    __asm_vstr(f_v2, i_v1);
    __asm_vstr(f_v2, i_v1);
    __asm_vstr(f_v2, i_v1);
    function_1064c();
    if (function_10628() == 0) {
        // 0x10a64
        function_1064c();
        int32_t i_v3; // 0x109a0
        if (function_10658() == 0) {
            // 0x10ad4
            function_105e0();
            i_v3 = -1;
        } else {
            // 0x10a90
            function_1058c();
            function_10634();
            i_v3 = i_v1 != 0;
        }
        // 0x10ab4
        return i_v3;
    }
    // 0x109f0
    if (function_10658() == 0) {
        // 0x10abc
        function_105e0();
        return -1;
    }
    // 0x10a0c
    function_1064c();
    function_1061c();
    if (function_105bc() != 1) {
        // 0x10a44
        function_105e0();
    }
    // 0x10a50
    function_10634();
    return -1;
}

// Address range: 0x10ae8 - 0x10b1c
int32_t function_10ae8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_10560(i_a1, i_a2, i_a3, i_a4); // 0x10af8
    int32_t i_v2 =
        (int32_t) "pen64" + 0x10af8 - (int32_t)&i_g1 >> 2 == 0 ? i_v1 : i_a1;
    return i_v2;
}

// Address range: 0x10b24 - 0x10b26
int32_t function_10b24(void) {
    // 0x10b24
    int32_t i_v1; // 0x10b24
    return i_v1;
}

// Address range: 0x10b28 - 0x10b30
int32_t function_10b28(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10b28
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 34
