//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <dirent.h>
#include <errno.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stropts.h>
#include <unistd.h>

// ----------------- Float Types Definitions ------------------

typedef double float64_t;

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

struct __dirstream {
    int32_t e0;
};

struct dirent64 {
    int32_t e0;
    int32_t e1;
    int16_t e2;
    char e3;
    char e4[256];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_109e8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t *function_10a08(int32_t nmemb, int32_t size);
int32_t function_10a14(char *s1, char *s2);
int32_t function_10a20(char *nptr, char **endptr, int32_t base);
int32_t function_10a2c(char *format, ...);
int32_t function_10a38(struct _IO_FILE *stream);
void function_10a44(int32_t *ptr);
char *function_10a50(char *s, int32_t n, struct _IO_FILE *stream);
int32_t *function_10a5c(int32_t *ptr, int32_t size);
int32_t function_10a68(char *s1, char *s2);
int32_t function_10a74(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s);
int32_t function_10a80(int32_t fd, int32_t request, ...);
char *function_10a8c(char *dest, char *src);
int32_t function_10a98(int32_t i_a1, int32_t i_a2);
struct __dirstream *function_10aa4(char *name);
int32_t function_10ab0(char *file, int32_t oflag, ...);
int32_t *function_10abc(int32_t size);
int32_t function_10ac8(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)());
char *function_10ad4(int32_t errnum);
void function_10ae0(void);
void function_10aec(int32_t status);
int32_t function_10af8(char *nptr, char **endptr, int32_t base);
int32_t function_10b04(int32_t i_a1);
int32_t function_10b10(char *s);
char *function_10b1c(char *s, int32_t c);
int32_t function_10b28(struct _IO_FILE *stream, char *format, ...);
int32_t *function_10b34(void);
int32_t function_10b40(char *s, int32_t maxlen, char *format, ...);
int32_t function_10b4c(char *s, char *format, ...);
char *function_10b58(char *string);
int32_t *function_10b64(int32_t *s, int32_t c, int32_t n);
int32_t function_10b70(struct _IO_FILE *stream);
int32_t function_10b7c(struct _IO_FILE *stream);
int32_t function_10b88(int32_t i_a1, int32_t i_a2);
char *function_10b94(char *s, int32_t c);
int32_t function_10ba0(char *s, char *format, ...);
struct dirent64 *function_10bac(struct __dirstream *dirp);
int32_t function_10bb8(int32_t i_a1, int32_t i_a2);
struct _IO_FILE *function_10bc4(char *filename, char *modes);
int32_t function_10bd0(char *s1, char *s2, int32_t n);
void function_10bdc(void);
int32_t function_10be8(int32_t fd);
int32_t function_10bf4(struct __dirstream *dirp);
int32_t function_10c00(uint32_t i_a1, int32_t i_a2);
int32_t function_113e4(void);
int32_t function_113f0(void);
int32_t function_11414(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_11468(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_1147c(void);
int32_t function_11480(void);
int32_t function_114ac(int32_t i_a1);
int32_t function_1151c(int32_t i_a1);
int32_t function_11554(int32_t i_a1, int32_t i_a2);
int32_t function_1159c(int32_t i_a1, int32_t i_a2);
int32_t function_11654(int32_t i_a1, int32_t *p_a2, int32_t i_a3, int32_t i_a4);
int32_t function_11784(void);
int32_t function_11d6c(int32_t i_a1);
int32_t function_11ec0(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_11f34(int32_t i_a1);
int32_t function_11fd4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_12010(void);
int32_t function_12014(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t unknown_240(void);

// --------------------- Global Variables ---------------------

char *x_g1[10] = {"dummy",   "Dummy bus",   "isa",   "ISA bus",
                  "i2c",     "I2C adapter", "smbus", "SMBus adapter",
                  "unknown", "N/A"}; // 0x125ac
int32_t i_g2 = 0x1147d;       // 0x22f08
int32_t i_g3 = 0;             // 0x230b4
struct _IO_FILE *p_g4 = NULL; // 0x230c0
struct _IO_FILE *p_g5 = NULL; // 0x230c8
int32_t i_g6;
int32_t i_g7;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int32_t i_a1, int32_t i_a2, char **p_a3,
                          void (*p_a4)(), void (*p_a5)(), void (*p_a6)());
char *__strdup(char *p_a1);
struct _IO_FILE *fopen64(char *p_a1, char *p_a2);
int32_t i2c_smbus_read_byte(int32_t i_a1);
int32_t i2c_smbus_read_byte_data(int32_t i_a1, int32_t i_a2);
int32_t i2c_smbus_read_word_data(int32_t i_a1, int32_t i_a2);
int32_t i2c_smbus_write_byte(int32_t i_a1, int32_t i_a2);
int32_t open64(char *p_a1, int32_t i_a2, ...);
struct dirent64 *readdir64(struct __dirstream *p_a1);

// ------------------------ Functions -------------------------

// Address range: 0x109e8 - 0x109f4
int32_t function_109e8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x109e8
    return function_113f0();
}

// Address range: 0x10a08 - 0x10a14
int32_t *function_10a08(int32_t nmemb, int32_t size) {
    // 0x10a08
    return calloc(nmemb, size);
}

// Address range: 0x10a14 - 0x10a20
int32_t function_10a14(char *s1, char *s2) {
    // 0x10a14
    return strcmp(s1, s2);
}

// Address range: 0x10a20 - 0x10a2c
int32_t function_10a20(char *nptr, char **endptr, int32_t base) {
    // 0x10a20
    return strtol(nptr, endptr, base);
}

// Address range: 0x10a2c - 0x10a38
int32_t function_10a2c(char *format, ...) {
    // 0x10a2c
    return printf(format);
}

// Address range: 0x10a38 - 0x10a44
int32_t function_10a38(struct _IO_FILE *stream) {
    // 0x10a38
    return fflush(stream);
}

// Address range: 0x10a44 - 0x10a50
void function_10a44(int32_t *ptr) {
    // 0x10a44
    free(ptr);
}

// Address range: 0x10a50 - 0x10a5c
char *function_10a50(char *s, int32_t n, struct _IO_FILE *stream) {
    // 0x10a50
    return fgets(s, n, stream);
}

// Address range: 0x10a5c - 0x10a68
int32_t *function_10a5c(int32_t *ptr, int32_t size) {
    // 0x10a5c
    return realloc(ptr, size);
}

// Address range: 0x10a68 - 0x10a74
int32_t function_10a68(char *s1, char *s2) {
    // 0x10a68
    return strcasecmp(s1, s2);
}

// Address range: 0x10a74 - 0x10a80
int32_t function_10a74(int32_t *ptr, int32_t size, int32_t n,
                       struct _IO_FILE *s) {
    // 0x10a74
    return fwrite(ptr, size, n, s);
}

// Address range: 0x10a80 - 0x10a8c
int32_t function_10a80(int32_t fd, int32_t request, ...) {
    // 0x10a80
    return ioctl(fd, request);
}

// Address range: 0x10a8c - 0x10a98
char *function_10a8c(char *dest, char *src) {
    // 0x10a8c
    return strcpy(dest, src);
}

// Address range: 0x10a98 - 0x10aa4
int32_t function_10a98(int32_t i_a1, int32_t i_a2) {
    // 0x10a98
    return i2c_smbus_write_byte(i_a1, i_a2);
}

// Address range: 0x10aa4 - 0x10ab0
struct __dirstream *function_10aa4(char *name) {
    // 0x10aa4
    return opendir(name);
}

// Address range: 0x10ab0 - 0x10abc
int32_t function_10ab0(char *file, int32_t oflag, ...) {
    // 0x10ab0
    return open64(file, oflag);
}

// Address range: 0x10abc - 0x10ac8
int32_t *function_10abc(int32_t size) {
    // 0x10abc
    return malloc(size);
}

// Address range: 0x10ac8 - 0x10ad4
int32_t function_10ac8(int32_t main, int32_t argc, char **ubp_av,
                       void (*init)(), void (*fini)(), void (*rtld_fini)()) {
    // 0x10ac8
    return __libc_start_main(main, argc, ubp_av, init, fini, rtld_fini);
}

// Address range: 0x10ad4 - 0x10ae0
char *function_10ad4(int32_t errnum) {
    // 0x10ad4
    return strerror(errnum);
}

// Address range: 0x10ae0 - 0x10aec
void function_10ae0(void) {
    // 0x10ae0
    __gmon_start__();
}

// Address range: 0x10aec - 0x10af8
void function_10aec(int32_t status) {
    // 0x10aec
    exit(status);
}

// Address range: 0x10af8 - 0x10b04
int32_t function_10af8(char *nptr, char **endptr, int32_t base) {
    // 0x10af8
    return strtoul(nptr, endptr, base);
}

// Address range: 0x10b04 - 0x10b10
int32_t function_10b04(int32_t i_a1) {
    // 0x10b04
    return i2c_smbus_read_byte(i_a1);
}

// Address range: 0x10b10 - 0x10b1c
int32_t function_10b10(char *s) {
    // 0x10b10
    return strlen(s);
}

// Address range: 0x10b1c - 0x10b28
char *function_10b1c(char *s, int32_t c) {
    // 0x10b1c
    return strchr(s, c);
}

// Address range: 0x10b28 - 0x10b34
int32_t function_10b28(struct _IO_FILE *stream, char *format, ...) {
    // 0x10b28
    return fprintf(stream, format);
}

// Address range: 0x10b34 - 0x10b40
int32_t *function_10b34(void) {
    // 0x10b34
    return __errno_location();
}

// Address range: 0x10b40 - 0x10b4c
int32_t function_10b40(char *s, int32_t maxlen, char *format, ...) {
    // 0x10b40
    return snprintf(s, maxlen, format);
}

// Address range: 0x10b4c - 0x10b58
int32_t function_10b4c(char *s, char *format, ...) {
    // 0x10b4c
    return sscanf(s, format);
}

// Address range: 0x10b58 - 0x10b64
char *function_10b58(char *string) {
    // 0x10b58
    return __strdup(string);
}

// Address range: 0x10b64 - 0x10b70
int32_t *function_10b64(int32_t *s, int32_t c, int32_t n) {
    // 0x10b64
    return memset(s, c, n);
}

// Address range: 0x10b70 - 0x10b7c
int32_t function_10b70(struct _IO_FILE *stream) {
    // 0x10b70
    return fgetc(stream);
}

// Address range: 0x10b7c - 0x10b88
int32_t function_10b7c(struct _IO_FILE *stream) {
    // 0x10b7c
    return fclose(stream);
}

// Address range: 0x10b88 - 0x10b94
int32_t function_10b88(int32_t i_a1, int32_t i_a2) {
    // 0x10b88
    return i2c_smbus_read_word_data(i_a1, i_a2);
}

// Address range: 0x10b94 - 0x10ba0
char *function_10b94(char *s, int32_t c) {
    // 0x10b94
    return strrchr(s, c);
}

// Address range: 0x10ba0 - 0x10bac
int32_t function_10ba0(char *s, char *format, ...) {
    // 0x10ba0
    return sprintf(s, format);
}

// Address range: 0x10bac - 0x10bb8
struct dirent64 *function_10bac(struct __dirstream *dirp) {
    // 0x10bac
    return readdir64(dirp);
}

// Address range: 0x10bb8 - 0x10bc4
int32_t function_10bb8(int32_t i_a1, int32_t i_a2) {
    // 0x10bb8
    return i2c_smbus_read_byte_data(i_a1, i_a2);
}

// Address range: 0x10bc4 - 0x10bd0
struct _IO_FILE *function_10bc4(char *filename, char *modes) {
    // 0x10bc4
    return fopen64(filename, modes);
}

// Address range: 0x10bd0 - 0x10bdc
int32_t function_10bd0(char *s1, char *s2, int32_t n) {
    // 0x10bd0
    return strncmp(s1, s2, n);
}

// Address range: 0x10bdc - 0x10be8
void function_10bdc(void) {
    // 0x10bdc
    abort();
}

// Address range: 0x10be8 - 0x10bf4
int32_t function_10be8(int32_t fd) {
    // 0x10be8
    return close(fd);
}

// Address range: 0x10bf4 - 0x10c00
int32_t function_10bf4(struct __dirstream *dirp) {
    // 0x10bf4
    return closedir(dirp);
}

// Address range: 0x10c00 - 0x113c0
int32_t function_10c00(uint32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = 0; // 0x10c2c
    int32_t i_v2 = 0; // 0x10c2c
    int32_t i_v3 = 0; // 0x10c2c
    int32_t i_v4 = 0; // 0x10c2c
    int32_t i_v5 = 1; // 0x10c2c
    int32_t i_v6;     // 0x10c00
    int32_t i_v7;     // 0x10c00
    int32_t i_v8;     // 0x10c00
    int32_t i_v9;     // 0x10c00
    int32_t i_v10;    // 0x10c00
    int32_t i_v11;    // 0x10cec
    if (i_a1 >= 2) {
        int32_t i_v12 = i_a2 + 4;          // 0x10c30
        int32_t i_v13 = *(int32_t *)i_v12; // 0x10c30
        char *p_v14 = (char *)i_v13;       // 0x10c34
        char *p_v15 = p_v14;               // 0x10c3c
        int32_t i_v16 = i_v13;             // 0x10c3c
        int32_t i_v17 = i_v12;             // 0x10c3c
        int32_t i_v18 = 0;                 // 0x10c3c
        int32_t i_v19 = 0;                 // 0x10c3c
        int32_t i_v20 = 0;                 // 0x10c3c
        int32_t i_v21 = 0;                 // 0x10c3c
        int32_t i_v22 = 1;                 // 0x10c3c
        i_v1 = 0;
        i_v2 = 0;
        i_v3 = 0;
        i_v4 = 0;
        i_v5 = 1;
        if (*p_v14 == 45) {
            while (true) {
                // 0x10c40
                i_v7 = i_v22;
                int32_t i_v23 = i_v21;
                int32_t i_v24 = i_v20;
                int32_t i_v25 = i_v19;
                int32_t i_v26 = i_v18;
                unsigned char i_v27 = *(char *)(i_v16 + 1); // 0x10c40
                i_g6 = (int32_t)i_v27 - 86;
                int32_t i_v28 = i_v23; // 0x10c4c
                int32_t i_v29 = 1;     // 0x10c4c
                int32_t i_v30 = i_v25; // 0x10c4c
                int32_t i_v31 = i_v26; // 0x10c4c
                switch (i_v27) {
                case 86: {
                    // 0x10db4
                    i_v28 = 1;
                    i_v29 = i_v24;
                    i_v30 = i_v25;
                    i_v31 = i_v26;
                }
                case 102: {
                lab_0x10ce8:
                    // 0x10ce8
                    i_v6 = i_v31;
                    i_v10 = i_v30;
                    i_v9 = i_v29;
                    i_v8 = i_v28;
                    i_v11 = i_v7 + 1;
                    if (i_v11 >= i_a1) {
                        goto lab_0x10cf8_2;
                    }
                    // break -> 0x10c30
                    break;
                }
                case 121: {
                    // 0x10dbc
                    i_v28 = i_v23;
                    i_v29 = i_v24;
                    i_v30 = 1;
                    i_v31 = i_v26;
                    // branch (via goto) -> 0x10ce8
                    goto lab_0x10ce8;
                }
                case 97: {
                    // 0x10dac
                    i_v28 = i_v23;
                    i_v29 = i_v24;
                    i_v30 = i_v25;
                    i_v31 = 1;
                    // branch (via goto) -> 0x10ce8
                    goto lab_0x10ce8;
                }
                default: {
                    // 0x10dc4
                    fprintf(p_g4, "Error: Unsupported option \"%s\"!\n", p_v15);
                    function_11480();
                    // UNREACHABLE
                }
                }
                int32_t i_v32 = i_v17 + 4;         // 0x10c30
                int32_t i_v33 = *(int32_t *)i_v32; // 0x10c30
                char *p_v34 = (char *)i_v33;       // 0x10c34
                p_v15 = p_v34;
                i_v16 = i_v33;
                i_v17 = i_v32;
                i_v18 = i_v6;
                i_v19 = i_v10;
                i_v20 = i_v9;
                i_v21 = i_v8;
                i_v22 = i_v11;
                if (*p_v34 != 45) {
                    goto lab_0x10cf8_2;
                }
            }
            // 0x10dc4
            fprintf(p_g4, "Error: Unsupported option \"%s\"!\n", p_v15);
            function_11480();
            // UNREACHABLE
        }
    }
    goto lab_0x10d00;
lab_0x10cf8_2:
    // 0x10cf8
    i_v1 = i_v6;
    i_v2 = i_v10;
    i_v3 = i_v9;
    i_v4 = i_v7;
    i_v5 = i_v11;
    if (i_v8 != 0) {
        // 0x10e04
        fprintf(p_g4, "i2cget version %s\n", "4.1");
        exit(0);
        // UNREACHABLE
    }
    goto lab_0x10d00;
lab_0x10d00:
    // 0x10d00
    if (i_v4 + 2 >= i_a1) {
        // 0x10e00
        function_11480();
        // UNREACHABLE
    }
    int32_t i_v35 = 4 * i_v5 + i_a2;                   // 0x10d0c
    int32_t i_v36 = function_11d6c(*(int32_t *)i_v35); // 0x10d18
    if (i_v36 < 0) {
        // 0x10e00
        function_11480();
        // UNREACHABLE
    }
    int32_t i_v37 = function_1159c(*(int32_t *)(i_v35 + 4), i_v1); // 0x10d34
    if (i_v37 < 0) {
        // 0x10e00
        function_11480();
        // UNREACHABLE
    }
    int32_t i_v38 = 1;  // 0x10d58
    int32_t i_v39 = -1; // 0x10d58
    if (i_v4 + 3 < i_a1) {
        // 0x10e2c
        char *p_v40; // bp-68, 0x10c00
        int32_t i_v41 =
            strtol((char *)*(int32_t *)(i_v35 + 8), &p_v40, 0); // 0x10e38
        if (*p_v40 != 0) {
            // 0x10de0
            fwrite((int32_t *)"Error: Data address invalid!\n", 1, 29, p_g4);
            // 0x10e00
            function_11480();
            // UNREACHABLE
        }
        // 0x10e50
        i_v38 = 2;
        i_v39 = i_v41;
        if (i_v41 >= 255 == (i_v41 != 255)) {
            // 0x10de0
            fwrite((int32_t *)"Error: Data address invalid!\n", 1, 29, p_g4);
            // 0x10e00
            function_11480();
            // UNREACHABLE
        }
    }
    uint32_t i_v42 = i_v39;
    int32_t i_v43 = i_v38; // 0x10d64
    if (i_v4 + 4 < i_a1) {
        // 0x10d68
        i_v43 = 1;
        switch (*(char *)*(int32_t *)(i_v35 + 12)) {
        case 99: {
            goto lab_0x10e7c;
        }
        case 119: {
            // 0x10fc0
            i_v43 = 3;
            goto lab_0x10e7c;
        }
        case 98: {
            // 0x10fb4
            i_v43 = 2;
            goto lab_0x10e7c;
        }
        default: {
            // 0x10d88
            fwrite((int32_t *)"Error: Invalid mode!\n", 1, 21, p_g4);
            function_11480();
            // UNREACHABLE
        }
        }
    } else {
        goto lab_0x10e7c;
    }
lab_0x10e7c:;
    // 0x10e7c
    int32_t i_v44;                                        // bp-60, 0x10c00
    int32_t i_v45 = function_11654(i_v36, &i_v44, 20, 0); // 0x10e8c
    if (i_v45 < 0) {
        // 0x10fac
        exit(1);
        // UNREACHABLE
    }
    // 0x10e98
    if (ioctl(i_v45, 1797) < 0) {
        int32_t i_v46 = *__errno_location(); // 0x11350
        fprintf(p_g4,
                "Error: Could not get the adapter functionality matrix: %s\n",
                strerror(i_v46));
        // 0x10fac
        exit(1);
        // UNREACHABLE
    }
    // 0x10eac
    int32_t i_v47; // 0x10c00
    switch (i_v43) {
    case 2: {
        if ((i_v47 & 0x80000) == 0) {
            // 0x10fd4
            fprintf(p_g4, "Error: Adapter does not have %s capability\n",
                    "SMBus read byte");
            // 0x10fac
            exit(1);
            // UNREACHABLE
        }
        // break -> 0x10efc
        break;
    }
    case 3: {
        if ((i_v47 & 0x200000) == 0) {
            // 0x112f8
            fprintf(p_g4, "Error: Adapter does not have %s capability\n",
                    "SMBus read word");
            // 0x10fac
            exit(1);
            // UNREACHABLE
        }
        // break -> 0x10efc
        break;
    }
    default: {
        if ((i_v47 & 0x20000) == 0) {
            // 0x1131c
            fprintf(p_g4, "Error: Adapter does not have %s capability\n",
                    "SMBus receive byte");
            // 0x10fac
            exit(1);
            // UNREACHABLE
        }
        if ((i_v47 & 0x40000) == 0 == (i_v42 != -1)) {
            // 0x10f8c
            fprintf(p_g4, "Error: Adapter does not have %s capability\n",
                    "SMBus send byte");
            // 0x10fac
            exit(1);
            // UNREACHABLE
        }
        // break -> 0x10efc
        break;
    }
    }
    // 0x10efc
    if (function_11ec0(i_v45, i_v37, i_v3) != 0) {
        // 0x10fac
        exit(1);
        // UNREACHABLE
    }
    int32_t i_v48; // 0x10c00
    int32_t i_v49; // 0x10c00
    int32_t i_v50; // 0x10c00
    int32_t i_v51; // 0x10c00
    if (i_v2 == 0) {
        // 0x10ff8
        fwrite((int32_t *)"WARNING! This program can confuse your I2C bus, "
                          "cause data loss and worse!\n",
               1, 75, p_g4);
        fprintf(p_g4, "I will read from device file %s, chip address 0x%02x, ",
                &i_v44, i_v37);
        if (i_v42 < 0 ? i_v42 == 0 : i_v43 == 1) {
            // 0x111e0
            fprintf(p_g4, "data address\n0x%02x", i_v42);
            int32_t i_v52 = (int32_t)p_g4; // 0x11210
            i_v48 = i_v52;
            if (i_v43 == 1) {
                int32_t i_v53 = i_v42 == -1 ? (int32_t) "read byte"
                                            : (int32_t) "write byte/read byte";
                i_v49 = i_v52;
                i_v50 = i_v53;
                goto lab_0x110b8;
            } else {
                goto lab_0x11088;
            }
        } else {
            // 0x11040
            if (i_v42 == -1) {
                // 0x11060
                fwrite((int32_t *)"current data\naddress", 1, 20, p_g4);
                i_v48 = (int32_t)p_g4;
                if (i_v43 == 1) {
                    // 0x1138c
                    fprintf(p_g4, ", using %s.\n", "read byte");
                    fprintf(p_g4, "Continue? [%s] ", "Y/n");
                    fflush(p_g4);
                    if (function_11f34(1) == 0) {
                        // 0x110f8
                        fwrite((int32_t *)"Aborting on user request.\n", 1, 26,
                               p_g4);
                        // 0x10f6c
                        exit(0);
                        // UNREACHABLE
                    }
                    // 0x111b8
                    i_v51 = i2c_smbus_read_byte(i_v45);
                    goto lab_0x11170;
                } else {
                    goto lab_0x11088;
                }
            } else {
                // 0x112c8
                fprintf(p_g4, "data address\n0x%02x", i_v42);
                int32_t i_v54 = (int32_t)p_g4; // 0x112e0
                i_v48 = i_v54;
                i_v49 = i_v54;
                i_v50 = 0x12164;
                if (i_v43 == 1) {
                    goto lab_0x110b8;
                } else {
                    goto lab_0x11088;
                }
            }
        }
    } else {
        goto lab_0x10f24;
    }
lab_0x10f24:
    if (i_v43 == 1) {
        if (i_v42 != -1) {
            // 0x11254
            if (i2c_smbus_write_byte(i_v45, i_v42 % 256) < 0) {
                // 0x11268
                fwrite((int32_t *)"Warning - write failed\n", 1, 23, p_g4);
            }
        }
        // 0x111b8
        i_v51 = i2c_smbus_read_byte(i_v45);
        goto lab_0x11170;
    } else {
        // 0x10f30
        if (i_v43 == 3) {
            // 0x10f38
            uint32_t i_v55;                                         // 0x10c00
            int32_t i_v56 = i2c_smbus_read_word_data(i_v45, i_v55); // 0x10f40
            close(i_v45);
            int32_t i_v57 = 4;     // 0x10f58
            int32_t i_v58 = i_v56; // 0x10f58
            if (i_v56 < 0) {
                struct _IO_FILE *p_v59 = p_g4; // 0x11198
                fwrite((int32_t *)"Error: Read failed\n", 1, 19, p_v59);
                exit(2);
                // UNREACHABLE
            }
            int32_t i_v60 = i_v58;
            int32_t i_v61 = i_v57;
            printf("0x%0*x\n", i_v61, i_v60);
            // 0x10f6c
            exit(0);
            // UNREACHABLE
        }
        // 0x11164
        i_v51 = i2c_smbus_read_byte_data(i_v45, i_v42 % 256);
        goto lab_0x11170;
    }
lab_0x11088:;
    int32_t i_v62 =
        i_v43 == 2 ? (int32_t) "read byte data" : (int32_t) "read word data";
    i_v49 = i_v48;
    i_v50 = i_v62;
    goto lab_0x110b8;
lab_0x11170:
    // 0x11170
    close(i_v45);
    if (i_v51 < 0) {
        // 0x11188
        fwrite((int32_t *)"Error: Read failed\n", 1, 19, p_g4);
        exit(2);
        // UNREACHABLE
    }
    // 0x10f5c
    printf("0x%0*x\n", 2, i_v51);
    // 0x10f6c
    exit(0);
    // UNREACHABLE
lab_0x110b8:
    // 0x110b8
    fprintf((struct _IO_FILE *)i_v49, ", using %s.\n", (char *)i_v50);
    fprintf(p_g4, "Continue? [%s] ", "Y/n");
    fflush(p_g4);
    if (function_11f34(1) == 0) {
        // 0x110f8
        fwrite((int32_t *)"Aborting on user request.\n", 1, 26, p_g4);
        // 0x10f6c
        exit(0);
        // UNREACHABLE
    }
    goto lab_0x10f24;
}

// Address range: 0x113c0 - 0x113e4
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x113c0
    int32_t i_v1; // 0x113c0
    __libc_start_main(0x10c00, i_a2, (char **)&i_v1, (void (*)())0x11fd5,
                      (void (*)())0x10c00, (void (*)())i_a1);
    abort();
    // UNREACHABLE
}

// Address range: 0x113e4 - 0x113e8
int32_t function_113e4(void) {
    // 0x113e4
    return 17;
}

// Address range: 0x113f0 - 0x1140c
int32_t function_113f0(void) {
    // 0x113f0
    if (i_g3 == 0) {
        int32_t i_v1; // 0x113f0
        return i_v1;
    }
    // 0x11408
    __gmon_start__();
    return &i_g7;
}

// Address range: 0x11414 - 0x11468
int32_t function_11414(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x11414
    int32_t i_v1; // 0x11414
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x11414
    if (i_v3) {
        return i_a1;
    }
    bool i_v4; // 0x11414
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x1144c
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x1145c
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    float64_t f_v6; // 0x11414
    __asm_vqrshl_s8(f_v6, f_v6);
    return i_a1;
}

// Address range: 0x11468 - 0x1147c
int32_t function_11468(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    char *p_v1 = (char *)(0x80000 * i_a2 | 0x20000); // 0x1146e
    int32_t i_v2 = i_a1;                             // 0x11470
    if (*p_v1 == 0) {
        // 0x11472
        int32_t i_v3; // 0x11468
        i_v2 = function_11414(i_a1, i_a2, i_v3, 0);
        *p_v1 = 1;
    }
    // 0x1147a
    return i_v2;
}

// Address range: 0x1147c - 0x1147e
int32_t function_1147c(void) {
    // 0x1147c
    int32_t i_v1; // 0x1147c
    return i_v1;
}

// Address range: 0x11480 - 0x114ac
int32_t function_11480(void) {
    // 0x11480
    fwrite((int32_t *)"Usage: i2cget [-f] [-y] [-a] I2CBUS CHIP-ADDRESS "
                      "[DATA-ADDRESS [MODE]]\n  I2CBUS is an integer or an I2C "
                      "bus name\n  ADDRESS is an integer (0x03 - 0x77, or 0x00 "
                      "- 0x7f if -a is given)\n  MODE is one of:\n    b (read "
                      "byte data, default)\n    w (read word data)\n    c "
                      "(write byte/read byte)\n    Append p for SMBus PEC\n",
           1, 311, p_g4);
    exit(1);
    // UNREACHABLE
}

// Address range: 0x114ac - 0x1151c
int32_t function_114ac(int32_t i_a1) {
    int32_t i_v1 = strlen((char *)i_a1); // 0x114b4
    if (i_v1 == 0) {
        // 0x11504
        return 1;
    }
    int32_t i_v2 = i_v1 - 1;
    int32_t i_v3 = i_v2 + i_a1;
    char *p_v4 = (char *)i_v3;
    char i_v5 = *p_v4; // 0x114c0
    int32_t i_v6;      // 0x114ac
    int32_t i_v7;      // 0x114ac
    int32_t i_v8;      // 0x114ac
    char i_v9;         // 0x114ac
    int32_t i_v10;     // 0x114f8
    char *p_v11;       // 0x114ac
    switch (i_v5) {
    case 32: {
    }
    case 10: {
        // 0x114f4
        int32_t i_v12; // 0x114ac
        i_v9 = i_v5 == 10 | i_v5 == 32 ? 0 : (char)i_v12;
        *p_v4 = i_v9;
        i_v6 = i_v3;
        if (i_v2 == 0) {
            // 0x11504
            return 1;
        }
        i_v7 = i_v2;
        while (true) {
        lab_0x114e0:
            // 0x114e0
            i_v8 = i_v7;
            i_v10 = i_v6 - 1;
            p_v11 = (char *)i_v10;
            switch (*p_v11) {
            case 32: {
                goto lab_0x114f4;
            }
            case 10: {
                goto lab_0x114f4;
            }
            default: {
                return i_v8 + 1;
            }
            }
        }
    }
    default: {
        // 0x11514
        return i_v1 + 1;
    }
    }
    // 0x1150c
    return i_v8 + 1;
lab_0x114f4:;
    int32_t i_v13 = i_v8 - 1; // 0x114f4
    *p_v11 = i_v9;
    i_v6 = i_v10;
    i_v7 = i_v13;
    if (i_v13 == 0) {
        // 0x11504
        return 1;
    }
    goto lab_0x114e0;
}

// Address range: 0x1151c - 0x11554
int32_t function_1151c(int32_t i_a1) {
    int32_t i_v1 = *(int32_t *)(i_a1 + 4); // 0x11524
    int32_t i_v2 = i_a1;                   // 0x1152c
    if (i_v1 == 0) {
        // 0x11548
        free((int32_t *)i_a1);
        return &i_g7;
    }
    free((int32_t *)i_v1);
    int32_t i_v3 = *(int32_t *)(i_v2 + 20); // 0x1153c
    i_v2 += 16;
    while (i_v3 != 0) {
        // 0x11534
        free((int32_t *)i_v3);
        i_v3 = *(int32_t *)(i_v2 + 20);
        i_v2 += 16;
    }
    // 0x11548
    free((int32_t *)i_a1);
    return &i_g7;
}

// Address range: 0x11554 - 0x1159c
int32_t function_11554(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = 16 * i_a2;                             // 0x11554
    int32_t *p_v2 = realloc((int32_t *)i_a1, i_v1 + 128); // 0x11568
    int32_t i_v3 = (int32_t)p_v2;                         // 0x11568
    if (p_v2 == NULL) {
        // 0x11590
        function_1151c(i_a1);
    } else {
        // 0x11574
        memset((int32_t *)(i_v1 + i_v3), 0, 128);
    }
    // 0x11588
    return i_v3;
}

// Address range: 0x1159c - 0x11654
int32_t function_1159c(int32_t i_a1, int32_t i_a2) {
    // 0x1159c
    char *p_v1;                                    // bp-20, 0x1159c
    int32_t i_v2 = strtol((char *)i_a1, &p_v1, 0); // 0x115b4
    if ((char)i_v2 == 0 | *p_v1 != 0) {
        // 0x1160c
        fwrite((int32_t *)"Error: Chip address is not a number!\n", 1, 37,
               p_g4);
        // 0x11604
        return -1;
    }
    int32_t i_v3 = i_a2 == 0 ? 3 : 0;
    int32_t i_v4 = i_a2 == 0 ? 119 : 127;
    int32_t i_v5 = i_v2; // 0x11600
    if (i_v3 > i_v2 || i_v4 < i_v2) {
        // 0x11634
        fprintf(p_g4, "Error: Chip address out of range (0x%02lx-0x%02lx)!\n",
                i_v3, i_v4);
        i_v5 = -2;
    }
    // 0x11604
    return i_v5;
}

// Address range: 0x11654 - 0x11784
int32_t function_11654(int32_t i_a1, int32_t *p_a2, int32_t i_a3,
                       int32_t i_a4) {
    // 0x11654
    snprintf((char *)p_a2, i_a3, "/dev/i2c/%d", i_a1);
    *(char *)(i_a3 - 1 + (int32_t)p_a2) = 0;
    int32_t i_v1 = open64((char *)p_a2, 2); // 0x11698
    if (i_v1 >= 0) {
        // 0x116a4
        return i_v1;
    }
    int32_t i_v2 = *__errno_location(); // 0x116b4
    int32_t i_v3 = i_v1;                // 0x11654
    switch (i_v2) {
    case 20: {
    }
    case 2: {
        // 0x1175c
        sprintf((char *)p_a2, "/dev/i2c-%d", i_a1);
        i_v3 = open64((char *)p_a2, 2);
        // break -> 0x116a4
        break;
    }
    }
    // 0x116a4
    return i_v3;
}

// Address range: 0x11784 - 0x11d6c
int32_t function_11784(void) {
    // 0x11784
    int32_t i_v1; // 0x11784
    uint32_t i_v2 = i_v1;
    int32_t *p_v3 = calloc(8, 16); // 0x11794
    int32_t i_v4 = (int32_t)p_v3;  // 0x11794
    if (p_v3 == NULL) {
        // 0x118f0
        return i_v4;
    }
    struct _IO_FILE *p_v5 = fopen64("/proc/bus/i2c", "r"); // 0x117b0
    struct dirent64 *p_v6;                                 // 0x11784
    int32_t i_v7;                                          // 0x11784
    int32_t i_v8;                                          // 0x11784
    int32_t i_v9;                                          // 0x11784
    int32_t i_v10;                                         // 0x11784
    int32_t i_v11;                                         // bp-296, 0x11784
    int32_t i_v12;                                         // bp-552, 0x11784
    struct __dirstream *p_v13;                             // 0x119e0
    if (p_v5 == NULL) {
        struct _IO_FILE *p_v14 = fopen64("/proc/mounts", "r"); // 0x11924
        if (p_v14 == NULL) {
            // 0x118f0
            return i_v4;
        }
        while (fgets((char *)&i_v11, 255, p_v14) != NULL) {
            // 0x11944
            int32_t i_v15; // bp-808, 0x11784
            sscanf((char *)&i_v11, "%*[^ ] %[^ ] %[^ ] %*s\n", &i_v12, &i_v15);
            if (strcasecmp((char *)&i_v15, "sysfs") == 0) {
                // 0x11990
                fclose(p_v14);
                int32_t i_v16 =
                    strlen((char *)&i_v12) + (int32_t)&i_v12; // 0x119b4
                *(int32_t *)i_v16 = 0x616c632f;
                *(int32_t *)(i_v16 + 4) = 0x692f7373;
                *(int32_t *)(i_v16 + 8) = 0x642d6332;
                *(int16_t *)(i_v16 + 12) = 0x7665;
                *(char *)(i_v16 + 14) = 0;
                p_v13 = opendir((char *)&i_v12);
                i_v7 = i_v4;
                if (p_v13 == NULL) {
                    return i_v7;
                } else {
                    struct dirent64 *p_v17 = readdir64(p_v13); // 0x11a0c
                    i_v9 = i_v4;
                    if (p_v17 == NULL) {
                        goto lab_0x11b58;
                    } else {
                        // 0x11a18
                        p_v6 = p_v17;
                        i_v8 = i_v4;
                        i_v10 = 0;
                        goto lab_0x11a18_2;
                    }
                }
            }
        }
        // 0x11984
        fclose(p_v14);
        // 0x118f0
        return i_v4;
    }
    // 0x118c0
    int32_t i_v18;                                  // bp-928, 0x11784
    char *p_v19 = fgets((char *)&i_v18, 120, p_v5); // 0x118d0
    int32_t i_v20 = 1;                              // 0x118e4
    int32_t i_v21 = i_v4;                           // 0x118e4
    int32_t i_v22 = 0;                              // 0x118e4
    if (p_v19 == NULL) {
        // 0x118e8
        fclose(p_v5);
        // 0x118f0
        return i_v4;
    }
    int32_t i_v23; // 0x11784
    while (true) {
        int32_t i_v24 = i_v21;
        uint32_t i_v25 = i_v20;
        char *p_v26 = strrchr((char *)&i_v18, 9); // 0x117dc
        *p_v26 = 0;
        char *p_v27 = strrchr((char *)&i_v18, 9); // 0x117fc
        *p_v27 = 0;
        char *p_v28 = strrchr((char *)&i_v18, 9); // 0x1181c
        *p_v28 = 0;
        sscanf((char *)&i_v18, "i2c-%d", &i_v11);
        int32_t i_v29 = i_v24; // 0x11858
        if (i_v25 % 8 == 0) {
            // 0x1185c
            i_v29 = function_11554(i_v24, i_v25);
            i_v7 = 0;
            if (i_v29 == 0) {
                // break -> 0x118f0
                break;
            }
        }
        int32_t i_v30 = (int32_t)p_v27 + 1; // 0x11800
        int32_t i_v31 = (int32_t)p_v28 + 1; // 0x11820
        int32_t i_v32 = i_v31 + i_v30;      // 0x1183c
        i_v21 = i_v29;
        int32_t *p_v33 = malloc((i_v32 >> 31) + i_v32); // 0x11874
        i_v23 = i_v21;
        if (p_v33 == NULL) {
            goto lab_0x118fc;
        }
        int32_t i_v34 = i_v21 + i_v22;  // 0x1186c
        int32_t i_v35 = (int32_t)p_v33; // 0x11874
        *(int32_t *)i_v34 = i_v11;
        char *p_v36 = strcpy((char *)p_v33, (char *)i_v30); // 0x11890
        *(int32_t *)(i_v34 + 4) = (int32_t)p_v36;
        char *p_v37 = strcpy((char *)(i_v30 + i_v35), (char *)i_v31); // 0x118a4
        *(int32_t *)(i_v34 + 8) = (int32_t)p_v37;
        char *p_v38 = strcpy((char *)(i_v32 + i_v35),
                             (char *)((int32_t)p_v26 + 1)); // 0x118b8
        *(int32_t *)(i_v34 + 12) = (int32_t)p_v38;
        char *p_v39 = fgets((char *)&i_v18, 120, p_v5); // 0x118d0
        i_v20 = i_v25 + 1;
        i_v22 += 16;
        int32_t i_v40 = i_v21; // 0x118e4
        if (p_v39 == NULL) {
            // 0x118e8
            fclose(p_v5);
            // 0x118f0
            return i_v40;
        }
    }
lab_0x118f0:
    // 0x118f0
    return i_v7;
lab_0x118fc:
    // 0x118fc
    function_1151c(i_v23);
    i_v7 = 0;
    return i_v7;
lab_0x11b58:
    // 0x11b58
    closedir(p_v13);
    i_v7 = i_v9;
    goto lab_0x118f0;
lab_0x11a18_2:;
    struct dirent64 *p_v41 = p_v6; // 0x11784
    int32_t i_v42 = i_v10;         // 0x11784
    int32_t i_v43 = i_v8;          // 0x11784
    goto lab_0x11a18_3;
lab_0x11a18_3:;
    int32_t i_v44 = i_v43;
    int32_t i_v45 = i_v42;
    int32_t i_v46 = (int32_t)p_v41;
    char *p_v47 = (char *)(i_v46 + 19); // 0x11a18
    if (*p_v47 == 46) {
        // 0x11b64
        switch (*(char *)(i_v46 + 20)) {
        case 0: {
            goto lab_0x11a08_2;
        }
        case 46: {
            // 0x11b78
            if (*(char *)(i_v46 + 21) == 0) {
                goto lab_0x11a08_2;
            } else {
                goto lab_0x11a24;
            }
        }
        default: {
            goto lab_0x11a24;
        }
        }
    } else {
        goto lab_0x11a24;
    }
lab_0x11a24:;
    // 0x11a24
    struct dirent64 *p_v48;    // 0x11784
    struct _IO_FILE *p_v49;    // 0x11784
    struct __dirstream *p_v50; // 0x11c08
    if (snprintf((char *)&i_v11, 255, "%s/%s/name", &i_v12, p_v47) > 254) {
        // 0x11b88
        fprintf(p_g4, "%s: path truncated\n", &i_v11);
        goto lab_0x11a08_2;
    } else {
        struct _IO_FILE *p_v51 = fopen64((char *)&i_v11, "r"); // 0x11a50
        p_v49 = p_v51;
        if (p_v51 == NULL) {
            int32_t i_v52 = snprintf((char *)&i_v11, 255, "%s/%s/device/name",
                                     &i_v12, p_v47); // 0x11bc0
            if (i_v52 > 254) {
                // 0x11b88
                fprintf(p_g4, "%s: path truncated\n", &i_v11);
                goto lab_0x11a08_2;
            } else {
                struct _IO_FILE *p_v53 =
                    fopen64((char *)&i_v11, "r"); // 0x11bd4
                p_v49 = p_v53;
                if (p_v53 == NULL) {
                    // 0x11be0
                    if (snprintf((char *)&i_v11, 255, "%s/%s/device", &i_v12,
                                 p_v47) > 254) {
                        // 0x11b88
                        fprintf(p_g4, "%s: path truncated\n", &i_v11);
                        goto lab_0x11a08_2;
                    } else {
                        // 0x11c04
                        p_v50 = opendir((char *)&i_v11);
                        if (p_v50 == NULL) {
                            goto lab_0x11a08_2;
                        } else {
                            struct dirent64 *p_v54 =
                                readdir64(p_v50); // 0x11c2c
                            p_v48 = p_v54;
                            if (p_v54 == NULL) {
                                goto lab_0x11a08_2;
                            } else {
                                goto lab_0x11c44;
                            }
                        }
                    }
                } else {
                    goto lab_0x11a5c;
                }
            }
        } else {
            goto lab_0x11a5c;
        }
    }
lab_0x11a08_2:;
    struct dirent64 *p_v55 = readdir64(p_v13); // 0x11a0c
    p_v6 = p_v55;
    i_v8 = i_v44;
    i_v10 = i_v45;
    i_v9 = i_v44;
    if (p_v55 == NULL) {
        goto lab_0x11b58;
    } else {
        goto lab_0x11a18_2;
    }
lab_0x11a5c:;
    char *p_v56 = fgets((char *)&i_v18, 120, p_v49); // 0x11a70
    fclose(p_v49);
    if (p_v56 == NULL) {
        // 0x11d4c
        fprintf(p_g4, "%s: read error\n", &i_v11);
        goto lab_0x11a08_2;
    } else {
        char *p_v57 = strchr((char *)&i_v18, 10); // 0x11a94
        if (p_v57 == NULL) {
            goto lab_dec_label_pc_0x11ab0;
        } else {
            *p_v57 = 0;
            goto lab_dec_label_pc_0x11ab0;
        }
    }
lab_dec_label_pc_0x11ab0:;
    int32_t i_v58; // 0x11784
    int32_t i_v59; // bp-956, 0x11784
    if (sscanf(p_v47, "i2c-%d", &i_v59) == 0) {
        goto lab_0x11a08_2;
    } else {
        int32_t i_v60 = strncmp((char *)&i_v18, "ISA ", 4); // 0x11acc
        i_v58 = 8;
        if (i_v60 == 0) {
            goto lab_0x11adc;
        } else {
            // 0x11ccc
            int32_t i_v61; // bp-948, 0x11784
            int32_t i_v62 = function_11654(i_v59, &i_v61, 20, 1); // 0x11cdc
            i_v58 = 32;
            if (i_v62 >= 0) {
                int32_t i_v63 =
                    ioctl(i_v62, 1797) >= 0
                        ? i_v2 % 2 == 0 ? (i_v2 & 0x7e0000) == 0 ? 0 : 24 : 16
                        : 32;
                close(i_v62);
                i_v58 = i_v63;
                goto lab_0x11adc;
            } else {
                goto lab_0x11adc;
            }
        }
    }
lab_0x11adc:;
    int32_t i_v64 = i_v45 + 1; // 0x11adc
    int32_t i_v65 = i_v44;     // 0x11ae4
    if (i_v64 % 8 == 0) {
        int32_t i_v66 = function_11554(i_v44, i_v64); // 0x11af4
        i_v7 = 0;
        i_v65 = i_v66;
        if (i_v66 == 0) {
            goto lab_0x118f0;
        } else {
            goto lab_0x11b04;
        }
    } else {
        goto lab_0x11b04;
    }
lab_0x11c44:;
    int32_t i_v67 = (int32_t)p_v48;
    char *p_v68 = (char *)(i_v67 + 19); // 0x11c44
    if (*p_v68 == 46) {
        // 0x11ca8
        switch (*(char *)(i_v67 + 20)) {
        case 0: {
            goto lab_0x11c28_2;
        }
        case 46: {
            // 0x11cbc
            if (*(char *)(i_v67 + 21) == 0) {
                goto lab_0x11c28_2;
            } else {
                goto lab_0x11c54;
            }
        }
        default: {
            goto lab_0x11c54;
        }
        }
    } else {
        goto lab_0x11c54;
    }
lab_0x11b04:;
    int32_t i_v69 = i_v65 + 16 * i_v45; // 0x11b10
    *(int32_t *)i_v69 = i_v59;
    char *p_v70 = __strdup((char *)&i_v18); // 0x11b18
    *(int32_t *)(i_v69 + 4) = (int32_t)p_v70;
    i_v23 = i_v65;
    if (p_v70 == NULL) {
        goto lab_0x118fc;
    } else {
        int32_t i_v71 = *(int32_t *)(i_v58 + (int32_t)&x_g1);     // 0x11b3c
        int32_t i_v72 = *(int32_t *)(i_v58 + (int32_t)&x_g1 + 4); // 0x11b44
        *(int32_t *)(i_v69 + 8) = i_v71;
        *(int32_t *)(i_v69 + 12) = i_v72;
        struct dirent64 *p_v73 = readdir64(p_v13); // 0x11b4c
        p_v41 = p_v73;
        i_v42 = i_v64;
        i_v43 = i_v65;
        i_v9 = i_v65;
        if (p_v73 == NULL) {
            goto lab_0x11b58;
        } else {
            goto lab_0x11a18_3;
        }
    }
lab_0x11c54:
    // 0x11c54
    if (strncmp(p_v68, "i2c-", 4) == 0) {
        int32_t i_v74 = snprintf((char *)&i_v11, 255, "%s/%s/device/%s/name",
                                 &i_v12, p_v47, p_v68); // 0x11c80
        if (i_v74 > 254) {
            // 0x11d2c
            fprintf(p_g4, "%s: path truncated\n", &i_v11);
            goto lab_0x11c28_2;
        } else {
            struct _IO_FILE *p_v75 = fopen64((char *)&i_v11, "r"); // 0x11c94
            p_v49 = p_v75;
            if (p_v75 == NULL) {
                goto lab_0x11c28_2;
            } else {
                goto lab_0x11a5c;
            }
        }
    } else {
        goto lab_0x11c28_2;
    }
lab_0x11c28_2:;
    struct dirent64 *p_v76 = readdir64(p_v50); // 0x11c2c
    p_v48 = p_v76;
    if (p_v76 == NULL) {
        goto lab_0x11a08_2;
    } else {
        goto lab_0x11c44;
    }
}

// Address range: 0x11d6c - 0x11ec0
int32_t function_11d6c(int32_t i_a1) {
    char *p_v1 = (char *)i_a1;              // 0x11d80
    char *p_v2;                             // bp-28, 0x11d6c
    int32_t i_v3 = strtoul(p_v1, &p_v2, 0); // 0x11d80
    if (!(((char)i_v3 == 0 | *p_v2 != 0))) {
        int32_t i_v4 = i_v3; // 0x11da8
        if (i_v3 >= 0x100000) {
            // 0x11e70
            fwrite((int32_t *)"Error: I2C bus out of range!\n", 1, 29, p_g4);
            i_v4 = -2;
        }
        // 0x11dac
        return i_v4;
    }
    int32_t i_v5 = function_11784(); // 0x11db8
    if (i_v5 == 0) {
        // 0x11e98
        fwrite((int32_t *)"Error: Out of memory!\n", 1, 22, p_g4);
        // 0x11dac
        return -3;
    }
    int32_t i_v6 = *(int32_t *)(i_v5 + 4); // 0x11dc4
    int32_t i_v7 = i_v6;                   // 0x11dd4
    int32_t i_v8 = i_v5;                   // 0x11dd4
    int32_t i_v9 = -1;                     // 0x11dd4
    if (i_v6 == 0) {
        goto lab_0x11e48;
    lab_0x11e48:
        // 0x11e48
        fwrite(
            (int32_t *)"Error: I2C bus name doesn't match any bus present!\n",
            1, 51, p_g4);
        // 0x11e0c
        function_1151c(i_v5);
        return -1;
    }
    while (true) {
        int32_t i_v10 = i_v9;
        int32_t i_v11 = i_v8;
        int32_t i_v12 = i_v10; // 0x11de4
        if (strcmp((char *)i_v7, p_v1) == 0) {
            if (i_v10 >= 0) {
                // break -> 0x11e20
                break;
            }
            // 0x11df0
            i_v12 = *(int32_t *)i_v11;
        }
        // 0x11df4
        i_v9 = i_v12;
        i_v7 = *(int32_t *)(i_v11 + 20);
        i_v8 = i_v11 + 16;
        if (i_v7 == 0) {
            // 0x11e04
            if (i_v9 == -1) {
                goto lab_0x11e48;
            } else {
                goto lab_0x11e0c;
            }
        }
    }
    // 0x11e20
    fwrite((int32_t *)"Error: I2C bus name is not unique!\n", 1, 35, p_g4);
    i_v9 = -4;
lab_0x11e0c:
    // 0x11e0c
    function_1151c(i_v5);
    return i_v9;
}

// Address range: 0x11ec0 - 0x11f34
int32_t function_11ec0(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x11ec0
    if (ioctl(i_a1, i_a3 == 0 ? 1795 : 1798) >= 0) {
        // 0x11eec
        return 0;
    }
    int32_t *p_v1 = __errno_location(); // 0x11f00
    fprintf(p_g4, "Error: Could not set address to 0x%02x: %s\n", i_a2,
            strerror(*p_v1));
    return -*p_v1;
}

// Address range: 0x11f34 - 0x11fd4
int32_t function_11f34(int32_t i_a1) {
    // 0x11f34
    int32_t i_v1; // bp-20, 0x11f34
    if (fgets((char *)&i_v1, 2, p_g5) == NULL) {
        // 0x11fb0
        return 0;
    }
    uint32_t i_v2 = i_v1;       // 0x11f60
    uint32_t i_v3 = i_v2 % 256; // 0x11f60
    int32_t i_v4;               // 0x11f34
    int32_t i_v5;               // 0x11f34
    if (i_v3 == 89) {
        // 0x11fcc
        i_v4 = 1;
        goto lab_0x11f98;
    } else {
        char i_v6 = i_v2;
        if (i_v3 < 89) {
            // 0x11fbc
            i_v4 = i_a1;
            i_v5 = i_a1;
            switch (i_v6) {
            case 78: {
                // 0x11fc4
                i_v4 = 0;
                goto lab_0x11f98;
            }
            case 10: {
                return i_v5;
            }
            default: {
                goto lab_0x11f98;
            }
            }
        } else {
            // 0x11f70
            i_v4 = i_a1;
            switch (i_v6) {
            case 110: {
                // 0x11fc4
                i_v4 = 0;
                goto lab_0x11f98;
            }
            case 121: {
                // 0x11fcc
                i_v4 = 1;
                goto lab_0x11f98;
            }
            default: {
                goto lab_0x11f98;
            }
            }
        }
    }
lab_0x11f98:
    // 0x11f98
    while (true) {
        uint32_t i_v7 = fgetc(p_g5); // 0x11f9c
        i_v5 = 0;
        if (i_v7 == -1) {
            // break -> 0x11fb0
            break;
        }
        // 0x11f8c
        i_v1 = 0x1000000 * i_v7 / 0x1000000;
        i_v5 = i_v4;
        if (i_v7 % 256 == 10) {
            // break -> 0x11fb0
            break;
        }
    }
    // 0x11fb0
    return i_v5;
}

// Address range: 0x11fd4 - 0x12008
int32_t function_11fd4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_109e8(i_a1, i_a2, i_a3, i_a4); // 0x11fe4
    return 0x22f0a - (int32_t)&i_g2 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x12010 - 0x12012
int32_t function_12010(void) {
    // 0x12010
    int32_t i_v1; // 0x12010
    return i_v1;
}

// Address range: 0x12014 - 0x1201c
int32_t function_12014(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x12014
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 63
